"""int_address_b is NOT NULL

Revision ID: 6e185504ffb5
Revises: 9df2ef0f7f32
Create Date: 2022-05-31 12:06:32.400919+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e185504ffb5'
down_revision = '9df2ef0f7f32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.alter_column('int_address_b',
               existing_type=sa.VARCHAR(length=45),
               nullable=False,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.alter_column('int_address_b',
               existing_type=sa.VARCHAR(length=45),
               nullable=True,
               existing_server_default=sa.text("('')"))

    # ### end Alembic commands ###
