"""sudo nopasswd commands

Revision ID: 48d82c064ea2
Revises: 5b68832586f4
Create Date: 2023-01-18 10:11:13.876642+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d82c064ea2'
down_revision = '5b68832586f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_bsdgroups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsdgrp_sudo_commands_nopasswd', sa.TEXT(), nullable=False, server_default="[]"))

    with op.batch_alter_table('account_bsdusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsdusr_sudo_commands_nopasswd', sa.TEXT(), nullable=False, server_default="[]"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('account_bsdusers', schema=None) as batch_op:
        batch_op.drop_column('bsdusr_sudo_commands_nopasswd')

    with op.batch_alter_table('account_bsdgroups', schema=None) as batch_op:
        batch_op.drop_column('bsdgrp_sudo_commands_nopasswd')

    # ### end Alembic commands ###
