"""add tpm 2.0 emulator for vms

Revision ID: b690e5ae986d
Revises: 9694ff0f4de6
Create Date: 2023-03-05 14:42:01.124356+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b690e5ae986d'
down_revision = '9694ff0f4de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_vm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trusted_platform_module', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_vm', schema=None) as batch_op:
        batch_op.drop_column('trusted_platform_module')

    # ### end Alembic commands ###
