"""Webshare bindip

Revision ID: f2caf540c93f
Revises: 055cfee51499
Create Date: 2026-02-12 15:29:26.410524+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2caf540c93f'
down_revision = '055cfee51499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_webshare', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bindip', sa.TEXT(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_webshare', schema=None) as batch_op:
        batch_op.drop_column('bindip')

    # ### end Alembic commands ###
