"""Remove legacy services

Revision ID: ce5aac1ae6e8
Revises: 5925fe02f2ec
Create Date: 2026-02-24 13:32:17.568289+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = 'ce5aac1ae6e8'
down_revision = '5925fe02f2ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DELETE FROM services_services WHERE srv_service = 'directoryservice'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
