#!/usr/local/bin/python3
#
# Copyright (c) 2015 iXsystems, Inc.
# All rights reserved.
# This file is a part of TrueNAS
# and may not be copied and/or distributed
# without the express permission of iXsystems.

import argparse
import logging
import sys
import subprocess
import getpass

from middlewared.client import Client


def jb_callback(job):
    print(job["progress"]["description"])


def run(cmd):
    proc = subprocess.Popen(
        cmd,
        stderr=subprocess.PIPE,
        stdout=subprocess.PIPE,
        shell=True,
        encoding='utf8',
    )
    output = proc.communicate()[0]
    return (proc.returncode, output.strip('\n'))


log = logging.getLogger('tools.haenc')

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(help='sub-command help', dest='name')
    subparsers.add_parser('clear', help='Clear the passphrase')
    subparsers.add_parser('synctopeer', help='Transfer local passphrase to remote system')
    subparsers.add_parser('syncfrompeer', help='Transfer remote passphrase to local system')
    subparsers.add_parser('shutdown', help='Shutdown the escrow daemon')
    subparsers.add_parser('status', help='Inquiry escrow daemon status')
    subparsers.add_parser('attachall', help='Attach all GELI providers with the escrowd passphrase')
    subparsers.add_parser('detachall', help='Detach all GELI providers')
    iparser = subparsers.add_parser('interactive', help='Sets passphrase securely from the CLI')
    iparser.add_argument('-k', '--key-only', action='store_true', help='Set the key only, do not force failover')

    args = parser.parse_args()

    cmd = args.name
    rv = "Unknown"
    with Client() as c:
        if cmd == 'clear':
            rv = c.call('failover.encryption_clearkey')
        elif cmd == 'shutdown':
            rv = c.call('failover.encryption_shutdown')
        elif cmd == 'status':
            rv = c.call('failover.encryption_status')
            if rv:
                print("Escrowd has the passphrase")
                log.warn("Escrowd has the passphrase")
            else:
                print("Escrowd is running without the passphrase")
                log.warn("Escrowd is running without the passphrase")
        elif cmd == 'attachall':
            c.call('failover.encryption_attachall', timeout=600, job=True, callback=jb_callback)

        elif cmd == 'detachall':
            job = c.call('failover.encryption_detachall', job='RETURN', callback=jb_callback)
            if job.result() is False:
                sys.exit(1)

        elif cmd == 'interactive':
            passphrase = getpass.getpass()
            if passphrase:
                rv = c.call('failover.encryption_setkey', passphrase)
                try:
                    c.call('failover.call_remote', 'failover.encryption_setkey', [passphrase])
                except Exception:
                    print("Failed to set the passphrase on the standby node.")
                    log.warn("Failed to set the passphrase on the standby node.")
                if not args.key_only:
                    c.call('failover.force_master')
        else:
            where = None
            if cmd == 'synctopeer':
                where = 'standby'
                passphrase = c.call('failover.encryption_getkey')
                if passphrase:
                    rv = c.call('failover.call_remote', 'failover.encryption_setkey', [passphrase, {'sync': False}])
                else:
                    print("ERROR: passphrase not detected.")
                    log.warn("ERROR: passphrase not detected.")
            elif cmd == 'syncfrompeer':
                where = 'local'
                passphrase = c.call('failover.call_remote', 'failover.encryption_getkey')
                rv = c.call('failover.encryption_setkey', passphrase, {'sync': False})
            if not rv:
                print(f"ERROR: Failed to sync passphrase on {where} controller.")
                log.warn("ERROR: Failed to sync passphrase on %s controller.", where)

    if rv:
        print("Succeeded")
        sys.exit(0)
    else:
        print("Failed")
        sys.exit(1)
