#!/usr/bin/env python
#-
# Copyright (c) 2015 iXsystems, Inc.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

import argparse
import os
import sys

sys.path.extend([
    '/usr/local/www',
    '/usr/local/www/freenasUI',
])

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'freenasUI.settings')

# Make sure to load all modules
from django.db.models.loading import cache
cache.get_apps()

from freenasUI.middleware.notifier import notifier
_not = notifier()


def main(command):
    if command == "status":
        ret = _not.failover_status()
        if ret == "MASTER":
            print "Node status: Active"
        elif ret == "BACKUP":
            print "Node status: Passive"
        elif ret == "ELECTING":
            print "Node status: Electing master node"
        elif ret == "IMPORTING":
            print "Node status: Transitioning to Active"
        elif ret == "ERROR":
            print "Node status: Faulted"
        elif ret == "SINGLE":
            print "Node status: Not an HA node"
    elif command == "enable":
        from freenasUI.failover.models import Failover
        if Failover.objects.all()[0].disabled is False:
            ip = Failover.objects.all()[0].ipaddress
            ret = os.system("ssh -o ConnectTimeout=3 %s /usr/local/libexec/truenas/hactl-worker enable" % ip)
            if not ret:
                for item in Failover.objects.all():
                    item.disabled = False
                    item.active = False
                    item.save()
                print "Failover enabled."
            else:
                print "Unable to contact remote node.  Failover not enabled."
                sys.exit(2)
        else:
            print "Failover not disabled.  Cannot enable!"
            sys.exit(3)
    elif command == "disable":
        from freenasUI.failover.models import Failover
        ip = Failover.objects.all()[0].ipaddress
        if _not.failover_status() == "MASTER" or _not.failover_status() == "IMPORTING":
            status = "master"
            ret = os.system("ssh -o ConnectTimeout=3 %s /usr/local/libexec/truenas/hactl-worker disable passive" % ip)
        else:
            status = "passive"
            ret = os.system("ssh -o ConnectTimeout=3 %s /usr/local/libexec/truenas/hactl-worker disable active" % ip)
        if not ret:
            for item in Failover.objects.all():
                item.disabled = True
                if status == "master":
                    item.active = True
                else:
                    item.active = False
                item.save()
                print "Failover disabled."
                sys.exit(0)
        else:
            print "Unable to contact remote node.  Failover not disabled."
            sys.exit(3)
    elif command == "takeover":
        ret = _not.failover_status()
        if ret != "BACKUP":
            print "Cannot takeover volume, not passive"
            sys.exit(5)
        print "This will likely cause the active node to reboot."
        while True:
            ret = raw_input("Are you sure you wish to proceed with making this node active? (y/n): ")
            if ret.lower() == "y":
                break
            elif ret.lower() == "n":
                print "Takeover cancelled."
                sys.exit(1)
            else:
                continue
        _not.failover_force_master()
    elif command == "giveback":
        ret = _not.failover_status()
        if ret == "BACKUP":
            print "Cannot giveback volume.  This unit is not Active!"
            sys.exit(6)
        print "Volume giveback will reboot this node."
        while True:
            ret = raw_input("Are you sure you wish to proceed with making the other node active? (y/n): ")
            if ret.lower() == "y":
                break
            elif ret.lower() == "n":
                print "Giveback cancelled."
                sys.exit(1)
            else:
                continue
        os.system("shutdown -r now")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='HA CLI control utility.')
    parser.add_argument('command',
                        default="status",
                        nargs='?',
                        help="subcommand: enable disable status takeover giveback",
                        choices=['enable', 'disable', 'status', 'takeover', 'giveback'],
                        )

    args = parser.parse_args()
    main(args.command)
