#!/bin/sh -ex
(
    cd "$(python3 -c 'import os; import sys; sys.path.remove("") if "" in sys.path else None; import middlewared; print(os.path.dirname(middlewared.__spec__.origin))')" &&
    alembic upgrade head
)
