#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: gui
# REQUIRE: dispatcher datastore

. /etc/rc.subr

name="gui"
pidfile="/var/run/node.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"
gui="/usr/local/sbin/gui"

prestart()
{
    rc_flags="-P ${pidfile} -r ${gui}"
}

load_rc_config $name
run_rc_command $*
