"""Condense nameserver fields of network.configuration entry.

Revision ID: 600a75488ab7
Revises: 9a5b103ec2e4
Create Date: 2025-03-21 16:50:49.063185+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '600a75488ab7'
down_revision = '9a5b103ec2e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_globalconfiguration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gc_nameservers', sa.TEXT(), nullable=False))
        batch_op.drop_column('gc_nameserver1')
        batch_op.drop_column('gc_nameserver2')
        batch_op.drop_column('gc_nameserver3')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_globalconfiguration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gc_nameserver3', sa.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('gc_nameserver2', sa.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('gc_nameserver1', sa.VARCHAR(length=45), nullable=False))
        batch_op.drop_column('gc_nameservers')

    # ### end Alembic commands ###
