"""Periodic snapshot task state

Revision ID: aeae837fb2d5
Revises: 08febd74cdf9
Create Date: 2025-05-08 11:00:43.785325+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aeae837fb2d5'
down_revision = '08febd74cdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_state', sa.Text(), nullable=False, server_default="{}"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('storage_task', schema=None) as batch_op:
        batch_op.drop_column('task_state')

    # ### end Alembic commands ###
