"""Docker registry mirrors

Revision ID: 3693df62fd6f
Revises: d4e0268ca57d
Create Date: 2025-06-30 01:15:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3693df62fd6f'
down_revision = 'd4e0268ca57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_docker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registry_mirrors', sa.Text(), nullable=False, server_default='[]'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_docker', schema=None) as batch_op:
        batch_op.drop_column('registry_mirrors')

    # ### end Alembic commands ###