"""Add primary_kdc key to kerberos realm entries

Revision ID: fe655f29b9c9
Revises: 3d738dbd75ef
Create Date: 2025-07-17 15:44:32.049824+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe655f29b9c9'
down_revision = '3d738dbd75ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directoryservice_kerberosrealm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('krb_primary_kdc', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('directoryservice_kerberosrealm', schema=None) as batch_op:
        batch_op.drop_column('krb_primary_kdc')

    # ### end Alembic commands ###
