"""empty message

Revision ID: beaaa12e897c
Revises: 3693df62fd6f
Create Date: 2025-07-04 19:40:49.111879+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beaaa12e897c'
down_revision = '3693df62fd6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=False),
    sa.Column('memory', sa.Integer(), nullable=False),
    sa.Column('autostart', sa.Boolean(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=False),
    sa.Column('threads', sa.Integer(), nullable=False),
    sa.Column('cpuset', sa.Text(), nullable=True),
    sa.Column('shutdown_timeout', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('init', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_container')),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_container')
    # ### end Alembic commands ###
