"""Add rate_limit field to cloud_backup.

Revision ID: 9c52f1653402
Revises: 2368b4b28a87
Create Date: 2025-07-01 17:20:10.015634+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c52f1653402'
down_revision = '2368b4b28a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_cloud_backup', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate_limit', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_cloud_backup', schema=None) as batch_op:
        batch_op.drop_column('rate_limit')

    # ### end Alembic commands ###
