#!/bin/sh
#
# $FreeBSD$

# PROVIDE: winbindd
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# See .../rc.d/samba for more details.
#

name="smbd"
desc="$name daemon"
: ${smbd_enable=${samba_enable=NO}}
: $(smbd_flags="-D")

. /usr/local/etc/rc.samba

rcvar=$(set_rcvar)

reload_cmd="reload_cmd"

run_rc_command "$1"
