#!/bin/sh
#
# $FreeBSD$

# PROVIDE: winbindd
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# See .../rc.d/samba for more details.
#

name="winbindd"
desc="$name daemon"
: ${winbindd_enable=NO}

. /usr/local/etc/rc.samba

rcvar=$(set_rcvar)

reload_cmd="reload_cmd"

if ! checkyesno ${name}_enable; then
	samba_idmap=$(${samba_parm} 'idmap uid' "${samba_config}" 2>/dev/null)
	if [ -n "${samba_idmap}" ]; then
		${name}_enable="YES"
	fi
fi

run_rc_command "$1"
