#!/bin/sh
#
# $FreeBSD$

# PROVIDE: winbindd
# REQUIRE: NETWORKING SERVERS DAEMON ldconfig resolv
# BEFORE: LOGIN
# KEYWORD: shutdown
#
# See .../rc.d/samba for more details.
#

name="winbindd"

. /usr/local/etc/rc.samba

if checkyesno ${name}_enable || checkyesno samba_enable; then
	eval ${name}_enable="YES"
else
	eval ${name}_enable="NO"
fi
if [ -z "${winbindd_flags:-}" ]; then
	eval ${name}_flags="-D"
fi

rcvar=$(set_rcvar)

if ! checkyesno ${name}_enable; then
	samba_idmap=$(${samba_parm} 'idmap uid' "${samba_config}" 2>/dev/null)
	if [ -n "${samba_idmap}" ]; then
		${name}_enable="YES"
	fi
fi

reload_cmd="reload_cmd"

run_rc_command "$1"
