"""
Add containers devices

Revision ID: e794ef384903
Revises: c3f8d9e2a4b1
Create Date: 2025-10-22 19:48:28.600327+00:00
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e794ef384903'
down_revision = 'c3f8d9e2a4b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.TEXT(), nullable=False),
    sa.Column('container_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(
        ['container_id'], ['container_container.id'], name=op.f('fk_container_device_container_id_container_container')
    ),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_device')),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('container_device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_container_device_container_id'), ['container_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    pass
