""" Add stateful_failover to SMB service

Revision ID: ec5dad4625ad
Revises: 2b73cb14b156
Create Date: 2025-12-19 20:18:56.674064+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5dad4625ad'
down_revision = '2b73cb14b156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cifs_srv_stateful_failover', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.drop_column('cifs_srv_stateful_failover')

    # ### end Alembic commands ###
