"""Container

Revision ID: bdddec2904bf
Revises: 94d4fd77c063
Create Date: 2025-07-30 14:14:01.231473+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdddec2904bf'
down_revision = '94d4fd77c063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('container_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bridge', sa.Text(), nullable=True),
    sa.Column('v4_network', sa.Text(), nullable=True),
    sa.Column('v6_network', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_config')),
    sqlite_autoincrement=True
    )
    op.create_table('container_container',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('vcpus', sa.Integer(), nullable=True),
    sa.Column('memory', sa.Integer(), nullable=True),
    sa.Column('autostart', sa.Boolean(), nullable=False),
    sa.Column('time', sa.Text(), nullable=False),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('cpuset', sa.Text(), nullable=True),
    sa.Column('shutdown_timeout', sa.Integer(), nullable=False),
    sa.Column('dataset', sa.Text(), nullable=False),
    sa.Column('init', sa.Text(), nullable=False),
    sa.Column('initdir', sa.Text(), nullable=True),
    sa.Column('initenv', sa.TEXT(), nullable=False),
    sa.Column('inituser', sa.Text(), nullable=True),
    sa.Column('initgroup', sa.Text(), nullable=True),
    sa.Column('idmap_uid_target', sa.Integer(), nullable=True),
    sa.Column('idmap_uid_count', sa.Integer(), nullable=True),
    sa.Column('idmap_gid_target', sa.Integer(), nullable=True),
    sa.Column('idmap_gid_count', sa.Integer(), nullable=True),
    sa.Column('capabilities_policy', sa.Text(), nullable=False),
    sa.Column('capabilities_state', sa.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_container_container')),
    sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('container_container')
    op.drop_table('container_config')
    # ### end Alembic commands ###
