"""Webshare service

Revision ID: d5ccdbe6479f
Revises: e41efceeeb41
Create Date: 2025-10-24 10:42:18.331279+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ccdbe6479f'
down_revision = 'e41efceeeb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_webshare',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services_webshare')),
    sqlite_autoincrement=True
    )
    op.create_table('sharing_webshare_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sharing_webshare_share')),
    sqlite_autoincrement=True
    )
    op.execute(sa.text("INSERT INTO services_services (srv_service, srv_enable) VALUES ('webshare', 0)"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sharing_webshare_share')
    op.drop_table('services_webshare')
    # ### end Alembic commands ###
