#############################################################################
# Makefile for building: pc-extractoverlay
#############################################################################

####### Install

all:

install_doinstall:
	sh install.sh

install:  install_doinstall
