.Dd Nov 16, 2010
.Dt PBI_MAKEREPO 1
.Os
.Sh NAME
.Nm pbi_makerepo
.Nd Make a new PBI Repo file
.Sh SYNOPSIS
.Nm
.Op Fl -desc Ar description
.Op Fl -key Ar keyfile
.Op Fl -mirror Ar mirrorurl
.Op Fl -url Ar indexurl
.Op Ar outdir
.Sh DESCRIPTION
The utility,
.Nm ,
can be used to make a new PBI repo file (.rpo), which when imported can be used
to add pbis with pbi_add -r, or to automatically update PBIs. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl -desc Ar description
(Required) Description of the repo, which will be shown in the repo list
.It Fl -key Ar keyfile
(Required) The specified openssl public key which will be used to verify the digital
signature of PBIs installed from this repo. The public file can be created
with the openssl command below:
# openssl genrsa -out privkey.pem 4056
# openssl rsa -in privkey.pem -pubout 
.It Fl -mirror Ar mirrorurl
(Required) The url you wish this repo to use when downloading PBIs and updates found
in the repo's index file. Multiple mirrors can be specified by using ','. Mirrors will be used in the order they are listed. 
.It Fl -url Ar indexurl
(Required) The url you wish this repo to use when trying to download the master
INDEX files of PBIs available. I.E. "http://update.pbidir.com", will be expanded
to "http://update.pbidir.com/pbi-index-<major freebsd version>"
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_patch 1
