.Dd Sept 15, 2010
.Dt PBI_MAKEPATCH 1
.Os
.Sh NAME
.Nm pbi_makepatch
.Nd Make a PBP patch file
.Sh SYNOPSIS
.Nm
.Op Fl o Ar outdir
.Op Fl -sign Ar keyfile
.Op Ar oldpbi
.Op Ar newpbi 
.Sh DESCRIPTION
The utility,
.Nm ,
can be used to make a patch file (*.PBP) for PBI managed software. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl o Ar outdir
Save the resulting .PBP file to the specified outdir
.It Fl -sign Ar keyfile
Use the specified openssl key to digitally sign the patch file
.Sh NOTES
For details about the module format, please refer to the wiki guide:
http://wiki.pcbsd.org/index.php/PBI_Module_Builder_Guide
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_patch 1
