.Dd Nov 9, 2010
.Dt PBID 8
.Os
.Sh NAME
.Nm pbid
.Nd PBI Daemon
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl -refresh
.Op Ar pbi
.Sh DESCRIPTION
The daemon,
.Nm ,
is used keep track of the shared library hash-dir, merging new libraries and pruning old libraries
to keep PBIs disk and ram usage at a minimum. The daemon can be run manually, or by putting
pbid_enable="YES" into /etc/rc.conf
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl v
Enable verbose output
.It Fl -refresh
Schedule a refreshing of index / meta files
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_delete 1
