#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-devd
# REQUIRE: ix-zfs
# BEFORE: devd pf

# Copyright (C) iXsystems 2010
# This file is a part of TrueNAS
# and may not be copied and/or distributed
# without the express permission of iXsystems.

. /etc/rc.subr

#
# Generate CARP hooks right before mountlate.
#
ix_devd_gen()
{
	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT
	/usr/local/bin/python /usr/local/libexec/truenas/generate_failover_json.py
	local IFS=\|

	local failovers=`${FREENAS_SQLITE_CMD} ${RO_FREENAS_CONFIG} "SELECT COUNT(id) FROM system_failover;"`

	if [ "$(LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call notifier.failover_licensed)" = "True" ]; then
		cp /conf/base/etc/devd.conf /etc/devd.conf
		cat >> /etc/devd.conf << E*O*F

notify 100 {
   match "system"   "CARP";
   match "subsystem"      "[0-9]+@[0-9a-z]+";
   action "/usr/local/bin/python /usr/local/libexec/truenas/carp-state-change-hook.py \$subsystem \$type";
};
E*O*F

	else
		/usr/bin/truncate -s 0 /etc/pf.conf
	fi
}

name="ix-devd"
start_cmd='ix_devd_gen'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
