#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-etc
# REQUIRE: dispatcher etcd
# BEFORE: FILESYSTEMS

. /etc/rc.subr

etc_start()
{
	/usr/local/sbin/dispatcherctl call plugin.wait_for_service '"etcd.generation"'
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_all
	killall -ALRM sh
}

name="ix-etc"
start_cmd='etc_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
