#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: failover
# BEFORE: devd

# Copyright (c) 2010 iXsystems, Inc.  All rights reserved.
# This file is a part of TrueNAS
# and may not be copied and/or distributed
# without the express permission of iXsystems.

. /etc/rc.subr

name="failover"
start_cmd='ix_failover_start'
pidfile="/var/run/${name}/heartbeat-check.pid"
procname="/bin/sh"
rcvar="failover_enable"

ix_failover_start()
{ 
	allint=$(ifconfig -l)
	# The midclt call returns something like ["em0"] likely there is better sed to extract the em0 part.
	int=$(LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call failover.internal_interfaces | sed 's/\["\(.*\)"\]/\1/g')
	# "${allint#*$int}" != "$allint" is a really obfuscited way to express "is this substring in this string?"
	# however it is POSIX compliant...so there is that.
	# Note the check to make sure ${int} actually contains a value isn't all that paranoid.
	# The check to ensure that ${int} is a valid interface on the system is a little paranoid.
	if [ "$(LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call failover.licensed)" = "True" -a -n ${int} -a "${allint#*$int}" != "$allint" ]; then
		local IFS=\|

		if [ ! -x /etc/heartbeat-check ]; then
			cat >> /etc/heartbeat-check << E*O*F
#!/bin/sh

while true; do
	S1=\`(ifconfig $int | grep MASTER | wc -l)\`
	S2=\`(ifconfig $int | grep MASTER | wc -l)\`

	if [ \${S1} -eq 1 -a \${S2} -eq 1 ]; then
		touch /tmp/heartbeat_state
	fi
	sleep 29
done
E*O*F
		chmod +x /etc/heartbeat-check
	fi

	mkdir -p `dirname ${pidfile}`
	chown nobody `dirname ${pidfile}`
	daemon -cf -p ${pidfile} -u nobody /etc/heartbeat-check
	fi
}

load_rc_config $name
run_rc_command "$1"
