#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: failover
# BEFORE: devd

# Copyright (C) iXsystems 2010
# This file is a part of TrueNAS
# and may be copied and/or distributed
# without the express permission of iXsystems.

. /etc/rc.subr

name="failover"
start_cmd='ix_failover_start'
pidfile="/var/run/${name}/heartbeat-check.pid"
procname="/bin/sh"
rcvar="failover_enable"

ix_failover_start()
{
	local IFS=\|

	if [ ! -x /etc/heartbeat-check ]; then
		cat >> /etc/heartbeat-check << E*O*F
#!/bin/sh

while true; do
	S1=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep MASTER | wc -l\`
	S2=\`(ifconfig carp1 | grep carp: | awk '{print \$2;}' ; ifconfig carp2 | grep carp: | awk '{print \$2;}')| grep BACKUP | wc -l\`

	if [ \${S1} -eq 1 -a \${S2} -eq 1 ]; then
		touch /tmp/heartbeat_state
	fi
	sleep 29
done
E*O*F
		chmod +x /etc/heartbeat-check
	fi

	mkdir -p `dirname ${pidfile}`
	chown nobody `dirname ${pidfile}`
	daemon -cf -p ${pidfile} -u nobody /etc/heartbeat-check
}

load_rc_config $name
run_rc_command "$1"
