#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-postinit
# REQUIRES: cron swaplate

. /etc/rc.subr

do_postinit()
{
	/usr/local/bin/midclt call core.notify_postinit > /dev/null
	/usr/local/bin/midclt call -job initshutdownscript.execute_init_tasks POSTINIT > /dev/null 2>&1
}

name="ix-postinit"
start_cmd='do_postinit'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
