.Dd Feb 02, 2011
.Dt PBI_BROWSER 1
.Os
.Sh NAME
.Nm pbi_browser
.Nd Browse listings of available PBIs from a repository
.Sh SYNOPSIS
.Nm
.Op Fl c Ar category
.Op Fl s Ar search
.Op Fl -listcats
.Op Fl -viewall
.Op Ar repoid
.Sh DESCRIPTION
The utility,
.Nm ,
is used to provide a searchable listing of available PBIs from a particular
repository.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl c Ar category
Display a list of PBIs from the specified category.
.It Fl s Ar search
Search the repository for PBIs with the specified string in the
name, description, or keywords. 
.It Fl -listcats
List the available categories in the PBI repository. 
.It Fl -viewall
List all available PBIs for a specific repository. 
.El
.Sh SEE ALSO
.Xr pbi_addrepo 1 ,
.Xr pbi_deleterepo 1 ,
.Xr pbi_makerepo 1
