.Dd Nov 27, 2010
.Dt PBI_LISTREPO 1
.Os
.Sh NAME
.Nm pbi_listrepo
.Nd Lists information about registered repositories
.Sh SYNOPSIS
.Nm
.Op Fl -down
.Op Fl -mirror Ar url
.Op Fl -up
.Op Ar repoid
.Sh DESCRIPTION
The utility,
.Nm ,
is used provide a listing of PBI repositories in use on the system, as well
as provide option to raise / lower a particular repo's priority. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl -down
Move the targeted repoid down a single number in priority
.It Fl -mirror Ar url
Change the specific repoid's mirror URL
.It Fl -up 
Move the targeted repoid up a single number in priority
.El
.Sh SEE ALSO
.Xr pbi_addrepo 1 ,
.Xr pbi_deleterepo 1 ,
.Xr pbi_makerepo 1
