.Dd Feb 02, 2011
.Dt PBI_METATOOL 1
.Os
.Sh NAME
.Nm pbi_metatool
.Nd Tool for modifying a repo meta file
.Sh SYNOPSIS
.Nm
.Op Ar add
.Op Ar rem 
.Op Ar metafile
.Sh DESCRIPTION
The utility,
.Nm ,
can be used by repository maintainers to add / remove data from their
meta file, which is used by clients for browsing PBIs in a repository via
pbi_browser, or associated GUI tool.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Ar add
Adds a category / application to the target metafile, running 'pbi_metatool add' provides more details on usage. 
.It Ar rem 
Removes a category / application from the target metafile, running 'pbi_metatool remove' provides more details on usage. 
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_browser 1
