.Dd Nov 19, 2010
.Dt PBI_INDEXTOOL 1
.Os
.Sh NAME
.Nm pbi_indextool
.Nd Lists information about PBIs
.Sh SYNOPSIS
.Nm
.Op Ar add
.Op Ar rem 
.Op Ar indexfile
.Sh DESCRIPTION
The utility,
.Nm ,
can be used by repository maintainers to add / remove PBIs from their
INDEX file, which is used by clients for downloading / updating PBIs from that
repository. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Ar add
Adds a PBI to the target indexfile, running 'pbi_indextool add' provides more details on usage. 
.It Ar rem 
Removes a PBI to the target indexfile, running 'pbi_indextool remove' provides more details on usage. 
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_delete 1
