.Dd Mar 21, 2011
.Dt PBI_UPDATE_HASHDIR 1
.Os
.Sh NAME
.Nm pbi_update_hashdir
.Nd Merge a PBIs contents into the hashdir
.Sh SYNOPSIS
.Nm
.Op Ar pbidirectory
.Op Ar deletetrigger
.Sh DESCRIPTION
The 
.Nm ,
command is normally used by the pbid daemon, which manages integrating PBIs
into a hash-dir. This should not need to be run by users. 
.Pp
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_delete 1
