.Dd Apr 15, 2010
.Dt PBI_CREATE 1
.Os
.Sh NAME
.Nm pbi_create
.Nd Package a directory into PBI format
.Sh SYNOPSIS
.Nm
.Op Fl a Ar author
.Op Fl b
.Op Fl c Ar confdir
.Op Fl d Ar portsdir
.Op Fl i Ar icon
.Op Fl n Ar name
.Op Fl o Ar outdir
.Op Fl p Ar port
.Op Fl r Ar version
.Op Fl -sign Ar keyfile
.Op Fl w Ar weburl 
.Op Fl -no-hash
.Op Ar pbidir
.Sh DESCRIPTION
The utility,
.Nm ,
creates a self-contained PBI file from a target directory.
In most cases a small meta-data module will be required 
for desktop compliance.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl a Ar author
Specify the Author for this PBI
.It Fl b
Make a backup of an installed PBI, when using this option specify the 
target PBI name instead of [pbidir]
.It Fl c Ar confdir
Specify the meta-data confdir to use. While not required for building
a PBI, it is highly recommended. Without some configuration settings
in the meta-data, icons and binary entry-points will not be created. 
.It Fl d Ar portsdir
Specify an alternative ports-dir, defaults to /usr/ports
.It Fl i Ar icon
Specify a default icon for this PBI, relative to pbidir/
.It Fl n Ar name
Specify a name for this PBI
.It Fl o Ar outdir
Place the finished .pbi file into the specified directory. Defaults to
$HOME/
.It Fl p Ar port
Use the given port to get PBI name / version from
.It Fl r Ar version 
Specify a version for this PBI
.It Fl u Ar weburl
Specify a website URL for the PBI
.It Fl -no-hash
Disable using the shared-hash dir, which uses hard-links to share files
between applications which are the same. 
.It Fl -sign Ar keyfile
Digitially sign the PBI file with the openssl private key file specified
.Sh NOTES
For details about the module format, please refer to the wiki guide:
http://wiki.pcbsd.org/index.php/PBI_Module_Builder_Guide
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_makeport 1
