#!/bin/sh
#-
# Copyright (c) 2010-2011 iXsystems, Inc., All rights reserved.
# Copyright (c) 2012 Avatar Project. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL Jordan Hubbard OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
#
# This file is heavily derived from both Sam Leffler's Avilia config,
# as well as the BSDRP project's config file.  Neither of these have
# an explicit copyright/license statement, but are implicitly BSDL.
#

# Where cust_pkg() finds packages to install
NANO_PACKAGE_DIR=${NANO_SRC}/${NANO_TOOLS}/Pkg
NANO_DATADIR=${NANO_OBJ}/_.data
NANO_DATASIZE=40960
NANO_INIT_IMG2=0
unset MAKEOBJDIRPREFIX

# Python version needs to be known when we are picking port vs package.  However,
# we've not yet created the make.conf.build file, nor setup things so that the nano
# vars for that are even defined.  To cope, export this globally.  We may be able
# to remove it from make.conf.build, but it doesn't hurt to have it there and
# may help.
export PYTHON_DEFAULT_VERSION=python2.7

# Defeat the python auto versioning goo that contaminates the build slightly
# with the host's python version rather than the version that's inside the
# port tree we're building.  We do this by adding PYTHON_CMD=/bin/true to the
# make package-name invocation.
PKGNAME_HACK=PYTHON_CMD=/bin/true

# this to go into nanobsd.sh
NANO_PORTS=${NANO_PORTS:-/usr/ports}

if is_truenas ; then
	: ${MASTER_SITE_OVERRIDE='http://gitserver/truenas/distfiles/${DIST_SUBDIR}/'}
	export MASTER_SITE_OVERRIDE
fi

NANO_FETCH_PORTS_BG=""

clean_packages()
{
	LOCAL_DIR=${NANO_WORLDDIR}/usr/local
	pprint 2 "Clean and create world directory (${LOCAL_DIR})"
	if [ -d "$LOCAL_DIR" ]; then
		rm -Rf ${LOCAL_DIR} >/dev/null 2>&1
		chflags -R noschg ${LOCAL_DIR}/ || :
		rm -rf ${LOCAL_DIR}
	fi
	for f in bin etc lib libdata libexec sbin share; do
		mkdir -p ${LOCAL_DIR}/$f
	done
	find ${LOCAL_DIR}/var/db/pkg/ -mindepth 1 -maxdepth 1 | xargs rm -Rf
}
customize_cmd clean_packages

# XXX: until the directories are restructured in such a way that this is more
# sane, do not copy over things from the base system into plugins-base, etc,
# otherwise stuff won't work when starting up plugins jails because the bits
# in nanobsd/Files make assumptions in terms of how things are laid out / done
# in the base system, which doesn't work for plugins-jails, et all.
if [ $AVATAR_COMPONENT = "os-base" ]
then
cust_install_machine_files()
{
	echo "cd ${NANO_CFG_BASE}/Files"
	cd ${NANO_CFG_BASE}/Files
	find . -print | grep -Ev '/(CVS|\.git|\.svn)' | cpio -R root:wheel -dumpv ${NANO_WORLDDIR}
}
customize_cmd cust_install_files
customize_cmd cust_install_machine_files 
fi

buildenv()
{
	cd ${NANO_SRC}
	env \
		DESTDIR=${NANO_WORLDDIR} \
		${NANO_PMAKE} \
		buildenv \
		__MAKE_CONF=${NANO_MAKE_CONF_BUILD}
}

# XXX: move to nanobsd.sh once it has a use there.
NANO_MAKEFS="makefs -B big \
	-o bsize=4096,fsize=512,density=8192,optimization=space"
export NANO_MAKEFS

NANO_PACKAGE_ONLY=1

# Ports compiles need to be free of locale tainting.
for v in $(env | egrep '^(LANG|LC).*='); do
	unset ${v%=*}
done

# NOTE: the following code consists of temporary shims inherited from the
# FreeNAS project to get things to work with the predefined src + ports tree
# pulled by do_build.sh to work with an untainted build environment. This works
# on amd64/i386, but not in other cross-architecture scenarios.
#
# The shims will be removed/folded into nanobsd.sh once a more generic solution
# is available for solving some of the problems with bsd.ports.mk related to
# cross-building, package-recursive build issues, etc.

is_release_image()
{
	:
}

if is_release_image
then
	AVATAR_DEBUG_BUILD="
DEBUG_FLAGS=		-g
"
else
	AVATAR_DEBUG_INSTALL="
INSTALL_NODEBUG=	t
"
fi

# NOTE: the following code consists of temporary shims inherited from the
# FreeNAS project to get things to work with the predefined src + ports tree
# pulled by do_build.sh to work with an untainted build environment. This works
# on amd64/i386, but not in other cross-architecture scenarios.
#
# The shims will be removed/folded into nanobsd.sh once a more generic solution
# is available for solving some of the problems with bsd.ports.mk related to
# cross-building, package-recursive build issues, etc.
# XXX: chroot is not cross-architecture safe.
fake_target_host()
{
	local newvers revision branch

	newvers="$NANO_SRC/sys/conf/newvers.sh"
	revision=$(grep -m 1 REVISION= $newvers | cut -f2 -d '"')
	branch=$(grep -m 1 BRANCH= $newvers | cut -f2 -d '"')
	# 1. Invoke a subshell so we don't pollute the build environment with
	#    these variables.
	# 2. Use sane defaults to avoid polluting the build environment with
	#    system specific settings that might have been defined via
	#    /etc/make.conf (LOCALBASE), etc.
	(
	 set -e
	 env
	 export UNAME_m=$NANO_ARCH
	 export UNAME_p=$NANO_ARCH
	 export UNAME_r="$revision-$branch"
	 export UNAME_v="$(uname -v | sed -e "s/$(uname -p)/$UNAME_p/" -e "s/$(uname -r)/$UNAME_r/g")"
	 export OSVERSION=$(awk '/\#define.*__FreeBSD_version/ { print $3 }' "$NANO_SRC/sys/sys/param.h")
	 export PATH=${PBI_BINDIR}:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin
	 "$@"
	)
}

CR()
{
	mount -t devfs none $NANO_WORLDDIR/dev
	fake_target_host \
	    chroot ${NANO_WORLDDIR} /bin/sh -exc "$@"
	umount $NANO_WORLDDIR/dev
}

# install a package from a pre-built binary
do_add_pkg ()
{
	# Need to create ${NANO_OBJ}/ports in this add_pkg_${port} function
	mkdir -p ${NANO_OBJ}/ports/packages
	mkdir -p ${NANO_WORLDDIR}/usr/ports/packages/All
	mount -t nullfs -o noatime ${NANO_OBJ}/ports/packages \
    		${NANO_WORLDDIR}/usr/ports/packages

	CR "cd /usr/ports/packages/All;pkg_add -F $1.tbz"
	set -e
	umount -f ${NANO_WORLDDIR}/usr/ports/packages
	rmdir ${NANO_WORLDDIR}/usr/ports/packages/All
	rmdir ${NANO_WORLDDIR}/usr/ports/packages
	rmdir ${NANO_WORLDDIR}/usr/ports
}

# Build a port (with the side effect of creating a package)
do_add_port ()
{
	local port_repo
	port_repo=$1
	shift
	local port_path
	local fetch_list
	port_path=$1
	fetch_list=${NANO_OBJ}/_.fetch_list
	shift

	# Wait for port finish to fetch
	while grep "^${port_path}" ${fetch_list}; do
		sleep 1
	done;

	# Need to create ${NANO_OBJ}/ports in this add_port_${port} function
	mkdir -p ${NANO_OBJ}/ports/distfiles
	mkdir -p ${NANO_OBJ}/ports/packages
	mkdir -p ${port_repo}/packages
	mkdir -p ${port_repo}/distfiles
	mkdir -p ${NANO_WORLDDIR}/usr/src
	# we always mount NANO_PORTS to /usr/ports for Mk files.
	mkdir -p ${NANO_WORLDDIR}/usr/ports
	mkdir -p ${NANO_WORLDDIR}/usr/ports_dir
	mkdir -p ${NANO_WORLDDIR}/usr/nas_source
	set +e
	# we need a copy of the source tree
      	mount -t nullfs -o noatime ${NANO_SRC} ${NANO_WORLDDIR}/usr/src
	# we need a copy of the ports tree but ONLY for ports/Mk/*.mk
	mount -t nullfs -o noatime ${NANO_PORTS} ${NANO_WORLDDIR}/usr/ports
	# we need a copy of the actual ports tree the port is located in
	mount -t nullfs -o noatime ${port_repo} ${NANO_WORLDDIR}/usr/ports_dir
	mount -t nullfs -o noatime $AVATAR_ROOT/nas_source \
		${NANO_WORLDDIR}/usr/nas_source
	mount -t nullfs -o noatime ${NANO_OBJ}/ports/packages \
    		${NANO_WORLDDIR}/usr/ports/packages
	if [ -n "${DISTCACHE}" ]; then
		if ! [ -d ${DISTCACHE} ]; then
			mkdir -p ${DISTCACHE}
		fi
		mount -t nullfs -o noatime ${DISTCACHE} ${NANO_WORLDDIR}/usr/ports/distfiles
	else
		mount -t nullfs -o noatime ${NANO_OBJ}/ports/distfiles \
	    		${NANO_WORLDDIR}/usr/ports/distfiles
	fi
	mkdir -p ${NANO_WORLDDIR}/usr/workdir
	set -e
	cp /etc/resolv.conf ${NANO_WORLDDIR}/etc/resolv.conf

	# we need to pass on the environment variables for
	# NAS_PORTS_DIRECT (if set) and NAS_PORTS_DIRECT_SYSUTILS_ZFSD (if set)
	# convert the port path from sysutils/zfsd to SYSUTILS_ZFSD
	#
	# so we will look in the environment and build up 'envargs'
	# to set NAS_PORTS_DIRECT/NAS_PORTS_DIRECT_CATAGORY_PORT
	set -x
	local port_path_caps=`echo $port_path|tr 'a-z' 'A-Z' | tr '/' '_'`
	eval local exact_set=\${NAS_PORTS_DIRECT_$port_path_caps}
	local envargs;
	if [ ! -z "$exact_set" ] ; then
		envargs="NAS_PORTS_DIRECT_${port_path_caps}=1"
	fi
	if [ ! -z "$NAS_PORTS_DIRECT" ] ; then
		envargs="$envargs NAS_PORTS_DIRECT=1"
	fi

	# Improvement: Don't know why package-recursive don't works here
	CR "env \
	    TARGET=${NANO_ARCH} \
	    TARGET_ARCH=${NANO_ARCH} \
	    $envargs \
	    make \
	    __MAKE_CONF=${NANO_MAKE_CONF_BUILD} \
	    SRC_BASE=/usr/src \
	    WRKDIRPREFIX=/usr/workdir -C /usr/ports_dir/$port_path \
	    clean package BATCH=yes -DUSE_PACKAGE_DEPENDS \
	    $* clean -DFORCE_PACKAGE -DFORCE_PKG_REGISTER"
	rm ${NANO_WORLDDIR}/etc/resolv.conf
	rm -rf ${NANO_WORLDDIR}/usr/obj
	rm -rf ${NANO_WORLDDIR}/usr/workdir
	umount -f ${NANO_WORLDDIR}/usr/nas_source
	umount -f ${NANO_WORLDDIR}/usr/ports/distfiles
	umount -f ${NANO_WORLDDIR}/usr/ports/packages
	umount -f ${NANO_WORLDDIR}/usr/ports_dir
	umount -f ${NANO_WORLDDIR}/usr/ports
	umount -f ${NANO_WORLDDIR}/usr/src
}

# Need to check if this function works with cross-compiling architecture!!!!
# Recursive complex function: Generate one function for each ports
add_port_generic()
{
    local _add_pkg PKG_NAME
    local repo_path=$1
    shift
    local port_path=$1
    local port=`echo $1 | sed -e 's/\//_/'`
    shift
    # Check if package already exist
    # Need to:
    # 1. check ARCH of this package!
    # 2. Add a trap
    cd ${repo_path}/${port_path}
    # __MAKE_CONF -> ${NANO_MAKE_CONF_BUILD} -- can't plug this in because of a
    # sourcing chicken and egg problem.
    set +e
    #PKG_NAME=`make ${PKGNAME_HACK} PORTSDIR=${repo_path} __MAKE_CONF=${NANO_OBJ}/make.conf.install OPTIONSFILE=/nonexistent package-name $*`
    # XXX: use NANO_PORTS here for ${NANO_PORTS}/Mk/*.mk
    PKG_NAME=`make ${PKGNAME_HACK} PORTSDIR=${NANO_PORTS} __MAKE_CONF=${NANO_OBJ}/make.conf.install OPTIONSFILE=/nonexistent package-name $*`
    if [ $? -ne 0 ]; then
        echo "failed to determine the package name for $port_path"
        exit 1
    fi
    set -e

    _add_pkg=false
    if ! [ -d ${NANO_OBJ}/ports/packages ]; then
        mkdir -p ${NANO_OBJ}/ports/packages
    fi
    if ! [ -d ${NANO_OBJ}/ports/distfiles ]; then
        mkdir -p ${NANO_OBJ}/ports/distfiles
    fi
    if [ -n "${DISTCACHE}" ]; then
        if ! [ -d ${DISTCACHE} ]; then
            mkdir -p ${DISTCACHE}
        fi
        mount -t nullfs -o noatime ${DISTCACHE} ${NANO_OBJ}/ports/distfiles
    fi
    if $do_world && $do_clean; then
        # HACK: make do_build.sh -ff work properly instead of having
        # do_add_pkg fall flat on its face when it tries to add the
        # missing package.
        if [ -f ${NANO_OBJ}/ports/packages/All/${PKG_NAME}.tbz ]; then
            _add_pkg=true
        else
            :
        fi
    elif [ -f ${NANO_OBJ}/ports/packages/All/${PKG_NAME}.tbz ]; then
	# Pkg file found: Generate add_pkg_NAME function
        _add_pkg=true
    fi

    if $_add_pkg; then
	eval "
	    add_pkg_${port} () {
	        do_add_pkg ${PKG_NAME}
	    }
            customize_cmd add_pkg_${port}
            "
    else
	# We don't support background fetch for other ports trees
	# than the FreeBSD one for now because I don't have time to
	# abstract background fetches for multiple ports repos right now.
	if [ "$repo_path" = "${NANO_PORTS}" ] ; then
	    NANO_FETCH_PORTS_BG="${NANO_FETCH_PORTS_BG} ${port_path}"
	fi

	echo "Package is not yet built: $port"
        eval "
            add_port_${port} () {
	        do_add_port ${repo_path} ${port_path} $*
	    }
	    customize_cmd add_port_${port}
	"
	NANO_PACKAGE_ONLY=0
    fi
    if [ -n "${DISTCACHE}" ]; then
        umount -f ${NANO_OBJ}/ports/distfiles
    fi
}

do_fetch (){

	local path=$1

	(
	cd ${NANO_PORTS}/${path}
	env ARCH=${NANO_ARCH} SRC_DIR=${NANO_SRC} PORTSDIR=${NANO_PORTS} DISTDIR=${NANO_OBJ}/ports/distfiles make -I ${NANO_PORTS}/Mk fetch-recursive || :
	)

}

do_fetch_background () {

	local fetch_list=$1
	set +e -- $NANO_FETCH_PORTS_BG
	i=1
	num_steps=$#
	while [ $i -le $num_steps ]
	do
		do_fetch $1
		newlist=$(cat ${fetch_list} | grep -v $1)
		echo "${newlist}" > ${fetch_list}
	        shift
	        : $(( i += 1 ))
	done
	rm ${fetch_list}
	set -e
}

fetch_background ()
{
	local fetch_list
	pprint 2 "fetch ports in background"
	fetch_list=${NANO_OBJ}/_.fetch_list
	echo ${NANO_FETCH_PORTS_BG} | tr -s " " "\n" > ${fetch_list}
	do_fetch_background ${fetch_list} &
}
customize_cmd fetch_background

# Add a port from the basic NANO_PORTS directory
add_port ()
{

   add_port_generic ${NANO_PORTS} $*
}

# Add a port from a specific repo!
add_port_with_repo ()
{
    local port_repo=$1
    shift
    add_port_generic $port_repo $*
}

# Fill in stub functions for non-base OS images.
if [ $AVATAR_COMPONENT != "os-base" ]
then
do_image=false

build_kernel()
{
	:
}

install_kernel()
{
	:
}

do_image()
{
	:
}

setup_nanobsd()
{
	:
}

setup_nanobsd_etc()
{
	:
}
fi

generate_avatar_conf()
{
	cat > ${NANO_WORLDDIR}/etc/avatar.conf <<EOF
#!/bin/sh
#
# A simple, sourceable script that can be used to derive
# avatar project specific details, such as name, version, etc.
# This should be sourced by middleware.
#
# Use easy-to parse lines for this script, like:
#
# {{{
# FOO="bar"
#
# export FOO
# }}}
# Not something like...
#
# {{{
# export FOO="bar"
# }}}
#
# or...
#
# {{{
# for var in FOO; do
#      eval \${var}="bar"
# done
# }}}
#
# This file will be parsed sometime in the future without having
# to invoke /bin/sh.

# The name of the project, e.g. FreeNAS.
AVATAR_PROJECT="$NANO_LABEL"

# The website for the avatar project.
AVATAR_PROJECT_SITE="$AVATAR_PROJECT_SITE"

# The support site for the avatar project.
AVATAR_SUPPORT_SITE="$AVATAR_SUPPORT_SITE"

# The version of software, e.g. 8.0.3-RELEASE, 8.2-ALPHA, etc.
AVATAR_VERSION="$VERSION"

# The build number, e.g. r9310, <git-sha256-hash>, etc.
AVATAR_BUILD_NUMBER="$SVNREVISION"

# The machine[:processor] for the image with a humanized name,
# e.g. 'x64', 'mips:mipsel', etc.
AVATAR_ARCH="$NANO_ARCH_HUMANIZED"

# The avatar project component being built
AVATAR_COMPONENT="$AVATAR_COMPONENT"

export AVATAR_ARCH AVATAR_COMPONENT
export AVATAR_PROJECT AVATAR_VERSION AVATAR_BUILD_NUMBER
export AVATAR_PROJECT_SITE AVATAR_SUPPORT_SITE
EOF

}
customize_cmd generate_avatar_conf

__a=`mount | grep ${NANO_OBJ}/ | awk '{print length($3), $3;}' | sort -rn | awk '{$1=""; print;}'`
if [ -n "$__a" ]; then
	echo "unmounting $__a"
	umount $__a
fi

NANO_BOOTLOADER="boot/boot0"

make_conf_install ( ) (
        pprint 2 "Construct install make.conf ($NANO_MAKE_CONF_INSTALL)"

        echo "${CONF_WORLD}" > ${NANO_MAKE_CONF_INSTALL}
        echo "${CONF_INSTALL}" >> ${NANO_MAKE_CONF_INSTALL}

	# hacky hack
	mkdir -p ${NANO_WORLDDIR}/usr/pbi
	chown root:wheel ${NANO_WORLDDIR}/usr/pbi
)

