#!/bin/sh
#-
# Copyright (c) 2010-2011 iXsystems, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL iXsystems, Inc. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# This file is heavily derived from both Sam Leffler's Avilia config,
# as well as the BSDRP project's config file.  Neither of these have
# an explicit copyright/license statement, but are implicitly BSDL.
#

#
# FreeNAS specific bits of the common stuff.
#

# Override the defaults in nanobsd.sh from a common script.
. "$AVATAR_ROOT/build/nano_env"
# Helpful functions.
. "$AVATAR_ROOT/build/functions.sh"

if is_truenas ; then
	. ${TRUENAS_COMPONENTS_ROOT}/nanobsd/os-base.truenas
fi

. "$NANO_CFG_BASE/os-base-functions.sh"

FlashDevice generic 2g

# Pull in common definitions.
. ${NANO_CFG_BASE}/common

customize_cmd build_debug_kernel
customize_cmd install_debug_kernel

customize_cmd install_ports

if [ "${NANO_PACKAGE_ONLY}" -eq 1 ]; then
 	CONF_INSTALL="${CONF_INSTALL}
${PKG_ONLY_MAKE_CONF}
"
	echo "Automatically building a thin image with packages"
else
	echo "Automatically building a * * F A T * * image so we can build ports"
fi

VARS="MASTER_SITE_BACKUP MASTER_SITE_OVERRIDE PACKAGEROOT PACKAGESITE"

for var in $VARS; do
	val=$(eval echo "\$$var")
	if [ -n "$val" ]; then
		CONF_INSTALL="${CONF_INSTALL}
$var=$val"
	fi
done

customize_cmd hack_nsswitch_conf

customize_cmd save_build

customize_cmd add_gui

customize_cmd_truenas add_licensor

if ! is_truenas ; then
	customize_cmd arch_specific_ko
fi

customize_cmd add_warden_hooks

customize_cmd move_data

customize_cmd add_data_to_fstab

customize_cmd_truenas afpd_conf_symlink

customize_cmd select_httpd

customize_cmd remove_patch_divots

customize_cmd configure_mnt_md

customize_cmd shrink_md_fbsize

if [ "${DEBUG}" = 1 ]; then
	customize_cmd unmute_console_logging
fi

customize_cmd remove_gcc47

customize_cmd remove_packages

customize_cmd remove_var_cache_pkg

customize_cmd remove_var_db_pkg

customize_cmd fix_easy_install_pth

customize_cmd create_var_home_symlink

customize_cmd add_netcli_shell

late_customize_cmd freenas_custom
