#!/bin/sh
#-
# Copyright (c) 2010-2012 iXsystems, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL iXsystems, Inc. OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

# Override the defaults in nanobsd.sh from a common script.
. "$AVATAR_ROOT/build/nano_env"
# Helpful functions.
. "$AVATAR_ROOT/build/functions.sh"

CONF_BUILD="
WITHOUT_ATM=		true	# do not build ATM related programs and libraries
WITHOUT_AUTHPF=		true	# do not build and install authpf (setuid/gid)
WITHOUT_BOOT=		true	# do not build boot blocks and loader
WITHOUT_BLUETOOTH=	true	# do not build Bluetooth related stuff
WITHOUT_FORTRAN=	true	# do not build g77 and related libraries
WITHOUT_GAMES=		true	# do not build games
WITHOUT_GPIB=		true	# do not build GPIB support
WITHOUT_I4B=		true	# do not build isdn4bsd package
WITHOUT_IPFILTER=	true	# do not build IP Filter package
WITHOUT_MODULES=	true	# do not build modules with the kernel
WITHOUT_PF=		true	# do not build PF firewall package
WITHOUT_PROFILE=	true	# Avoid compiling profiled libraries
WITHOUT_USB=		true	# do not build usbd(8) and related programs
WITHOUT_VINUM=		true	# do not build Vinum utilities

# BIND OPTIONS
WITHOUT_BIND=			true	# Do not build any part of BIND
WITHOUT_BIND_DNSSEC=		true	# Do not build dnssec-keygen, dnssec-signzone
WITHOUT_BIND_ETC=		true	# Do not install files to /etc/namedb
WITHOUT_BIND_LIBS_LWRES=	true	# Do not install the lwres library
WITHOUT_BIND_MTREE=		true	# Do not run mtree to create chroot directories
WITHOUT_BIND_NAMED=		true	# Do not build named, rndc, lwresd, etc.

# We run 2.7 for now
PYTHON_DEFAULT_VERSION=python2.7

# For devel/apr
WITH_BDB_VER=46
"

CONF_INSTALL="$CONF_BUILD"

# Pull in common definitions.
. ${NANO_CFG_BASE}/common

# XXX: libtool is needed for i386. Need to determine why because this isn't
# required when compiling the packages in the base system.
add_port devel/libtool
add_port converters/libiconv
#+editors/nano || converters/iconv
add_port lang/perl5.14
#-editors/nano || converters/iconv
add_port converters/iconv
#+databases/tdb || ...
add_port devel/pkg-config
#-databases/tdb || ...
add_port devel/gettext
add_port databases/db46
add_port lang/python27
add_port dns/py-dnspython
add_port databases/tdb
add_port devel/pcre
add_port databases/sqlite3
add_port databases/py-sqlite3
add_port databases/py-bsddb3
add_port devel/py-distribute
add_port devel/py-asn1
add_port devel/py-asn1-modules
add_port www/py-flup
add_port textproc/libxml2
add_port textproc/py-libxml2
add_port textproc/expat2
add_port devel/libltdl
add_port devel/py-ipaddr
add_port converters/base64
add_port devel/glib20
add_port devel/gamin
add_port devel/gio-fam-backend
#+add_port devel/dbus*
add_port sysutils/gnome_subr
#-add_port devel/dbus*
add_port devel/dbus OPTIONS_FILE_UNSET+=X11
add_port devel/dbus-glib OPTIONS_FILE_UNSET+=X11
add_port devel/libdaemon
add_port databases/gdbm
add_port textproc/py-xml
#+add_port ftp/wget
add_port dns/libidn
#-add_port ftp/wget
add_port ftp/wget
add_port devel/py-lockfile
add_port devel/py-daemon

setup_nanobsd_etc()
{
	(
	cd $NANO_WORLDDIR

	# Create an empty fstab
	: > etc/fstab

	# XXX: put this in dist/
	cat > etc/rc.conf <<EOF
sendmail_enable="NONE"
syslogd_flags="-ss"
pbid_enable="YES"
EOF

	cat > etc/pw.conf <<EOF
minuid 40000
maxuid 49999
mingid 40000
maxgid 49999
EOF

	)

}

add_pbi_manager()
{
	local pm dst
	pm=${AVATAR_ROOT}/src/pcbsd/pbi-manager
	dst=${NANO_WORLDDIR}/usr/local

	pprint 2 "Adding pbi-manager"

	mkdir -p ${dst}/sbin >/dev/null 2>/dev/null
	cp ${pm}/pbi-manager ${dst}/sbin/pbi_create
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_add
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_addrepo
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_browser
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_autobuild
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_delete
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_deleterepo
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_icon
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_info
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_indextool
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_listrepo
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_makepatch
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_makeport
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_makerepo
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_metatool
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_patch
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_update
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi_update_hashdir
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbid
	ln -f ${dst}/sbin/pbi_create ${dst}/sbin/pbi-crashhandler
	rm -f ${dst}/pbi-manager
}
customize_cmd add_pbi_manager

add_pbi_wrapper()
{
	local _pm
	_pm="${NANO_WORLDDIR}/usr/pbi/.pbiwrapper"

	pprint 2 "Adding PBI wrapper"

	mkdir -p "${PBI_BUILDDIR}"
	if [ ! -s "${PBI_BUILDDIR}/.pbiwrapper" ]
	then
		cp "${_pm}" "${PBI_BUILDDIR}/.pbiwrapper"
	fi
}
customize_cmd add_pbi_wrapper

last_orders()
{
	local pj_dest_basename pj_src_basename
	local pj_log pj_name pj_pbi pj_version pj_world_dir

	set -u

	pj_name="plugins_jail"
	pj_log="$MAKEOBJDIRPREFIX/_.plugins_jail"
	pj_world_dir="$MAKEOBJDIRPREFIX/_.w"

	pprint 2 "Creating plugins jail PBI"
	pprint 3 "log: $pj_log"

	pj_version=`echo $VERSION | sed -E -e 's/-[^-]+//g'`

	pj_src_basename="$pj_name-$pj_version-$NANO_ARCH.pbi"
	pj_dest_basename="$NANO_IMGNAME.Plugins_Jail"
	pj_pbi=$pj_dest_basename.pbi

	(
	set -x

	fake_target_host \
		pbi_create \
		-a $NANO_LABEL \
		-n $pj_name \
		-o "$NANO_DISKIMGDIR" \
		-r $pj_version \
		-w $AVATAR_PROJECT_SITE \
		$pj_world_dir

		cd $NANO_DISKIMGDIR/
		mv $pj_src_basename $pj_pbi
		mv $pj_src_basename.sha256 $pj_pbi.sha256

	) > "$pj_log" 2>&1

}
