# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-01 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_remove_volume_vol_fstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_enclosure_slot',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Enclosure Slot'),
        ),
    ]
