# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-21 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_resilver.py'),
    ]

    operations = [
        migrations.AlterField(
            model_name='Scrub',
            name='scrub_threshold',
            field=models.PositiveSmallIntegerField(verbose_name=_("Threshold days"), help_text=_("Determine how many days shall be between scrubs"), default=7),
        ),
    ]
