# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import os


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_quota_value'),
    ]

    def forward_pre(apps, schema_editor):
        # Check for sentinel file that signifies storage_disk was added manually
        if os.path.isfile("/data/.sed"):
            # save the contents of storage_disk off manually.  This will be
            # re-added by ix-sed after the system reboots.
            ret = os.popen('sqlite3 /data/freenas-v1.db'
                           ' "SELECT disk_name, disk_passwd FROM storage_disk" ').read()
            fh = open("/data/seddata", "w")
            fh.write(ret)
            fh.close()
            os.remove("/data/.sed")

    def reverse_pre(apps, schema_editor):
        pass

    operations = [
        migrations.RunPython(forward_pre, reverse_pre),
        migrations.AddField(
            model_name='disk',
            name='disk_passwd',
            field=models.CharField(blank=True, max_length=120, verbose_name='Password for SED'),
        ),
    ]
