# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-27 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_quota_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_passwd',
            field=models.CharField(blank=True, max_length=120, verbose_name='Password for SED'),
        ),
    ]
