# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-14 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_replication_restrict_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='replication',
            name='repl_netcat_active_side_listen_address',
            field=models.CharField(default=None, max_length=120, null=True, verbose_name='Netcat Active Side Listen Address'),
        ),
        migrations.AddField(
            model_name='replication',
            name='repl_netcat_passive_side_connect_address',
            field=models.CharField(default=None, max_length=120, null=True, verbose_name='Netcat Passive Side Connect Address'),
        ),
    ]
