# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-24 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0016_replication_netcat_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='replication',
            name='repl_logging_level',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default=None, max_length=120, null=True, verbose_name='Logging Level'),
        ),
    ]
