# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-13 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_replication_logging_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='disk_model',
            field=models.CharField(default=None, editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_rotationrate',
            field=models.IntegerField(default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='disk',
            name='disk_type',
            field=models.CharField(choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('UNKNOWN', 'UNKNOWN')], default='UNKNOWN', editable=False, max_length=20),
        ),
    ]
