# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-03-09 22:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models

from freenasUI.common.system import get_sw_name


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0022_auto_20190809_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='replication',
            name='repl_readonly',
            field=models.CharField(choices=[('SET', 'Set to read-only'), ('REQUIRE', 'Require to be read-only'), ('IGNORE', 'Ignore read-only value')],
                                   default='SET' if get_sw_name().lower() == 'freenas' else 'REQUIRE',
                                   max_length=120, verbose_name='Destination dataset read-only'),
        ),
    ]
