# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-18 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0023_auto_20200309_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replication',
            name='repl_dedup',
        ),
    ]
