#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: datastore

name="datastore"
start_cmd="datastore_start"
stop_cmd="datastore_stop"
status_cmd="datastore_status"
libdir="/usr/local/lib/datastore"

. /etc/rc.freenas

check_driver()
{
    if [ ! -d ${libdir}/drivers/${datastore_driver} ]; then
	warn "Could not find specified driver"
	return 1
    fi

    driver_ctl="${libdir}/drivers/${datastore_driver}/control"
}

datastore_start()
{
   check_driver
   ${driver_ctl} ${datastore_dbdir} start
}

datastore_stop()
{
    check_driver
    ${driver_ctl} ${datastore_dbdir} stop
}

datastore_status()
{
    check_driver
    ${driver_ctl} ${datastore_dbdir} status
}

datastore_init()
{
    check_driver
    ${driver_ctl} ${datastore_dbdir} init
}

load_rc_config $name
run_rc_command $*
