# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directoryservice', '0004_idmap_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='idmap_ad',
            name='idmap_ad_unix_nss_info',
            field=models.BooleanField(default=False, help_text='If set to yes winbind will retrieve the login shell and home directory from the LDAP attributes. If set to no the or the AD LDAP entry lacks the SFU attributes the options template shell and template homedir are used.', verbose_name='UNIX NSS Info'),
        ),
        migrations.AddField(
            model_name='idmap_ad',
            name='idmap_ad_unix_primary_group',
            field=models.BooleanField(default=False, help_text='Defines whether the user\'s primary group is fetched from the SFU attributes or the AD primary group. If set to yes the primary group membership is fetched from the LDAP attributes (gidNumber). If set to no the primary group membership is calculated via the "primaryGroupID" LDAP attribute.', verbose_name='UNIX Primary Group'),
        ),
    ]
