# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-14 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('directoryservice', '0011_add_new_idmap_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ActiveDirectory',
            name='ad_unix_extensions',
        ),
    ]
