#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: dispatcher
# REQUIRE: datastore
# BEFORE: FILESYSTEMS

. /etc/rc.subr

name="dispatcher"
pidfile="/var/run/dispatcher.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"
start_postcmd="poststart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/dispatcherd ${rc_flags}"
}

poststart()
{
    # ensure that dispatcher is up and accepting connections.
    /usr/local/sbin/dispatcherctl wait-server --timeout 5
}

load_rc_config $name
run_rc_command $*