#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: dispatcher
# REQUIRE: datastore
# BEFORE: FILESYSTEMS

. /etc/rc.subr

name="dispatcher"
pidfile="/var/run/dispatcher.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"
start_postcmd="poststart"

prestart()
{
    rc_flags="-P ${pidfile} -r /usr/local/sbin/dispatcherd ${rc_flags}"
}

poststart()
{
    # ensure that dispatcher is up and accepting connections.
    if ! /usr/local/sbin/dispatcherctl wait-server --timeout 5; then
        echo "ERROR:"
        echo "dispatcher failed to start"
        exit 1
    fi
}

load_rc_config $name
run_rc_command $*