"""Fix migrations state

Revision ID: 273e1e000675
Revises: df8ce67e4828
Create Date: 2020-07-22 12:11:42.611037+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273e1e000675'
down_revision = 'df8ce67e4828'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.alter_column('adv_kdump_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_advanced', schema=None) as batch_op:
        batch_op.alter_column('adv_kdump_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
