"""ftp_timeout_notransfer

Revision ID: 99ddc485eac2
Revises: fee786dfe121
Create Date: 2021-12-10 13:36:47.357888+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '99ddc485eac2'
down_revision = 'fee786dfe121'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ftp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_timeout_notransfer', sa.Integer(), nullable=True))

    op.execute(text("UPDATE services_ftp SET ftp_timeout_notransfer = 300"))

    with op.batch_alter_table('services_ftp', schema=None) as batch_op:
        batch_op.alter_column('ftp_timeout_notransfer', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ftp', schema=None) as batch_op:
        batch_op.drop_column('ftp_timeout_notransfer')

    # ### end Alembic commands ###
