"""API key allowlist

Revision ID: 410b83305c45
Revises: 3a3a37c1f48c
Create Date: 2021-06-08 18:23:04.487592+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '410b83305c45'
down_revision = '3a3a37c1f48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_api_key', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allowlist', sa.TEXT(), nullable=True))

    op.execute(text("UPDATE account_api_key SET allowlist = '[]'"))

    with op.batch_alter_table('account_api_key', schema=None) as batch_op:
        batch_op.alter_column('allowlist', existing_type=sa.TEXT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_api_key', schema=None) as batch_op:
        batch_op.drop_column('allowlist')

    # ### end Alembic commands ###
