"""system_kmip.ssl_version is not null

Revision ID: a3ee46e3860e
Revises: 8b6d0edc6a38
Create Date: 2022-05-31 11:50:45.010927+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3ee46e3860e'
down_revision = '8b6d0edc6a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_kmip', schema=None) as batch_op:
        batch_op.alter_column('ssl_version',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("'PROTOCOL_TLSv1_2'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_kmip', schema=None) as batch_op:
        batch_op.alter_column('ssl_version',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("'PROTOCOL_TLSv1_2'"))

    # ### end Alembic commands ###
