 dependencies ={

   layers:  [
       {
       name: "freenasdojo.js",
       dependencies: [
           "dojo.data.ItemFileReadStore",
           "dojo.dnd.Moveable",
           "dojo.NodeList-traverse",
           "dojo.NodeList-manipulate",
           "dojo.fx",
           "dojo.io.iframe",
           "dojo._base.xhr",
           "dojo.rpc.JsonService",
           "dojo.rpc.RpcService",
           "dojo.selector.acme",
           "dojox.fx._base",
           "dojox.fx._core",
           "dojox.fx.scroll",
           "dojox.validate",
           "dojox.validate._base",
           "dojox.grid.DataGrid",
           "dojox.data.JsonRestStore",
           "dojox.data.FileStore",
           "dojox.grid.EnhancedGrid",
           "dojox.grid.enhanced.plugins.DnD",
           "dojox.grid.enhanced.plugins.Filter",
           "dojox.grid.enhanced.plugins.IndirectSelection",
           "dojox.grid.enhanced.plugins.Menu",
           "dojox.grid.enhanced.plugins.NestedSorting",
           "dojox.grid.enhanced.plugins.Pagination",
           "dojox.grid.TreeGrid",
           "dojox.validate.regexp",
           "dojox.timing",
           "dojox.form.CheckedMultiSelect",
           "dojox.form.FileInput",
           "dojox.form.BusyButton",
           "dojox.layout.ExpandoPane",
           "dojox.string.sprintf",
           "dojox.uuid._base",
           "dojox.uuid.generateRandomUuid",
           "dijit.Tree",
           "dijit.layout.BorderContainer",
           "dijit.layout.ContentPane",
           "dijit.layout.TabContainer",
           "dijit.ProgressBar",
           "dijit.MenuBar",
           "dijit.MenuBarItem",
           "dijit.Calendar",
           "dijit.Dialog",
           "dijit.form.Form",
           "dijit.form.Button",
           "dijit.form.DateTextBox",
           "dijit.form.DropDownButton",
           "dijit.form.MultiSelect",
           "dijit.form.Select",
           "dijit.form.ValidationTextBox",
           "dijit.form.NumberTextBox",
           "dijit.form.Textarea",
           "dijit.form.TimeTextBox",
           "dijit.form.ComboBox",
           "dijit.form.FilteringSelect",
           "dijit.form.NumberTextBox",
           "dijit.form.HorizontalSlider",
           "dijit.form.HorizontalRule",
           "dijit.form.HorizontalRuleLabels",
       ]
       }
   ],

   prefixes: [
       [ "dijit", "../dijit" ],
       [ "dojox", "../dojox" ],
   ]

 };
