#!/bin/sh

. /etc/rc.freenas

cifs_file="/tmp/.cifs_AD"
service=/usr/sbin/service
python=/usr/local/bin/python
notifier=/usr/local/www/freenasUI/middleware/notifier.py

adctl_cmd()
{
	local args="$*"

	if [ -n "${args}" ]
	then
		logger -t ActiveDirectory "${args}"
		${args}
		return $?
	fi

	return 0
}

cifs_enabled()
{
	srv_enabled cifs && return 0
	return 1
}

ad_enabled()
{
	dirsrv_enabled activedirectory && return 0
	return 1
}

cifs_start()
{
	adctl_cmd ${python} ${notifier} start cifs
	return $?
}

cifs_stop()
{
	adctl_cmd ${python} ${notifier} stop cifs
	return $?
}

cifs_restart()
{
	adctl_cmd ${python} ${notifier} stop cifs
	adctl_cmd ${python} ${notifier} start cifs
	return $?
}

adctl_start()
{
	local cifs_started=0	
	local ad_started=0

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	else
		srv_set cifs 1
	fi

	if ad_enabled
	then
		ad_started=1
	else		
		srv_set directoryservice 1
	fi

	echo ${cifs_started} > "${cifs_file}"

	adctl_cmd ${service} ix-kerberos quietstart

	adctl_cmd ${service} ix-nsswitch quietstart
	adctl_cmd ${service} ix-pam quietstart

	adctl_cmd ${service} ix-kinit quietstart
	if ! adctl_cmd ${service} ix-kinit status
	then
		srv_set directoryservice 0
		return 1
	fi

	adctl_cmd ${service} ix-samba quietstart
	cifs_start

	if ! adctl_cmd ${service} ix-activedirectory quietstart
	then
		srv_set directoryservice 0
		return 1
	fi
	if ! adctl_cmd ${service} ix-activedirectory status
	then
		srv_set directoryservice 0
		return 1
	fi

	cifs_restart

	adctl_cmd "${service} ix-cache quietstart &"

	return 0
}

adctl_stop()
{
	local cifs_started=1
	local prev_cifs_started=0
	if [ -s "${cifs_file}" ]
	then
		prev_cifs_started="$(cat "${cifs_file}")"
	fi

	if ! ad_enabled
	then
		srv_set directoryservice 1
	fi

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	fi

	adctl_cmd ${service} ix-kerberos quietstop
	adctl_cmd ${service} ix-nsswitch quietstop
	adctl_cmd ${service} ix-pam quietstop
	adctl_cmd ${service} ix-kinit forcestop
	adctl_cmd ${service} ix-activedirectory forcestop
	adctl_cmd "${service} ix-cache quietstop &"

	if [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "0" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set cifs 0
		srv_set directoryservice 0
		adctl_cmd ${service} ix-samba start

	elif [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "1" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set cifs 0
		srv_set directoryservice 0
		adctl_cmd ${service} ix-samba start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "0" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set directoryservice 0
		srv_set cifs 1
		adctl_cmd ${service} ix-samba start
		cifs_start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "1" ]		
	then
		adctl_cmd ${service} samba forcestop
		srv_set directoryservice 0
		srv_set cifs 1
		adctl_cmd ${service} ix-samba start
		cifs_start
	fi

	srv_set directoryservice 0
	return 0
}

adctl_status()
{
	adctl_cmd ${service} ix-activedirectory status
}

name="adctl"
start_cmd='adctl_start'
status_cmd='adctl_status'
stop_cmd='adctl_stop'
extra_commands='status'

load_rc_config $name
run_rc_command "$1"
