#!/usr/bin/python3

user = "root"
password = "Delta@NoVip88"
netmask = "172.25.5.128"
gateway = "172.25.5.129"
vip = "172.25.5.132"
vm_name = None
hostname = "testAUTOGENERATED"
domain = "tn.ixsystems.com"
api_url = 'http://172.25.5.5/api/v2.0'
interface = "eth0"
badNtpServer = "10.20.20.122"
localHome = "/root"
keyPath = "/root/.ssh/test_id_rsa"
pool_name = "tank"
ha_pool_name = "ha"
ha = True
ha_license = ''
update = False
artifacts = "/root/freenas/freenas/tests/artifacts/"
isns_ip = "10.234.24.50"
extended_tests = False
sshKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC test@reference"
