#!/usr/bin/env expect

set vm [lindex $argv 0];
set logfilepath [lindex $argv 1];
log_file -noappend "$logfilepath"
set timeout 1800
set PID [spawn vm console "$vm"]
send_user "Spawned PID: $PID \n"

# ┌───────────FreeNAS 11.3-MASTER-201810170704 Console Setup──────────────┐
# │ ┌───────────────────────────────────────────────────────────────────┐ │
# │ │                        1  Install/Upgrade                         │ │
# │ │                        2  Shell                                   │ │
# │ │                        3  Reboot System                           │ │
# │ │                        4  Shutdown System                         │ │
# │ │                                                                   │ │
# │ │                                                                   │ │
# │ └───────────────────────────────────────────────────────────────────┘ │
# ├───────────────────────────────────────────────────────────────────────┤
# │                     <  OK  >           <Cancel>                       │
# └───────────────────────────────────────────────────────────────────────┘

expect {
  "Console Setup" {
    sleep .5
    send "1"
    send "\r"
  }
}

# ┌────────────────Choose destination media──────────────────┐
# │ Select one or more drives where FreeNAS should be        │
# │ installed (use arrow keys to navigate to the drive(s)    │
# │ for installation; select a drive with the spacebar).     │
# │ ┌──────────────────────────────────────────────────────┐ │
# │ │            [*] vtbd0  (null) -- 20.0 GiB             │ │
# │ │            [ ] vtbd1  (null) -- 50.0 GiB             │ │
# │ │            [ ] vtbd2  (null) -- 50.0 GiB             │ │
# │ └──────────────────────────────────────────────────────┘ │
# ├──────────────────────────────────────────────────────────┤
# │               <  OK  >        <Cancel>                   │
# └──────────────────────────────────────────────────────────┘

expect {
  "Choose destination media" {
    sleep .5
    send \040
    send "\r"
  }
}

# ┌─────────────────────────FreeNAS installation───────────────────────────┐
# │ WARNING:                                                               │
# │ - This will erase ALL paritions and data on ada0.                      │
# │ - You can't use ada0 for sharing data.                                 │
# │                                                                        │
# │ NOTE:                                                                  │
# │ - Installing on flash media is preferred to install on a               │
# │   hard drive                                                           │
# │                                                                        │
# │   Proceed with the installation?                                       │
# ├────────────────────────────────────────────────────────────────────────┤
# │                       < Yes >            < No  >                       │
# └────────────────────────────────────────────────────────────────────────┘

expect {
  "FreeNAS installation" {
    sleep .5
    send "Y"
    send "\r"
  }
}

# ┌────────────────────────────────────────────────┐
# │ Enter your root password; cancel for no root   │
# │ password                                       │
# │ ┌────────────────────────────────────────────┐ │
# │ │Password:          *******                  │ │
# | |Confirm Password:  *******                  │ │
# │ └────────────────────────────────────────────┘ │
# ├────────────────────────────────────────────────┤
# │           <  OK  >      <Cancel>               │
# └────────────────────────────────────────────────┘

expect {
  "Enter your root password" {
    sleep .5
    send "testing"
    # Tab to next field
    send \011
    send "testing"
    # Tab to submit/OK button
    send \011
    # Submit/confirm password dialog
    send "O"
    send "\r"
  }
}

# ┌──────────────────────────FreeNAS Boot Mode─────────────────────────────┐
# │ FreeNAS can be booted in either BIOS or UEFI mode.                     │
# │                                                                        │
# | BIOS mode is recommended for legacy and enterprise hardware,           │
# | whereas UEFI may be required for newer consumer motherboards.          │
# ├────────────────────────────────────────────────────────────────────────┤
# │               <Boot via UEFI>        <Boot via BIOS>                   │
# └────────────────────────────────────────────────────────────────────────┘

expect {
  "FreeNAS Boot Mode" {
    sleep .5
    send "B"
  }
}

# ┌────────────────────────────────────────────────────────────────────────┐
# │ The FreeNAS installation on vtbd0 succeeded!                           |
# │                                                                        │
# ├────────────────────────────────────────────────────────────────────────┤
# │                               <  OK  >                                 │
# └────────────────────────────────────────────────────────────────────────┘

# Or

# ┌────────────────────────────────────────────────────────────────────────┐
# │ The FreeNAS installation on vtbd0 failed.                              |
# │                                                                        │
# ├────────────────────────────────────────────────────────────────────────┤
# │                               <  OK  >                                 │
# └────────────────────────────────────────────────────────────────────────┘

# Installation complete!
expect {
  "succeeded!" {
    send_user "Bhyve installation finished."
    sleep 5
    exit 0
  }

  "failed." {
    send_user "Bhyve installation failed."
    sleep 5
    exit 1
  }
}
