#!/usr/bin/env python3
# Author: Eric Turgeon
# License: BSD

from middlewared.test.integration.utils import client
from middlewared.test.integration.runner import parse
from ipaddress import ip_interface
from subprocess import run, call
from sys import exit
import os
import random
import socket
import sys
import secrets
import string
import json
import shutil

TEST_DIR_TO_RESULT = {
    'api2': 'results/api_v2_tests_result.xml',
    'directory_services': 'results/directoryservices_tests_result.xml',
    'stig': 'results/stig_tests_result.xml',
    'sharing_protocols': 'results/sharing_protocols_tests_result.xml',
    'sharing_protocols/fibre_channel': 'results/sharing_protocols_fibre_channel_tests_result.xml',
    'sharing_protocols/iscsi': 'results/sharing_protocols_iscsi_tests_result.xml',
    'sharing_protocols/nfs': 'results/sharing_protocols_nfs_tests_result.xml',
    'sharing_protocols/nvmet': 'results/sharing_protocols_nvmet_tests_result.xml',
    'sharing_protocols/smb': 'results/sharing_protocols_smb_tests_result.xml',
    'cloud': 'results/cloud_tests_result.xml',
    'vm': 'results/vm_result.xml',
}

initial_env_key = set(os.environ.keys())

workdir = os.getcwd()
sys.path.append(workdir)
localHome = os.path.expanduser('~')
keyPath = localHome + '/.ssh/test_id_rsa'

ixautomation_dot_conf_url = "https://raw.githubusercontent.com/iXsystems/" \
    "ixautomation/master/src/etc/ixautomation.conf.dist"
config_file_msg = "Please add config.py to freenas/tests which can be empty " \
    f"or contain settings from {ixautomation_dot_conf_url}"

if not os.path.exists('config.py'):
    print(config_file_msg)
    exit(1)

args = parse()

callargs = []
if args.no_capture:
    callargs.append('-s')
if args.log_cli_level:
    callargs.append('--log-cli-level')
    callargs.append(args.log_cli_level)

ha_license = args.ha_license
if args.ha_license_path:
    with open(args.ha_license_path) as f:
        ha_license = f.read()

vip = args.vip
hostname = args.hostname

# create random hostname and random fake domain
digit = ''.join(secrets.choice((string.ascii_uppercase + string.digits)) for i in range(10))
digit = 'AUTOGENERATED'
if not hostname:
    hostname = f'test{digit}'
domain = f'{hostname}.nb.ixsystems.net'
artifacts = f"{workdir}/artifacts/"
if not os.path.exists(artifacts):
    os.makedirs(artifacts)

os.environ["MIDDLEWARE_TEST_IP"] = args.ip
os.environ["MIDDLEWARE_TEST_PASSWORD"] = args.password
os.environ["SERVER_TYPE"] = "ENTERPRISE_HA" if args.ha else "STANDARD"

ip_to_use = args.ip
if args.ha and args.ip2:
    domain = 'tn.ixsystems.com'
    os.environ['controller1_ip'] = args.ip
    os.environ['controller2_ip'] = args.ip2


def get_ipinfo(ip_to_use):
    return (
        'eth0',
        '.'.join(ip_to_use.split('.')[:3] + ['128']),
        '.'.join(ip_to_use.split('.')[:3] + ['129']),
        '.'.join(ip_to_use.split('.')[:3] + ['130']),
        '.'.join(ip_to_use.split('.')[:3] + ['131']),
    )

    iface = net = gate = ns1 = ns2 = None
    with client(host_ip=ip_to_use) as c:
        net_config = c.call('network.configuration.config')
        ns1 = net_config.get('nameserver1')
        ns2 = net_config.get('nameserver2')
        _ip_to_use = socket.gethostbyname(ip_to_use)
        for i in c.call('interface.query'):
            for j in i['state']['aliases']:
                if j.get('address') == _ip_to_use:
                    iface = i['id']
                    net = j['netmask']
                    for k in c.call('route.system_routes'):
                        if k.get('network') == '0.0.0.0' and k.get('gateway'):
                            return iface, net, k['gateway'], ns1, ns2

    return iface, net, gate, ns1, ns2


interface, netmask, gateway, ns1, ns2 = get_ipinfo(ip_to_use)
if not all((interface, netmask, gateway)):
    print(f'Unable to determine interface ({interface!r}), netmask ({netmask!r}) and gateway ({gateway!r}) for {ip_to_use!r}')
    exit()


def get_random_vip():
    return '.'.join(args.ip.split('.')[:3] + ['132'])

    # reduce risk of trying to assign same VIP to two VMs
    # starting at roughly the same time
    vip_pool = list(ip_interface(f'{args.ip}/{netmask}').network)
    random.shuffle(vip_pool)

    for i in vip_pool:
        last_octet = int(i.compressed.split('.')[-1])
        if last_octet < 15 or last_octet >= 250:
            # addresses like *.255, *.0 and any of them that
            # are < *.15 we'll ignore. Those are typically
            # reserved for routing/switch devices anyways
            continue
        elif run(['ping', '-c', '2', '-w', '4', i.compressed]).returncode != 0:
            # sent 2 packets to the address and got no response so assume
            # it's safe to use
            return i.compressed

    raise RuntimeError('Unable to come up with vip address')


if args.ha:
    if vip:
        os.environ['virtual_ip'] = vip
    elif os.environ.get('virtual_ip'):
        vip = os.environ['virtual_ip']
    else:
        os.environ['virtual_ip'] = get_random_vip()
        vip = os.environ['virtual_ip']

    # Set various env variables for HA, if not already set
    if not os.environ.get('domain'):
        os.environ['domain'] = domain
    if not os.environ.get('hostname_virtual'):
        os.environ['hostname_virtual'] = hostname
    if not os.environ.get('hostname'):
        os.environ['hostname'] = f'{hostname}-nodea'
    if not os.environ.get('hostname_b'):
        os.environ['hostname_b'] = f'{hostname}-nodeb'
    if not os.environ.get('primary_dns'):
        os.environ['primary_dns'] = ns1 or '10.230.0.10'
    if not os.environ.get('secondary_dns'):
        os.environ['secondary_dns'] = ns2 or '10.230.0.11'

cfg_content = f"""#!{sys.executable}

user = "root"
password = "{args.password}"
netmask = "{netmask}"
gateway = "{gateway}"
vip = "{vip}"
vm_name = {f"'{args.vm_name}'" if args.vm_name else None}
hostname = "{hostname}"
domain = "{domain}"
api_url = 'http://{args.ip}/api/v2.0'
interface = "{interface}"
badNtpServer = "10.20.20.122"
localHome = "{localHome}"
keyPath = "{keyPath}"
pool_name = "{args.pool_name}"
ha_pool_name = "ha"
ha = {args.ha}
ha_license = {ha_license!r}
update = {args.update}
artifacts = "{artifacts}"
isns_ip = "{args.isns_ip}"
extended_tests = {args.extended_tests}
"""

cfg_file = open("auto_config.py", 'w')
cfg_file.writelines(cfg_content)
cfg_file.close()

from functions import setup_ssh_agent, create_key, add_ssh_key, get_folder
from functions import SSH_TEST
"""
# Setup ssh agent before starting test.
setup_ssh_agent()
if os.path.isdir(dotsshPath) is False:
    os.makedirs(dotsshPath)
if os.path.exists(keyPath) is False:
    create_key(keyPath)
add_ssh_key(keyPath)
"""

f = open(keyPath + '.pub', 'r')
Key = f.readlines()[0].rstrip()

cfg_file = open("auto_config.py", 'a')
cfg_file.writelines(f'sshKey = "{Key}"\n')
cfg_file.close()

if args.verbose:
    callargs.append("-" + "v" * args.verbose)
if args.exit_first:
    callargs.append("-x")

if args.show_locals:
    callargs.append('--showlocals')

# Use the right python version to start pytest with sys.executable
# So that we can support virtualenv python pytest.
pytest_command = [
    sys.executable,
    '-m',
    'pytest'
] + callargs + [
    "-o", "junit_family=xunit2",
    '--timeout=300',
    "--junitxml",
    TEST_DIR_TO_RESULT[args.test_dir],
]
if args.testexpr:
    pytest_command.extend(['-k', args.testexpr])


def parse_test_name(test):
    test = test.removeprefix(f"{args.test_dir}/")
    test = test.removeprefix(f"{args.test_dir}.")
    if ".py" not in test and test.count(".") == 1:
        # Test name from Jenkins
        filename, testname = test.split(".")
        return f"{filename}.py::{testname}"
    return test


def parse_test_name_prefix_dir(test_name):
    name = parse_test_name(test_name)
    if name.startswith('/'):
        return name
    else:
        return f"{args.test_dir}/{name}"


if args.tests:
    pytest_command.extend(list(map(parse_test_name_prefix_dir, args.tests.split(','))))
else:
    pytest_command.append(parse_test_name_prefix_dir(args.test))

runtest_output_dir = os.environ.get('RUNTEST_OUTPUT_DIR', 'runtest_references')
runtest_test_dir = f"{runtest_output_dir}/{os.environ['RUNTEST_TEST_NAME']}"
os.makedirs(runtest_test_dir, exist_ok=True)
shutil.copy("auto_config.py", runtest_test_dir)
with open(f"{runtest_test_dir}/result", "w") as f:
    f.write(json.dumps({
        "argv": sys.argv[1:],
        "command": pytest_command,
        "returncode": args.returncode,
        "artifacts": artifacts,
        "ip": args.ip,
        "ip2": args.ip2,
        "environ": {k: v for k, v in os.environ.items() if k not in initial_env_key},
    }))

sys.exit(0)

proc_returncode = call(pytest_command)


def get_cmd_result(cmd: str, target_file: str, target_ip: str):
    try:
        results = SSH_TEST(cmd, 'root', 'testing', target_ip)
    except Exception as exc:
        with open(f'{target_file}.error.txt', 'w') as f:
            f.write(f'{target_ip}: command [{cmd}] failed: {exc}\n')
            f.flush()
    else:
        with open(target_file, 'w') as f:
            f.writelines(results['stdout'])
            f.flush()


if args.ha:
    get_folder('/var/log', f'{artifacts}/log_nodea', 'root', 'testing', args.ip)
    get_folder('/var/log', f'{artifacts}/log_nodeb', 'root', 'testing', args.ip2)
    get_cmd_result('midclt call core.get_jobs | jq .', f'{artifacts}/core.get_jobs_nodea.json', args.ip)
    get_cmd_result('midclt call core.get_jobs | jq .', f'{artifacts}/core.get_jobs_nodeb.json', args.ip2)
    get_cmd_result('dmesg', f'{artifacts}/dmesg_nodea.json', args.ip)
    get_cmd_result('dmesg', f'{artifacts}/dmesg_nodeb.json', args.ip2)
else:
    get_folder('/var/log', f'{artifacts}/log', 'root', 'testing', args.ip)
    get_cmd_result('midclt call core.get_jobs | jq .', f'{artifacts}/core.get_jobs.json', args.ip)
    get_cmd_result('dmesg', f'{artifacts}/dmesg.json', args.ip)

if args.returncode:
    exit(proc_returncode)
