#!/bin/sh

. /etc/rc.freenas

cifs_file="/tmp/.cifs_AD"
service=/usr/sbin/service
python=/usr/local/bin/python
notifier=/usr/local/www/freenasUI/middleware/notifier.py

adctl_cmd()
{
	local args="$*"

	if [ -n "${args}" ]
	then
		logger -t ActiveDirectory "${args}"
		${args}
		return $?
	fi

	return 0
}

cifs_enabled()
{
	srv_enabled cifs && return 0
	return 1
}

ad_enabled()
{
	srv_enabled activedirectory && return 0
	return 1
}

cifs_start()
{
	adctl_cmd ${python} ${notifier} start cifs
	return $?
}

cifs_stop()
{
	adctl_cmd ${python} ${notifier} stop cifs
	return $?
}

cifs_restart()
{
	adctl_cmd ${python} ${notifier} stop cifs
	adctl_cmd ${python} ${notifier} start cifs
	return $?
}

adctl_start()
{
	local cifs_started=0	
	local ad_started=0

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	else
		srv_set cifs 1
	fi

	if ad_enabled
	then
		ad_started=1
	else		
		srv_set activedirectory 1
	fi

	echo ${cifs_started} > "${cifs_file}"

	adctl_cmd ${service} ix-kerberos quietstart

	adctl_cmd ${service} ix-nsswitch quietstart
	adctl_cmd ${service} ix-pam quietstart

	adctl_cmd ${service} ix-kinit quietstart
	adctl_cmd ${service} ix-kinit status || return 1

	adctl_cmd ${service} ix-samba quietstart
	cifs_start

	adctl_cmd ${service} ix-activedirectory quietstart || return 1
	adctl_cmd ${service} ix-activedirectory status || return 1

	cifs_restart

	adctl_cmd "${service} ix-cache quietstart &"

	return 0
}

adctl_stop()
{
	local cifs_started=1
	local prev_cifs_started=0
	if [ -s "${cifs_file}" ]
	then
		prev_cifs_started="$(cat "${cifs_file}")"
	fi

	if ! ad_enabled
	then
		return 1
	fi

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	fi

	adctl_cmd ${service} ix-kerberos quietstart
	adctl_cmd ${service} ix-nsswitch quietstart
	adctl_cmd ${service} ix-pam quietstart
	adctl_cmd ${service} ix-kinit forcestop
	adctl_cmd ${service} ix-activedirectory forcestop
	adctl_cmd "${service} ix-cache quietstop &"

	if [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "0" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set cifs 0
		srv_set activedirectory 0
		adctl_cmd ${service} ix-samba start

	elif [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "1" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set cifs 0
		srv_set activedirectory 0
		adctl_cmd ${service} ix-samba start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "0" ]
	then
		adctl_cmd ${service} samba forcestop
		srv_set activedirectory 0
		srv_set cifs 1
		adctl_cmd ${service} ix-samba start
		cifs_start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "1" ]		
	then
		adctl_cmd ${service} samba forcestop
		srv_set activedirectory 0
		srv_set cifs 1
		adctl_cmd ${service} ix-samba start
		cifs_start
	fi

	srv_set activedirectory 0
	return 0
}

adctl_restart()
{
	adctl_start
	adctl_stop
}

usage()
{
	echo "Usage: $0 (start|stop|restart)"
	exit 1
}

if [ "$#" -lt "1" ]
then
	usage
fi

cmd="$(echo "${1}"|tr A-Z a-z)"
case "${cmd}" in
	start) adctl_start ;;
	stop) adctl_stop ;;
	restart) adctl_restart ;;
	*) usage ;;
esac

exit $?
