# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-06 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_201708211858'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='cert_san',
            field=models.TextField(blank=True, help_text='Multi-domain support. Enter additional space separated domains', null=True, verbose_name='Subject Alternate Names'),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='cert_san',
            field=models.TextField(blank=True, help_text='Multi-domain support. Enter additional space separated domains', null=True, verbose_name='Subject Alternate Names'),
        ),
    ]
