# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20170906_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='adv_cpu_in_percentage',
            field=models.BooleanField(default=False, help_text='collectd will report CPU usage in percentage instead of "jiffies" if this is checked.', verbose_name='Report CPU usage in percentage'),
        ),
    ]
