# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-02 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20180219_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='adv_sed_passwd',
            field=models.CharField(blank=True, help_text='Global password to unlock SED disks.', max_length=120, verbose_name='SED Password'),
        ),
    ]
