# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-12 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_alert'),
        ('system', '0021_merge_20180612_2332'),
        ('system', '0022_cloud_sync'),
    ]

    operations = [
    ]
