# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-07-16 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0024_rename_bes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advanced',
            name='adv_consolescreensaver',
        )
    ]