# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-03 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0039_alerts_classes'),
        ('system', '0039_crash_reporting'),
    ]

    operations = [
    ]
