# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0049_graphite_separateinstances'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stg_guihttpsprotocols',
            field=freenasUI.freeadmin.models.fields.ListField(default=['TLSv1', 'TLSv1.1', 'TLSv1.2', 'TLSv1.3'], verbose_name='WebGUI HTTPS Protocols'),
        ),
    ]
