# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-11 14:45
from __future__ import unicode_literals

from django.db import migrations

def remove_non_dimissed(apps, schema_editor):
    Alert = apps.get_model('system', 'Alert')
    Alert.objects.filter(dismiss=False).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_consulalerts'),
    ]

    operations = [
        migrations.RunPython(
            remove_non_dimissed,
        ),
        migrations.RemoveField(
            model_name='alert',
            name='dismiss',
        ),
        migrations.RemoveField(
            model_name='alert',
            name='timestamp',
        ),
    ]
