# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-03 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20170411_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consulalerts',
            options={'ordering': ['consulalert_type'], 'verbose_name': 'Alert Service', 'verbose_name_plural': 'Alert Services'},
        ),
        migrations.AlterField(
            model_name='consulalerts',
            name='consulalert_type',
            field=models.CharField(choices=[('AWS-SNS', 'AWS-SNS'), ('HipChat', 'HipChat'), ('InfluxDB', 'InfluxDB'), ('Mattermost', 'Mattermost'), ('OpsGenie', 'OpsGenie'), ('PagerDuty', 'PagerDuty'), ('Slack', 'Slack'), ('VictorOps', 'VictorOps')], default='AWS-SNS', max_length=20, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='consulalerts',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
