# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20170503_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced',
            name='adv_consolemenu',
            field=models.BooleanField(default=False, verbose_name='Show Text Console without Password Prompt'),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='adv_motd',
            field=models.TextField(blank=True, default='Welcome', max_length=1024, verbose_name='MOTD banner'),
        ),
    ]
