# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-27 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20170712_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tunable',
            name='tun_var',
            field=models.CharField(max_length=128, unique=True, verbose_name='Variable'),
        ),
    ]
