# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-02 13:55
from __future__ import unicode_literals

from django.db import migrations, models

def migrate_data(apps, schema_editor):
    advanced = apps.get_model('system', 'Advanced')
    system_general = apps.get_model('system', 'Settings')
    adv = advanced.objects.order_by('-id')[0]
    settingsm = system_general.objects.order_by('-id')[0]
    adv.adv_sysloglevel = settingsm.stg_sysloglevel
    adv.adv_syslogserver = settingsm.stg_syslogserver
    adv.save()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20170906_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='advanced',
            name='adv_sysloglevel',
            field=models.CharField(choices=[('f_emerg', 'Emergency'), ('f_alert', 'Alert'), ('f_crit', 'Critical'), ('f_err', 'Error'), ('f_warning', 'Warning'), ('f_notice', 'Notice'), ('f_info', 'Info'), ('f_debug', 'Debug'), ('f_is_debug', 'Is_Debug')], default='f_info', help_text='Specifies which messages will be logged by server. INFO and VERBOSE log transactions that server performs on behalf of the client. f_is_debug specify higher levels of debugging output. The default is f_info.', max_length=120, verbose_name='Syslog level'),
        ),
        migrations.AddField(
            model_name='advanced',
            name='adv_syslogserver',
            field=models.CharField(blank=True, default='', help_text='Specifies the server and port syslog messages will be sent to.  The accepted format is hostname:port or ip:port, if :port is not specified it will default to port 514 (this field currently only takes IPv4 addresses)', max_length=120, verbose_name='Syslog server'),
        ),
        migrations.RunPython(migrate_data),
        migrations.RemoveField(
            model_name='settings',
            name='stg_sysloglevel',
        ),
        migrations.RemoveField(
            model_name='settings',
            name='stg_syslogserver',
        ),
    ]
