# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-09-28 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20170926_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='stg_syslogserver',
        ),
        migrations.AddField(
            model_name='advanced',
            name='adv_syslogserver',
            field=models.CharField(blank=True, default='', help_text='Specifies the server and port syslog messages will be sent to.  The accepted format is hostname:port or ip:port, if :port is not specified it will default to port 514 (this field currently only takes IPv4 addresses)', max_length=120, verbose_name='Syslog server'),
        ),
        migrations.AlterField(
            model_name='advanced',
            name='adv_serialport',
            field=models.CharField(choices=[('0x248', '0x248'), ('0x3f8', '0x3f8')], default='0x2f8', help_text='Set this to match your serial port address (0x3f8, 0x2f8, etc.)', max_length=120, verbose_name='Serial Port Address'),
        ),
        migrations.AlterField(
            model_name='consulalerts',
            name='consulalert_type',
            field=models.CharField(choices=[('AWSSNS', 'AWS-SNS'), ('HipChat', 'HipChat'), ('InfluxDB', 'InfluxDB'), ('Mattermost', 'Mattermost'), ('OpsGenie', 'OpsGenie'), ('PagerDuty', 'PagerDuty'), ('Slack', 'Slack'), ('VictorOps', 'VictorOps')], default='AWS-SNS', max_length=20, verbose_name='Service Name'),
        ),
    ]
