# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-04-11 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_merge_20180409_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advanced',
            name='adv_motd',
            field=models.TextField(blank=True, default='Welcome', max_length=10240, verbose_name='MOTD banner'),
        ),
    ]
