# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-12 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0016_encrypt_cloud_credentials'),
        ('system', '0020_auto_20180502_1200'),
    ]

    operations = [
    ]
