# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-07 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_auto_20180502_1200'),
        ('system', '0019_increase_motd'),
    ]

    operations = [
    ]
