# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-05-14 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_merge_20180612_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cert_serial',
            field=models.CharField(blank=True, help_text='Serial for next certificate', max_length=48, null=True, verbose_name='Serial'),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='cert_serial',
            field=models.CharField(blank=True, help_text='Serial for next certificate', max_length=48, null=True, verbose_name='Serial'),
        ),
    ]
