# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 06:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0026_keyvalue'),
        ('system', '0021_merge_20180507_1315'),
    ]

    operations = [
    ]
