# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-07 06:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0027_add_organizational_unit'),
        ('system', '0027_merge_20180807_0638'),
    ]

    operations = [
    ]
