# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-10-16 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0030_ip_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeychainCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('attributes', freenasUI.freeadmin.models.fields.EncryptedDictField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
