# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-10 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


def create_reporting(apps, schema_editor):
    advanced = apps.get_model('system', 'Advanced').objects.latest('id')
    systemdataset = apps.get_model('system', 'SystemDataset').objects.latest('id')

    reporting = apps.get_model('system', 'Reporting').objects.create()
    reporting.rrd_usedataset = systemdataset.sys_rrd_usedataset
    reporting.cpu_in_percentage = advanced.adv_cpu_in_percentage
    reporting.graphite = advanced.adv_graphite
    reporting.save()


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0036_remove_parseable_cert_attrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rrd_usedataset', models.BooleanField(default=True, help_text='Store reporting database in system dataset instead of RAMDisk. Checking this will decrease RAM usage and increase IO on system dataset pool.', verbose_name='Store reporting database in system dataset')),
                ('cpu_in_percentage', models.BooleanField(default=False, help_text='collectd will report CPU usage in percentage instead of "jiffies" if this is checked.', verbose_name='Report CPU usage in percentage')),
                ('graphite', models.CharField(blank=True, default='', help_text='A hostname or IP here will be used as the destination to send collectd data to using the graphite plugin to collectd.', max_length=120, verbose_name='Graphite server')),
                ('rrd_ramdisk_size', models.IntegerField(default=1073741824, verbose_name='Reporting database RAMDisk size')),
                ('graph_timespans', freenasUI.freeadmin.models.fields.ListField(default=[3600, 86400, 604800, 2678400, 31622400], help_text='Time periods for which aggregated historical data will be stored. See collect RRARows option documentation for more details', verbose_name='Graph time spans')),
                ('graph_rows', models.IntegerField(default=1200, help_text='Number of points for each time period. See collect RRATimespan option documentation for more details', verbose_name='Graph points count')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_reporting),
        migrations.RemoveField(
            model_name='advanced',
            name='adv_cpu_in_percentage',
        ),
        migrations.RemoveField(
            model_name='advanced',
            name='adv_graphite',
        ),
        migrations.RemoveField(
            model_name='systemdataset',
            name='sys_rrd_usedataset',
        ),
    ]
