# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-05 16:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0042_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='stg_usage_collection',
            field=models.NullBooleanField(help_text='Enable sending anonymous usage collection to iXsystems', verbose_name='Usage collection'),
        )
    ]
