# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2020-05-27 10:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0046_legacy_ui'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alert',
            unique_together=set([]),
        ),
    ]
