# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-10 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0048_revoked_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporting',
            name='graphite_separateinstances',
            field=models.BooleanField(default=False, help_text='If checked, the plugin instance and type instance will be in their own path component, for example host.cpu.0.cpu.idle. If unchecked (the default), the plugin and plugin instance (and likewise the type and type instance) are put into one component, for example host.cpu-0.cpu-idle.', verbose_name='Graphite SeparateInstances'),
        ),
    ]
