# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-17 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_add_s3_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='cifs',
            name='cifs_srv_ntlmv1_auth',
            field=models.BooleanField(default=False, help_text='This parameter determines whether or not smbd(8) will attempt toauthenticate users using the NTLMv1 encrypted password response', verbose_name='NTLMv1 auth'),
        ),
    ]
