# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-18 23:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_s3_help_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='afp',
            name='afp_chmod_request',
            field=models.CharField(choices=[('ignore', 'Ignore'), ('preserve', 'Preserve'), ('simple', 'Simple')], default='preserve', help_text="\n            Advanced permission control that deals with ACLs.\n\n            ignore - UNIX chmod() requests are completely ignored, use this\n            option to allow the parent directory's ACL inheritance full\n            control over new items.\n\n            preserve - preserve ZFS ACEs for named users and groups or\n            POSIX ACL group mask\n\n            simple - just to a chmod() as requested without any extra steps\n            ", max_length=120, verbose_name='Chmod Request'),
        ),
    ]
