# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-27 10:32
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_add_netdata_bare_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssh',
            name='ssh_options',
            field=models.TextField(blank=True, help_text='Extra options to /usr/local/etc/ssh/sshd_config (usually empty). Note, incorrect entered options prevent SSH service to be started.', verbose_name='Extra options'),
        ),
    ]
