# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-29 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20170712_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='ups',
            name='ups_nocommwarntime',
            field=models.IntegerField(blank=True, help_text='Notify after this many seconds if it can’t reach any of the UPS. It keeps warning you until the situation is fixed. Default is 300 seconds.', null=True, verbose_name='No Communication Warning Time'),
        ),
    ]
