# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-16 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_cifs_srv_min_protocol_core'),
    ]

    operations = [
        migrations.AddField(
            model_name='s3',
            name='s3_certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Certificate', verbose_name='Certificate'),
        ),
    ]
