# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-17 07:42
from __future__ import unicode_literals

from django.db import migrations, models
from freenasUI.middleware.notifier import notifier


def add_asigra(apps, schema_editor):
    if notifier().is_freenas():
        return

    services = apps.get_model('services', 'services')
    asigra = services.objects.create()
    asigra.srv_service = 'asigra'
    asigra.srv_enable = False
    asigra.save()

    apps.get_model('services', 'asigra').objects.create()


def remove_asigra(apps, schema_editor):
    if notifier().is_freenas():
        return

    services = apps.get_model('services', 'services')
    services.objects.filter(srv_service='asigra').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_ftp_set_unlimited_length_for_ftp_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asigra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesystem', models.CharField(default='', max_length=100, verbose_name='Base Filesystem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(add_asigra, reverse_code=remove_asigra)
    ]
