# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models
from freenasUI.common.pipesubr import pipeopen

import sys
import os

def fix_samba_private_dir(apps, schema_editor):
    root_private_dir = "/root/samba/private/"
    private_dir = "/var/db/samba4/private/"

    if not os.access(private_dir, os.F_OK):
        try:
            os.makedirs(private_dir)

        except Exception as e:
            print(f"ERROR: unable to create samba private dir: {e}", file=sys.stderr)
            return

        os.chmod(private_dir, 0o700)

    try:
        pipeopen(f"/usr/local/bin/rsync -avz '{root_private_dir}' '{private_dir}'").wait()
        pipeopen(f"/bin/mv '{root_private_dir}' '{root_private_dir}'.bak").wait()

    except Exception as e:    
        print(e, file=sys.stderr)
        return


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_remove_afp_srv_home'),
    ]

    operations = [
        migrations.RunPython(
            fix_samba_private_dir
        )
    ]
