# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-16 12:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_make_lunid_non_null'),
        ('services', '0020_add_enable_smb1'),
    ]

    operations = [
    ]
