# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_tftp_host'),
        ('services', '0022_merge_20181206_0716'),
    ]

    operations = [
    ]
