# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-12-06 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_merge_20181116_1203'),
        ('services', '0022_merge_20181206_0716'),
        ('services', '0023_configurable_netdata_metrics'),
    ]

    operations = [
    ]
