# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-14 11:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_merge_20190114_2056'),
        ('services', '0024_merge_20181206_0849'),
    ]

    operations = [
    ]
