# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-22 04:56
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_add_admin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmp',
            name='snmp_zilstat',
            field=models.BooleanField(default=False, verbose_name='Expose zilstat via SNMP'),
        ),
    ]
