# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-16 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0027_auto_20190307_1006'),
        ('services', '0027_kill_domaincontroller'),
    ]

    operations = [
    ]
