# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-10 03:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_merge_20190316_0802'),
        ('services', '0024_add_admin_group'),
    ]

    operations = [
    ]
