# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-22 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_snmp_zilstat'),
        ('services', '0029_merge_20190410_0351'),
    ]

    operations = [
    ]
