# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-08 11:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_remove_service_monitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscsitargetextent',
            name='iscsi_target_extent_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
