# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-11 09:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_openvpn_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='nfs',
            name='nfs_srv_v4_domain',
            field=models.CharField(default='', help_text='Override the default DNS domain name', max_length=120, verbose_name='NFSv4 nfsuserd(8) domain name'),
            preserve_default=False,
        ),
    ]
