#############################################################################
# Makefile for building: warden 
#############################################################################

####### Install

all:

install_doinstall:
	sh install.sh

install:  install_doinstall
