'\" t
.\"     Title: regshell
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 03/26/2015
.\"    Manual: System Administration tools
.\"    Source: Samba 4.0
.\"  Language: English
.\"
.TH "REGSHELL" "1" "03/26/2015" "Samba 4\&.0" "System Administration tools"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
regshell \- Windows registry file browser using readline
.SH "SYNOPSIS"
.HP \w'\fBregshell\fR\ 'u
\fBregshell\fR [\-\-help] [\-\-backend=BACKEND] [\-\-credentials=CREDENTIALS] [location]
.SH "DESCRIPTION"
.PP
regshell is a utility that lets you browse thru a Windows registry file as if you were using a regular unix shell to browse thru a file system\&.
.SH "OPTIONS"
.PP
\-\-help
.RS 4
Show list of available options\&.
.RE
.PP
\-\-backend BACKEND
.RS 4
Name of backend to load\&. Possible values are: creg, regf, dir and rpc\&. The default is
\fIdir\fR\&.
.RE
.PP
\-\-credentials=CREDENTIALS
.RS 4
Credentials to use, if any\&. Password should be separated from user name by a percent sign\&.
.RE
.SH "COMMANDS"
.PP
ck|cd <keyname>
.RS 4
Go to the specified subkey\&.
.RE
.PP
ch|predef [predefined\-key\-name]
.RS 4
Go to the specified predefined key\&.
.RE
.PP
list|ls
.RS 4
List subkeys and values of the current key\&.
.RE
.PP
mkkey|mkdir <keyname>
.RS 4
Create a key with the specified
\fIkeyname\fR
as a subkey of the current key\&.
.RE
.PP
rmval|rm <valname>
.RS 4
Delete the specified value\&.
.RE
.PP
rmkey|rmdir <keyname>
.RS 4
Delete the specified subkey recursively\&.
.RE
.PP
pwd|pwk
.RS 4
Print the full name of the current key\&.
.RE
.PP
set|update
.RS 4
Update the value of a key value\&. Not implemented at the moment\&.
.RE
.PP
help|?
.RS 4
Print a list of available commands\&.
.RE
.PP
exit|quit
.RS 4
Leave regshell\&.
.RE
.SH "EXAMPLES"
.PP
Browsing thru a nt4 registry file
.sp
.if n \{\
.RS 4
.\}
.nf
\fBregshell \-b nt4 NTUSER\&.DAT\fR
$$$PROTO\&.HIV> \fBls\fR
K AppEvents
K Console
K Control Panel
K Environment
K Identities
K Keyboard Layout
K Network
K Printers
K Software
K UNICODE Program Groups
K Windows 3\&.1 Migration Status
$$$PROTO\&.HIV> \fBexit\fR
.fi
.if n \{\
.RE
.\}
.PP
Listing the subkeys of HKEY_CURRENT_USER\eAppEvents on a remote computer:
.sp
.if n \{\
.RS 4
.\}
.nf
\fBregshell \-\-remote=ncacn_np:aurelia \-c "jelmer%secret"\fR
HKEY_CURRENT_MACHINE> \fBpredef HKEY_CURRENT_USER\fR
HKEY_CURRENT_USER> \fBcd AppEvents\fR
Current path is: HKEY_CURRENT_USER\eAppEvents
HKEY_CURRENT_USER\eAppEvents> \fBls\fR
K EventLabels
K Schemes
HKEY_CURRENT_USER\eAppEvents> \fBexit\fR
.fi
.if n \{\
.RE
.\}
.SH "VERSION"
.PP
This man page is correct for version 4\&.0 of the Samba suite\&.
.SH "SEE ALSO"
.PP
regtree, regdiff, regpatch, gregedit, samba
.SH "AUTHOR"
.PP
This utility is part of the
\m[blue]\fBSamba\fR\m[]\&\s-2\u[1]\d\s+2
suite, which is developed by the global
\m[blue]\fBSamba Team\fR\m[]\&\s-2\u[2]\d\s+2\&.
.PP
This manpage and regshell were written by Jelmer Vernooij\&.
.SH "NOTES"
.IP " 1." 4
Samba
.RS 4
\%http://www.samba.org/
.RE
.IP " 2." 4
Samba Team
.RS 4
\%http://www.samba.org/samba/team/
.RE
