#!/bin/sh

firefly_path=/usr/pbi/firefly-$(uname -m)
tmpfile=$(mktemp /tmp/.XXXXXX)

grep -v 'firefly_' /etc/rc.conf > ${tmpfile}
cat ${firefly_path}/etc/rc.conf >> ${tmpfile}
mv ${tmpfile} /etc/rc.conf
