# Created by: Sunpoet Po-Chuan Hsieh <sunpoet@FreeBSD.org>
# $FreeBSD: head/devel/py-setuptools36/Makefile 429453 2016-12-25 19:21:51Z sunpoet $

PKGNAMESUFFIX=	${PYTHON_SUFFIX}

PYTHON_VERSION=	python3.6

MASTERDIR=	${.CURDIR}/../py-setuptools

.include "${MASTERDIR}/Makefile"
