NETLINK_GENERIC = 16
NLM_F_REQUEST = 0x01
NLM_F_ACK = 0x04
NLMSG_ERROR = 0x02

GENL_ID_CTRL = 0x10
CTRL_CMD_GETFAMILY = 3
CTRL_ATTR_FAMILY_NAME = 2
CTRL_ATTR_FAMILY_ID = 1

ETHTOOL_MSG_STRSET_GET = 1
ETHTOOL_MSG_LINKINFO_GET = 2
ETHTOOL_MSG_LINKMODES_GET = 4
ETHTOOL_MSG_LINKSTATE_GET = 6
ETHTOOL_MSG_FEATURES_GET = 11

ETHTOOL_A_HEADER = 1
ETHTOOL_A_HEADER_DEV_NAME = 2
ETHTOOL_A_HEADER_FLAGS = 3

ETHTOOL_A_LINKMODES_AUTONEG = 2
ETHTOOL_A_LINKMODES_OURS = 3
ETHTOOL_A_LINKMODES_SPEED = 5
ETHTOOL_A_LINKMODES_DUPLEX = 6

ETHTOOL_A_BITSET_SIZE = 2
ETHTOOL_A_BITSET_BITS = 3
ETHTOOL_A_BITSET_VALUE = 4
ETHTOOL_A_BITSET_MASK = 5

ETHTOOL_A_BITSET_BITS_BIT = 1
ETHTOOL_A_BITSET_BIT_INDEX = 1
ETHTOOL_A_BITSET_BIT_VALUE = 3

ETHTOOL_A_LINKINFO_PORT = 2
ETHTOOL_A_LINKINFO_PHYADDR = 3
ETHTOOL_A_LINKINFO_TRANSCEIVER = 6

ETHTOOL_A_LINKSTATE_LINK = 2

ETHTOOL_A_FEATURES_HW = 2
ETHTOOL_A_FEATURES_ACTIVE = 4
ETHTOOL_A_FEATURES_NOCHANGE = 5

ETHTOOL_A_STRSET_STRINGSETS = 2
ETHTOOL_A_STRINGSETS_STRINGSET = 1
ETHTOOL_A_STRINGSET_ID = 1
ETHTOOL_A_STRINGSET_STRINGS = 3
ETHTOOL_A_STRINGS_STRING = 1
ETHTOOL_A_STRING_INDEX = 1
ETHTOOL_A_STRING_VALUE = 2

ETH_SS_FEATURES = 4
ETH_SS_LINK_MODES = 9

NLA_F_NESTED = 0x8000
