#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: dispatcher
# REQUIRE: datastore

. /etc/rc.subr

name="etcd"
pidfile="/var/run/etcd.pid"
command="/usr/sbin/daemon"
start_precmd="prestart"

prestart()
{
    rc_flags="-P ${pidfile} -f -r /usr/local/sbin/etcd ${rc_flags}"
}

load_rc_config $name
run_rc_command $*