# $FreeBSD$
# $Id$
#
PORTNAME=	snmp_passpersist
PORTVERSION=    1.3.0
PKGNAMEPREFIX=  ${PYTHON_PKGNAMEPREFIX}

CATEGORIES=     net-mgmt

MAINTAINER=     dev@ixsystems.com
COMMENT=	Python client library for Net-SNMP pass persist backend

LICENSE=	GPLv3

RUN_DEPENDS=	net-snmp>=0:${PORTSDIR}/net-mgmt/net-snmp

USE_GITHUB=	yes
GH_ACCOUNT=	nagius
GH_TAGNAME=	ee71064

USES=			python
USE_PYTHON=	distutils autoplist


.include <bsd.port.mk>
