"""Remove crash reporting

Revision ID: 7157386393d8
Revises: 88bfe11b5be5
Create Date: 2023-06-07 19:15:42.681905+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7157386393d8'
down_revision = '88bfe11b5be5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('stg_crash_reporting')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stg_crash_reporting', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
