# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-12 14:23
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('directoryservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='idmap_fruit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmap_ds_type', models.IntegerField(null=True)),
                ('idmap_ds_id', models.PositiveIntegerField(null=True)),
                ('idmap_fruit_range_low', models.IntegerField(default=90000001, verbose_name='Range Low')),
                ('idmap_fruit_range_high', models.IntegerField(default=100000000, verbose_name='Range High')),
            ],
            options={
                'verbose_name': 'Fruit Idmap',
                'verbose_name_plural': 'Fruit Idmap',
            },
        ),
    ]
