# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-26 15:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directoryservice', '0002_idmap_fruit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NT4',
        ),
    ]
