.Dd Nov 18, 2010
.Dt PBI.CONF 5
.Os
.Sh NAME
.Nm pbi.conf 
.Nd PBI Configuration File
.Sh DESCRIPTION
The configuration file,
.Nm ,
allows the setting configuration values for the pbi_* related
commands.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It PBID_REFRESH:
Wakeup time in seconds for pbid to run checks
.It PBI_INDEXREFRESH:
Set the number of hours for pbid to refresh the index/meta files from repos.
.It PBI_PROXYURL:
Proxy server address to use for proxy communication.
.It PBI_PROXYPORT:
Proxy server port number to use for proxy communication. 
.It PBI_PROXYTYPE:
Sets the type of proxy server we will be communicating with. Possible values: HTTP SOCKS5.
.It PBI_PROXYUSER:
Username for authentication to the specified proxy server. 
.It PBI_PROXYPASS:
Password for authentication to the specified proxy server. 
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_delete 1 ,
.Xr pbi_makeport 1
