#!/bin/sh

. /etc/rc.freenas

cifs_file="/tmp/.cifs_AD"
status_file="/var/run/directoryservice.nt4"
service=/usr/sbin/service
python=/usr/local/bin/python
notifier=/usr/local/bin/midclt

nt4ctl_cmd()
{
	local args="$*"

	if [ -n "${args}" ]
	then
		logger -t NT4 "${args}"
		${args}
		return $?
	fi

	return 0
}

cifs_enabled()
{
	srv_enabled cifs && return 0
	return 1
}

cifs_start()
{
	nt4ctl_cmd ${python} ${notifier} call notifier.start cifs
	return $?
}

cifs_stop()
{
	nt4ctl_cmd ${python} ${notifier} call notifier.stop cifs
	return $?
}

cifs_restart()
{
	nt4ctl_cmd ${python} ${notifier} call notifier.stop cifs
	nt4ctl_cmd ${python} ${notifier} call notifier.start cifs
	return $?
}

nt4ctl_start()
{
	local cifs_started=0	
	local nt4_started=0

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	else
		srv_set cifs 1
	fi

	if nt4_enabled
	then
		nt4_started=1
	else		
		nt4_set 1
	fi

	echo ${cifs_started} > "${cifs_file}"

	nt4ctl_cmd ${service} ix-nsswitch quietstart
	nt4ctl_cmd ${service} ix-pam quietstart
	cifs_start

	if ! nt4ctl_cmd ${service} ix-nt4 quietstart
	then
		nt4_set 0
		return 1
	fi
	if ! nt4ctl_cmd ${service} ix-nt4 status
	then
		nt4_set 0
		return 1
	fi

	cifs_restart

	nt4ctl_cmd "${service} ix-cache quietstart &"
	touch "${status_file}"

	return 0
}

nt4ctl_stop()
{
	local cifs_started=1
	local prev_cifs_started=0
	if [ -s "${cifs_file}" ]
	then
		prev_cifs_started="$(cat "${cifs_file}")"
	fi

	if cifs_enabled
	then
		cifs_started=1
		cifs_stop
	fi

	nt4ctl_cmd ${service} ix-nsswitch quietstop
	nt4ctl_cmd ${service} ix-pam quietstop
	nt4ctl_cmd ${service} ix-nt4 forcestop
	nt4ctl_cmd "${service} ix-cache quietstop &"

	if [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "0" ]
	then
		nt4ctl_cmd ${service} samba_server forcestop
		srv_set cifs 0
		nt4_set 0
		nt4ctl_cmd ${service} ix-pre-samba start

	elif [ "${prev_cifs_started}" = "0" -a "${cifs_started}" = "1" ]
	then
		nt4ctl_cmd ${service} samba_server forcestop
		srv_set cifs 0
		nt4_set 0
		nt4ctl_cmd ${service} ix-pre-samba start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "0" ]
	then
		nt4ctl_cmd ${service} samba_server forcestop
		nt4_set 0
		srv_set cifs 1
		cifs_start

	elif [ "${prev_cifs_started}" = "1" -a "${cifs_started}" = "1" ]		
	then
		nt4ctl_cmd ${service} samba_server forcestop
		nt4_set 0
		srv_set cifs 1
		cifs_start
	fi

	nt4_set 0
	rm -f "${status_file}"

	return 0
}

nt4ctl_status()
{
	if [ -f "${status_file}" ]
	then
		nt4ctl_cmd ${service} ix-nt4 status
		return $?
	fi

	return 1
}

name="nt4ctl"
start_cmd='nt4ctl_start'
status_cmd='nt4ctl_status'
stop_cmd='nt4ctl_stop'
extra_commands='status'

load_rc_config $name
run_rc_command "$1"
