#!/usr/bin/env python
#+
# Copyright 2014 iXsystems, Inc.
# All rights reserved
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted providing that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS OR
# IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
# STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
# IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
#####################################################################

import argparse
import json
import datastore

DEFAULT_CONFIGFILE = '/conf/middleware.conf'
ds = None

def init_datastore(filename):
    global ds

    try:
        f = open(filename)
        conf = json.load(f)
        f.close()
    except IOError, err:
        return
    except ValueError, err:
        return

    if not 'datastore' in conf:
        pass

    try:
        ds = datastore.get_datastore(conf['datastore']['driver'], conf['datastore']['dsn'])
    except datastore.DatastoreException, err:
        pass

def dump_collection(ds, name):
    metadata = {
        'name': name,
        'pkey-type': ds.collection_get_pkey_type(name),
        'last-id': ds.collection_get_max_id(name)
    }

    return {
        'metadata': metadata,
        'data': list(ds.query(name))
    }


def main():
    global ds
    parser = argparse.ArgumentParser()
    parser.add_argument('-c', metavar='CONFIG', default=DEFAULT_CONFIGFILE, help='Config file name')
    parser.add_argument('-t', metavar='TYPE', help='Collection types to dump')
    parser.add_argument('-x', metavar='NOMETA', help='Don\'t include metadata')
    parser.add_argument('collections', metavar='COLLECTION', nargs='*', default='all', help='Collections to dump or "all"')
    args = parser.parse_args()
    init_datastore(args.c)

    types = args.t.split(',')
    result = []

    if 'all' in args.collections:
        args.collections = ds.collection_list()

    for cname in args.collections:
        attrs = ds.collection_get_attrs(cname)
        if 'type' in attrs.keys() and attrs['type'] not in types:
            continue

        result.append(dump_collection(ds, cname))

    print json.dumps(result, indent=4)

if __name__ == '__main__':
    main()