# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-25 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initshutdown',
            name='ini_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
