# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-08 10:34
from __future__ import unicode_literals

from django.db import migrations


def lower_type_and_when(apps, schema_editor):
    InitShutdown = apps.get_model('tasks', 'InitShutdown')
    for o in InitShutdown.objects.all():
        o.ini_type = o.ini_type.lower()
        o.ini_when = o.ini_when.lower()
        o.save()


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_merge_20180617_1001'),
    ]

    operations = [
        migrations.RunPython(lower_type_and_when, reverse_code=migrations.RunPython.noop),
    ]
