# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20180719_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsync',
            name='bwlimit',
            field=freenasUI.freeadmin.models.fields.DictField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
