#!/bin/sh
#
PATH=/bin:/usr/sbin:/usr/bin:/usr/sbin

DBDIR=/var/netatalk

case $2 in
	POST-INSTALL)
		tee $DBDIR/README > $DBDIR/CNID/README <<-'EOF'
			This directory contains modifiable Netatalk configuration files and the CNID databases.
		EOF
		;;
esac
