#!/bin/sh

# PROVIDE: warden
# REQUIRE: DAEMON
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="warden"
rcvar=`set_rcvar`

stop_cmd="warden_stop"
start_cmd="warden_start"

load_rc_config $name

: ${warden_enable=NO}

warden_start()
{
  PROGDIR="/usr/local/share/warden"
  $PROGDIR/scripts/rc.d/startup.sh
}

warden_stop()
{
  PROGDIR="/usr/local/share/warden"
  $PROGDIR/scripts/rc.d/shutdown.sh
}

run_rc_command "$1"

