#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: snmp-agent
# REQUIRE: snmpd

. /etc/rc.subr

name=snmp_agent
rcvar=snmp_agent_enable

load_rc_config $name

: ${snmp_agent_enable:="NO"}

PATH="$PATH:/usr/local/bin"
pidfile=/var/run/snmp-agent.pid
command="/usr/sbin/daemon"
command_args="-f -P ${pidfile} -r /usr/local/bin/snmp-agent.py"

run_rc_command "$1"
