# $FreeBSD$

PORTNAME=	backports.lzma
PORTVERSION=	0.0.6
CATEGORIES=	archivers python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	kmoore@FreeBSD.org
COMMENT=	Backport of the lzma function from Python 3.3

LICENSE=	BSD3CLAUSE

USES=		python:2.7
USE_PYTHON=	autoplist distutils

.include <bsd.port.mk>
