# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-20 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0006_auto_20171226_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='order',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
