# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-27 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0007_device_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='time',
            field=models.CharField(choices=[('LOCAL', 'Local Time'), ('UTC', 'UTC')], default='LOCAL', help_text='Use localtime or UTC inside the VM', max_length=5, verbose_name='System Clock'),
        ),
    ]
