# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-03-15 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vm', '0008_vm_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='vm',
            name='grubconfig',
            field=models.TextField(help_text='Grub.cfg file to be used on boot.', null=True, verbose_name='Grub Config'),
        ),
        migrations.RemoveField(
            model_name='vm',
            name='vm_type',
        ),
        migrations.AlterField(
            model_name='vm',
            name='bootloader',
            field=models.CharField(choices=[('UEFI', 'UEFI'), ('UEFI_CSM', 'UEFI-CSM'), ('GRUB', 'Grub')], default='UEFI', help_text='System boot method and architecture.', max_length=50, verbose_name='Boot Method'),
        ),
    ]
