"""
Remove unused NFS 'quiet' parameter

Revision ID: 1edf1b6b04db
Revises: 9a94fb8c0206
Create Date: 2023-08-21 17:11:31.864204+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1edf1b6b04db'
down_revision = '9a94fb8c0206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sharing_nfs_share', schema=None) as batch_op:
        batch_op.drop_column('nfs_quiet')

    # ### end Alembic commands ###


def downgrade():
    pass
