"""Remove system dataset syslog

Revision ID: b06ea181e7dd
Revises: 22a23dafd7de
Create Date: 2023-09-02 09:06:13.261715+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b06ea181e7dd'
down_revision = '22a23dafd7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_systemdataset', schema=None) as batch_op:
        batch_op.drop_column('sys_syslog_usedataset')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_systemdataset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sys_syslog_usedataset', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
