"""Remove TFTP

Revision ID: 2c0646015ca5
Revises: a70b230c1675
Create Date: 2023-05-21 12:12:50.254773+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '2c0646015ca5'
down_revision = 'a70b230c1675'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("DELETE FROM services_services WHERE srv_service = 'tftp'"))
    op.drop_table('services_tftp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_tftp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tftp_directory', sa.VARCHAR(length=255), nullable=False),
    sa.Column('tftp_newfiles', sa.BOOLEAN(), nullable=False),
    sa.Column('tftp_port', sa.INTEGER(), nullable=False),
    sa.Column('tftp_username', sa.VARCHAR(length=120), nullable=False),
    sa.Column('tftp_umask', sa.VARCHAR(length=120), nullable=False),
    sa.Column('tftp_options', sa.VARCHAR(length=120), nullable=False),
    sa.Column('tftp_host', sa.VARCHAR(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
