"""Remove ftp_tls_opt_no_cert_request

Revision ID: bd5cd1d802c7
Revises: bd11aee1c4b7
Create Date: 2023-06-27 17:15:14.561629+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd5cd1d802c7'
down_revision = 'bd11aee1c4b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ftp', schema=None) as batch_op:
        batch_op.drop_column('ftp_tls_opt_no_cert_request')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ftp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ftp_tls_opt_no_cert_request', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
