"""remove crash reporting

Revision ID: 3c011188cbe2
Revises: d2a26c29efca
Create Date: 2023-06-07 12:47:24.385652+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c011188cbe2'
down_revision = 'd2a26c29efca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('stg_crash_reporting')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stg_crash_reporting', sa.BOOLEAN(), nullable=True))

    # ### end Alembic commands ###
