# $FreeBSD$

PORTNAME=	s3transfer
PORTVERSION=	0.1.3
CATEGORIES=	devel python
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}
MAINTAINER=	wg@FreeBSD.org
COMMENT=	An Amazon S3 Transfer Manager

USES=		python
USE_GITHUB=	yes
USE_PYTHON=	autoplist distutils

GH_ACCOUNT=	boto

.include <bsd.port.mk>
