# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-25 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_cifs_vfsobjects_change_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifs_share',
            name='cifs_auxsmbconf',
            field=models.TextField(blank=True, help_text='These parameters are added to [Share] section of smb.conf', verbose_name='Auxiliary Parameters'),
        ),
    ]
