# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-10 17:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0008_aio_pthread_remove'),
        ('sharing', '0009_afp_share_afp_timemachine_quota_in_gib_instead_of_mib'),
    ]

    operations = [
    ]
