# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-02-12 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0011_aio_pthread_remove'),
        ('sharing', '0010_merge_20180110_1753'),
    ]

    operations = [
    ]
