# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-08 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0015_add_shadow_copy_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='afp_share',
            name='afp_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='cifs_share',
            name='cifs_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
        migrations.AddField(
            model_name='nfs_share',
            name='nfs_enabled',
            field=models.BooleanField(default=True, verbose_name='Enabled'),
        ),
    ]
