#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-collectd
# REQUIRE: var
# BEFORE: collectd

. /etc/rc.subr

generate_collectd()
{
    if [ -f "/data/rrd_dir.tar.bz2" ]; then
        if [ -d "/var/db" -a ! -d /var/db/collectd/rrd ]; then
            (cd /var/db && tar jxf /data/rrd_dir.tar.bz2)
        fi
    fi

    cfg="/usr/local/etc/collectd.conf"
    cat << EOF > $cfg
Hostname "localhost"
FQDNLookup true
BaseDir "/var/db/collectd"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/local/lib/collectd"

LoadPlugin aggregation
LoadPlugin cpu
LoadPlugin df
LoadPlugin disk
LoadPlugin interface
LoadPlugin load
LoadPlugin memory
LoadPlugin network
LoadPlugin processes
LoadPlugin rrdtool
LoadPlugin swap
LoadPlugin uptime

<Plugin "aggregation">
    <Aggregation>
        Plugin "cpu"
        Type "cpu"
        GroupBy "Host"
        GroupBy "TypeInstance"
        CalculateSum true
    </Aggregation>
</Plugin>

<Plugin "interface">
    Interface "lo0"
    Interface "plip0"
    Interface "/^usbus/"
    IgnoreSelected true
</Plugin>

<Plugin "disk">
    Disk "/^gptid/"
    Disk "/^md/"
    Disk "/^pass/"
    IgnoreSelected true
</Plugin>

<Plugin "rrdtool">
    DataDir "/var/db/collectd/rrd"
    CacheTimeout 120
    CacheFlush 900
</Plugin>

<Plugin "df">
EOF

    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT mp_path FROM storage_mountpoint m LEFT JOIN storage_volume v ON m.mp_volume_id=v.id WHERE m.mp_path LIKE '/%' AND v.vol_fstype != 'ZFS'" | sed -e 's,^,    Mountpoint ",g' -e 's,$,",g' >> ${cfg}
    for fs in `zfs list -t filesystem -o mountpoint -H`; do
        echo "    Mountpoint \"${fs}\"" >> ${cfg}
    done
echo '    IgnoreSelected false' >> ${cfg}
echo '</Plugin>' >> ${cfg}
}



name="ix-collectd"
start_cmd='generate_collectd'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
