#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kinit
# REQUIRE: kerberos
# REQUIRE: ix-samba
# REQUIRE: ntpd

. /etc/rc.freenas

kerberos_start()
{
	local res=1
	local pwfile
	local timeout=60

	if dirsrv_enabled activedirectory
	then
		AD_init

		local bindname="$(AD_get ad_bindname)"
		local bindpw="$(AD_get ad_bindpw)"
		local domainname="$(AD_get ad_domainname)"
		local use_keytab=$(AD_get ad_use_keytab)
		local keytab="$(AD_get ad_keytab)"

		if [ "${use_keytab}" = "1" -a -f "${keytab}" ]
		then
			local res=0
			local principals

			domainname="$(echo "${domainname}" | tr a-z A-Z)"

			principals="$(ktutil -k "${keytab}" list |tail +4|awk '{ print $3 }')"
			for p in ${principals}
			do
				AD_log "kerberos_start: kinit --renewable -t ${keytab} -k ${p}"
				kinit -t "${keytab}" --renewable -k "${p}"
				if [ "$?" != "0" ]
				then
					res=1
					break
				fi
				res=0
			done

			local ok="Failed"
			if [ "${res}" = "0" ]
			then
				ok="Successful"
			fi

			AD_log "kerberos_start: ${ok}"
			rm -f "${pwfile}"
			sleep 10

		elif [ -n "${bindname}" -a -n "${domainname}" -a -n "${bindpw}" ]
		then
			domainname="$(echo "${domainname}" | tr a-z A-Z)"

			pwfile="$(mktemp /tmp/tmp.XXXXXXXX)"
			echo -n "${bindpw}" > ${pwfile}

			AD_log "kerberos_start: /usr/bin/kinit --renewable " \
				"--password-file=${pwfile} ${bindname}@${domainname}"
			__AD_tc ${timeout} /usr/bin/kinit --renewable \
				--password-file="${pwfile}" "${bindname}@${domainname}"
			res=$?

			local ok="Failed"
			if [ "${res}" = "0" ]
			then
				ok="Successful"
			fi

			AD_log "kerberos_start: ${ok}"
			rm -f "${pwfile}"
			sleep 10
		fi
	fi

	return ${res}
}

kerberos_status()
{
	local res=1

	if dirsrv_enabled activedirectory
	then
		AD_init

		local domainname=$(AD_get ad_domainname)
		local bindname=$(AD_get ad_bindname)
		local bindpw=$(AD_get ad_bindpw)

		if [ -n "${bindname}" -a -n "${domainname}" -a -n "${bindpw}" ]
		then
			domainname=$(echo "${domainname}"|tr a-z A-Z)

			AD_log "kerberos_status: klist -t"
			klist -t
			res=$?

			local ok="Failed"
			if [ "${res}" = "0" ]
			then
				ok="Successful"
			fi

			AD_log "kerberos_status: ${ok}"
		fi
	fi

	return ${res}
}

kerberos_stop()
{
	kdestroy
}

kerberos_renew()
{
	if dirsrv_enabled activedirectory
	then
		kinit -R
	fi
}

name="ix-kinit"
start_cmd='kerberos_start'
status_cmd='kerberos_status'
stop_cmd='kerberos_stop'
renew_cmd="kerberos_renew"
extra_commands="renew"

load_rc_config $name
run_rc_command "$1"
