#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kinit
# REQUIRE: kerberos
# REQUIRE: ix-samba
# REQUIRE: ntpd

. /etc/rc.freenas
. /etc/directoryservice/rc.ActiveDirectory

kerberos_start()
{
	local res=1
	local pwfile
	local timeout=30

	if dirsrv_enabled activedirectory
	then
		AD_init

		local domainname=$(AD_get ad_domainname)
		local adminname=$(AD_get ad_adminname)
		local adminpw=$(AD_get ad_adminpw)

		if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
		then
			domainname=$(echo "${domainname}" | tr a-z A-Z)

			pwfile=$(mktemp /tmp/tmp.XXXXXXXX)
			echo -n "${adminpw}" > ${pwfile}

			AD_log "kerberos_start: /usr/bin/kinit --password-file=${pwfile} " \
			    "${adminname}@${domainname}"
			__AD_tc ${timeout} /usr/bin/kinit --password-file="${pwfile}" \
			    "${adminname}@${domainname}"
			res=$?

			local ok="Failed"
			if [ "${res}" = "0" ]
			then
				ok="Successful"
			fi

			AD_log "kerberos_start: ${ok}"
			rm -f "${pwfile}"
			sleep 10
		fi
	fi

	return ${res}
}

kerberos_status()
{
	local res=1

	if dirsrv_enabled activedirectory
	then
		AD_init

		local domainname=$(AD_get ad_domainname)
		local adminname=$(AD_get ad_adminname)
		local adminpw=$(AD_get ad_adminpw)

		if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
		then
			domainname=$(echo "${domainname}"|tr a-z A-Z)

			AD_log "kerberos_status: klist -l | grep -q ^${adminname}@${domainname}"
			klist -l | grep -q "^${adminname}@${domainname}"
			res=$?

			local ok="Failed"
			if [ "${res}" = "0" ]
			then
				ok="Successful"
			fi

			AD_log "kerberos_status: ${ok}"
		fi
	fi

	return ${res}
}

kerberos_stop()
{
	kdestroy
}

name="ix-kinit"
start_cmd='kerberos_start'
status_cmd='kerberos_status'
stop_cmd='kerberos_stop'

load_rc_config $name
run_rc_command "$1"
