#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nsswitch
# REQUIRE: nsswitch

. /etc/rc.freenas


generate_nsswitch_conf()
{
	/usr/local/libexec/nas/generate_nsswitch_conf.py
}

name="ix-nsswitch"
start_cmd='generate_nsswitch_conf'
stop_cmd='generate_nsswitch_conf'

load_rc_config $name
run_rc_command "$1"
