#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-system
# BEFORE: samba_server ix-syslogd

. /etc/rc.freenas

dataset_exists()
{
	local ds="${1}"

	if [ -z "${ds}" ]
	then
		return 1
	fi		

	/sbin/zfs list -H "${ds}" >/dev/null 2>&1
	if [ "$?" != "0" ]
	then
		return 1
	fi

	return 0
}

volume_is_zfs()
{
	local name="${1}"
	local fstype
	local res=1

	fstype="$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
		SELECT
			vol_fstype
		FROM
			storage_volume
		WHERE
			vol_name = '${name}'
		ORDER BY
			-id
		LIMIT 1
	")"

	if [ "${fstype}" = "ZFS" ]
	then
		res=0
	fi

	return ${res}
}

create_system_datasets_zfs()
{
	local system_dataset="${1}"
	local system_datasets="${2}"

	if ! dataset_exists "${system_dataset}"
	then
		/sbin/zfs create "${system_dataset}"
		if ! dataset_exists "${system_dataset}"
		then
			echo "Unable to create ${system_dataset}"
			exit 1
		fi
	fi

	for ds in ${system_datasets}
	do
		if dataset_exists "${system_dataset}/${ds}"
		then
			continue
		fi

		/sbin/zfs create "${system_dataset}/${ds}"
		if ! dataset_exists "${system_dataset}"
		then
			echo "Unable to create ${system_dataset}/${ds}"
			exit 1
		fi
		if [ "${ds}" = "cores" ]
		then
			local corepath="$(zfs list -H "${system_dataset}/cores"|awk '{ print $5 }')"
			if [ -n "${corepath}" ]
			then
				chmod 775 "${corepath}"
			fi
		fi
	done
}

create_system_datasets_ufs()
{
	local system_dataset="${1}"
	local system_datasets="${2}"

	system_dataset="/mnt/${system_dataset}"
	mkdir -p "${system_dataset}"
	if [ "$?" != "0" ]
	then
		echo "Unable to create ${system_dataset}"
		exit 1
	fi

	for ds in ${system_datasets}
	do
		mkdir -p "${system_dataset}/${ds}"
		if [ "$?" != "0" ]
		then
			echo "Unable to create ${system_dataset}/${ds}"
			exit 1
		fi
		if [ "${ds}" = "cores" ]
		then
			chmod 775 "${system_dataset}/cores"
		fi
	done
}

system_start()
{
	local system_datasets="samba4 syslog cores"

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_system_pool
	FROM
		system_advanced
	ORDER BY
		-id
	LIMIT 1
	" | \
	while read -r system_pool
	do
		local system_dataset="${system_pool}/.system"

		if volume_is_zfs "${system_pool}"
		then
			create_system_datasets_zfs "${system_dataset}" "${system_datasets}"
		else
			create_system_datasets_ufs "${system_dataset}" "${system_datasets}"
		fi

		sysctl kern.corefile="/mnt/${system_dataset}/cores/%N.core" >/dev/null
	done

	return 0
}

name="ix-system"
start_cmd='system_start'
stop_cmd=':'
status_cmd=':'
            
load_rc_config $name
run_rc_command $*
