#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-sssd
# REQUIRE: DAEMON
# BEFORE: sssd

. /etc/rc.freenas

generate_sssd_config()
{
	/usr/local/libexec/nas/generate_sssd_conf.py
}

name="ix-sssd"
start_cmd='generate_sssd_config'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
