#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ttys
# REQUIRE: root
# BEFORE: LOGIN

. /etc/rc.subr

netcli_enable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyv0.*)Pc(.*)\$,\1freenas\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyu0.*)std\.[0-9]+(.*)\$,\1freenas_serial${serspeed}\2," /etc/ttys > "${tmp}"
	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

netcli_disable()
{
	local tmp
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyv0.*)freenas(.*)\$,\1Pc\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyu0.*)freenas_serial[0-9]+(.*)\$,\1std.${serspeed}\2," /etc/ttys > "${tmp}"
	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

netcli_serial_enable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyu0.*)std\.[0-9]+(.*)\$,\1freenas_serial${serspeed}\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

netcli_serial_disable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")

	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyu0.*)freenas_serial\.[0-9]+(.*)\$,\1std.${serspeed}\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

serial_enable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local tmp
	tmp=$(mktemp /tmp/tmp.XXXXXX)

	sed -E -e "s,^(ttyu0.*)off(.*)\$,\1on\2," \
	       -e "s,^(ttyu0.*)dialup(.*)\$,\1vt100\2," \
	       -e "s,^(ttyu0.*)std\.[0-9]+(.*)\$,\1std.${serspeed}\2," \
		  /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

serial_disable()
{
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)

	sed -E -e "s,^(ttyu0.*)on(.*)\$,\1off\2," \
	       -e "s,^(ttyu0.*)vt100(.*)\$,\1dialup\2," \
		  /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

update_ttys()
{
	local IFS="|"
	local f="adv_consolemenu adv_serialconsole"
	eval local $f
	local sf=$(var_to_sf $f)

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		$sf

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1
	" | \
	while eval read $f
	do
		case "${adv_serialconsole}" in 
			0) serial_disable ;;
			1) serial_enable ;;
		esac

		case "${adv_consolemenu}" in
			0) netcli_disable; netcli_serial_disable ;;
			1) netcli_enable; netcli_serial_enable ;;
		esac
		kill -HUP 1
		break
	done
}

name="ix-ttys"
start_cmd='update_ttys'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
