#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ttys
# REQUIRE: root devfs
# BEFORE: LOGIN

. /etc/rc.subr

netcli_enable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyv0.*)Pc(.*)\$,\1freenas\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(sercons.*)std\.[0-9]+(.*)\$,\1freenas_serial${serspeed}\2," /etc/ttys > "${tmp}"
	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

netcli_disable()
{
	local tmp
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(ttyv0.*)freenas(.*)\$,\1Pc\2," /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi

	tmp=$(mktemp /tmp/tmp.XXXXXX)
	sed -E -e "s,^(sercons.*)freenas_serial[0-9]+(.*)\$,\1std.${serspeed}\2," /etc/ttys > "${tmp}"
	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
}

serial_enable()
{
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local tmp
	tmp=$(mktemp /tmp/tmp.XXXXXX)

	sed -E -e "s,^(sercons.*)off(.*)\$,\1on\2," \
		  /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi

	sercons=`conscontrol | grep Configured | cut -f 2 -d \  | tr , \\\\n | grep -vE 'ttyv[0-9]+' |head -n 1`
	if [ "${sercons}ZZZ" == "ZZZ" ] ; then
		sercons="ttyu0"
	fi

	ln -sf ${sercons} /dev/sercons
}

serial_disable()
{
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)

	sed -E -e "s,^(sercons.*)on(.*)\$,\1off\2," \
		  /etc/ttys > "${tmp}"

	if [ -s "${tmp}" ]; then
		mv "${tmp}" /etc/ttys
	else
		rm -f "$tmp"
	fi
	rm -f /dev/sercons
}

update_ttys()
{
	local IFS="|"
	local f="adv_consolemenu adv_serialconsole"
	eval local $f
	local sf=$(var_to_sf $f)

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		$sf

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1
	" | \
	while eval read $f
	do
		case "${adv_serialconsole}" in 
			0) serial_disable ;;
			1) serial_enable ;;
		esac

		case "${adv_consolemenu}" in
			0) netcli_disable ;;
			1) netcli_enable ;;
		esac
		kill -HUP 1
		break
	done
}

name="ix-ttys"
start_cmd='update_ttys'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
