#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-avahi
# BEFORE: avahi_daemon

. /etc/rc.subr

multi_service="/usr/local/etc/avahi/services/multi.service"

generate_config()
{

afp=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'afp'")
cifs=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'cifs'")
nfs=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'nfs'")
ssh=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'ssh'")
ftp=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'ftp'")
ftpport=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT ftp_port FROM services_ftp ORDER BY -id LIMIT 1")
rsync=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service = 'rsync'")
rsyncport=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT rsyncd_port FROM services_rsyncd ORDER BY -id LIMIT 1")
web=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT stg_guiprotocol FROM system_settings ORDER BY -id LIMIT 1")
http=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT stg_guiport FROM system_settings ORDER BY -id LIMIT 1")
if [ -z ${http} ]; then
	http="80"
fi

https=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT stg_guihttpsport FROM system_settings ORDER BY -id LIMIT 1")
if [ -z ${https} ]; then
	https="443"
fi

cat > "$multi_service" <<EOF
<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_device-info._tcp</type>
    <port>0</port>
    <txt-record>model=RackMac</txt-record>
  </service>
EOF

if [ $afp -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_afpovertcp._tcp</type>
    <port>548</port>
  </service>
EOF
fi

if [ $cifs -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
      <type>_smb._tcp</type>
      <port>445</port>
  </service>
EOF
fi

if [ $nfs -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_nfs._tcp</type>
    <port>2049</port>
EOF
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT path FROM sharing_nfs_share_path" | \
        while read -r path; do
            echo "    <txt-record>path=${path}</txt-record>" >> "$multi_service"
    	done
    echo "  </service>" >> "$multi_service"
fi

if [ $ssh -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_sftp-ssh._tcp</type>
    <port>22</port>
  </service>
  <service>
    <type>_ssh._tcp</type>
    <port>22</port>
  </service>
EOF
fi

if [ $web = "http" ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_http._tcp</type>
    <port>${http}</port>
  </service>
EOF
fi

if [ $web = "https" ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_https._tcp</type>
    <port>${https}</port>
  </service>
EOF
fi

if [ $web = "httphttps" ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_http._tcp</type>
    <port>${http}</port>
  </service>
  <service>
    <type>_https._tcp</type>
    <port>${https}</port>
  </service>
EOF
fi

if [ $ftp -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_ftp._tcp</type>
    <port>${ftpport}</port>
  </service>
EOF
fi

if [ $rsync -eq 1 ]; then
    cat >> "$multi_service" <<EOF
  <service>
    <type>_rsync._tcp</type>
    <port>${rsyncport}</port>
  </service>
EOF
fi

cat >> "$multi_service" <<EOF
</service-group>
EOF

}

name="ix_avahi"
start_cmd='generate_config'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
