#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix_pf_late
# REQUIRE: ix-smbpasswd ix-nfsd
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="ix_pf_late"
start_cmd="ix_pf_late_start"
stop_cmd="ix_pf_late_stop"
stop_cmd=":"


ix_pf_late_start()
{
	/sbin/ipfw -f flush
}

ix_pf_late_stop()
{
	/bin/sh /etc/ipfw.conf.block
}

run_rc_command "$1"
