<form data-dojo-type="dijit.form.Form" method="post">
    <script type="dojo/method" data-dojo-event="onSubmit" data-dojo-args="e">
    doSubmit({
        form: this,
        event: e,
        url: '/plugins/minidlna/index/edit',
    });
    </script>

<table>
    <?php echo $this->form ;?>
    <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>

    <tr>
        <td colspan="2">
            <button data-dojo-type="dijit.form.Button" type="submit"

                data-dojo-props="type:'submit'" class="submitform">
                OK
            </button>
            <button data-dojo-type="dijit.form.Button" type="button">
                Cancel
                <script type="dojo/method" data-dojo-event="onClick" data-dojo-args="evt">
                    cancelDialog(this);
                </script>
            </button>
        </td>
    </tr>


</table>


</form>
