from __future__ import annotations

from typing import TYPE_CHECKING, Any

from middlewared.api import Event, api_method
from middlewared.api.current import (
    TruecommandConfigChangedEvent,
    TruecommandEntry,
    TruecommandStatus,
    TruecommandUpdate,
    TruecommandUpdateArgs,
    TruecommandUpdateResult,
)
from middlewared.service import GenericConfigService, job, periodic, private

from .config import TruecommandConfigServicePart
from .portal import poll_api_for_status
from .state import set_status
from .wireguard import HEALTH_CHECK_SECONDS, health_check, start_truecommand_service, stop_truecommand_service

if TYPE_CHECKING:
    from middlewared.job import Job
    from middlewared.main import Middleware

__all__ = ('TruecommandService',)


class TruecommandService(GenericConfigService[TruecommandEntry]):

    class Config:
        cli_namespace = 'system.truecommand'
        entry = TruecommandEntry
        generic = True
        role_prefix = 'TRUECOMMAND'
        events = [
            Event(
                name='truecommand.config',
                description='Sent on TrueCommand configuration changes.',
                roles=['READONLY_ADMIN'],
                models={
                    'CHANGED': TruecommandConfigChangedEvent,
                },
            )
        ]

    def __init__(self, middleware: Middleware) -> None:
        super().__init__(middleware)
        self._svc_part = TruecommandConfigServicePart(self.context)

    @api_method(TruecommandUpdateArgs, TruecommandUpdateResult, check_annotations=True)
    async def do_update(self, data: TruecommandUpdate) -> TruecommandEntry:
        """
        Update Truecommand service settings.

        ``api_key`` is a valid API key generated by iX Portal.
        """
        return await self._svc_part.do_update(data)

    @private
    @job(lock='poll_ix_portal_api_truecommand', lock_queue_size=1)
    async def poll_api_for_status(self, job: Job) -> None:
        await poll_api_for_status(self.context, job)

    @private
    @periodic(HEALTH_CHECK_SECONDS, run_on_start=False)
    async def health_check(self) -> None:
        await health_check(self.context)

    @private
    async def start_truecommand_service(self) -> None:
        await start_truecommand_service(self.context)

    @private
    async def stop_truecommand_service(self) -> None:
        await stop_truecommand_service(self.context)

    @private
    async def set_status(self, new_status: str) -> None:
        await set_status(self.context, new_status)


async def _event_system_ready(middleware: Middleware, event_type: str, args: Any) -> None:
    if await middleware.call('failover.licensed'):
        return

    await middleware.call2(middleware.services.truecommand.start_truecommand_service)


async def setup(middleware: Middleware) -> None:
    await middleware.call('network.general.register_activity', 'truecommand', 'TrueCommand TrueNAS portal')

    await middleware.call2(middleware.services.truecommand.config)

    status = TruecommandStatus((await middleware.call('datastore.config', 'system.truecommand'))['api_key_state'])
    if status == TruecommandStatus.CONNECTED:
        status = TruecommandStatus.CONNECTING

    await middleware.call2(middleware.services.truecommand.set_status, status.value)

    middleware.event_subscribe('system.ready', _event_system_ready)
    if await middleware.call('system.ready'):
        if not await middleware.call('failover.licensed'):
            middleware.create_task(middleware.call2(middleware.services.truecommand.start_truecommand_service))
