# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-15 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_add_nslcd_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bsdusers',
            name='bsdusr_authenticator_credential',
            field=models.TextField(blank=True, default=None, editable=False, null=True),
        ),
    ]
