# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_add_pgsql_user'),
        ('account', '0008_migrate_legacy_values'),
    ]

    operations = [
    ]
