#############################################################################
# Makefile for building: pbi-manager
#############################################################################

####### Install

all:

install_doinstall:
	sh install.sh

install:  install_doinstall
