"""merge heads after backported 12.0 fix

Revision ID: 9c0795f22577
Revises: 3f06c8533cd3, 28ecea8be3fb
Create Date: 2020-08-11 14:36:46.817059+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0795f22577'
down_revision = ('3f06c8533cd3', '28ecea8be3fb')
branch_labels = None
depends_on = None
"""
This revision was auto-generated by running the command:
'alembic merge heads'
"""


def upgrade():
    pass


def downgrade():
    pass
