""" Add usepam column to SSH service

Revision ID: 3bc100abb47e
Revises: df19c1a8d4ae
Create Date: 2021-09-22 20:02:51.946059+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bc100abb47e'
down_revision = 'df19c1a8d4ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ssh', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ssh_usepam', sa.Boolean(), nullable=True))

    conn = op.get_bind()
    conn.execute("UPDATE services_ssh SET ssh_usepam = 1")

    with op.batch_alter_table('services_ssh', schema=None) as batch_op:
        batch_op.alter_column('ssh_usepam', existing_type=sa.BOOLEAN(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_ssh', schema=None) as batch_op:
        batch_op.drop_column('ssh_usepam')

    # ### end Alembic commands ###
