"""Remove UDP configuration option for NFS

Revision ID: 4c51b6b085a3
Revises: 334c69c59196
Create Date: 2023-12-18 17:48:41.974789+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c51b6b085a3'
down_revision = '334c69c59196'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_nfs', schema=None) as batch_op:
        batch_op.drop_column('nfs_srv_udp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_nfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nfs_srv_udp', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
