"""Add shadow fields

Revision ID: a270302ec08a
Revises: df1a322df40d
Create Date: 2023-12-12 20:25:28.004544+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a270302ec08a'
down_revision = 'df1a322df40d'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    with op.batch_alter_table('account_bsdusers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bsdusr_password_aging_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_password_change_required', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_last_password_change', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_min_password_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_max_password_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_password_warn_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_password_inactivity_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_account_expiration_date', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bsdusr_password_history', sa.Text(), nullable=True))

    conn.execute('UPDATE account_bsdusers SET bsdusr_password_aging_enabled = ?', False)
    conn.execute('UPDATE account_bsdusers SET bsdusr_password_change_required = ?', False)

    with op.batch_alter_table('account_bsdusers', schema=None) as batch_op:
        batch_op.alter_column('bsdusr_password_aging_enabled', existing_type=sa.Boolean(), nullable=False)
        batch_op.alter_column('bsdusr_password_change_required', existing_type=sa.Boolean(), nullable=False)



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account_bsdusers', schema=None) as batch_op:
        batch_op.drop_column('bsdusr_password_history')
        batch_op.drop_column('bsdusr_account_expiration_date')
        batch_op.drop_column('bsdusr_password_inactivity_period')
        batch_op.drop_column('bsdusr_password_warn_period')
        batch_op.drop_column('bsdusr_max_password_age')
        batch_op.drop_column('bsdusr_min_password_age')
        batch_op.drop_column('bsdusr_last_password_change')
        batch_op.drop_column('bsdusr_password_change_required')
        batch_op.drop_column('bsdusr_password_aging_enabled')

    # ### end Alembic commands ###
