"""Remove system birthday

Revision ID: 7c456c2a4926
Revises: 809e46a452e0
Create Date: 2024-01-23 10:38:31.580418+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c456c2a4926'
down_revision = '809e46a452e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_column('stg_birthday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stg_birthday', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
