# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields

from freenasUI import choices


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20170627_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='snmp',
            name='snmp_loglevel',
            field=models.IntegerField(choices=choices.SNMP_LOGLEVEL, default=3, verbose_name='Log Level'),
        ),
    ]
