# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-12 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields

from freenasUI import choices


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_auto_20170703_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nfs',
            name='nfs_srv_bindip',
            field=freenasUI.freeadmin.models.fields.MultiSelectField(blank=True, choices=choices.IPChoices(), help_text='Select the IP addresses to listen to for NFS requests. If left unchecked, NFS will listen on all available addresses.', max_length=250, verbose_name='Bind IP Addresses'),
        ),
    ]
