# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-11 07:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20170810_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cifs',
            name='cifs_srv_min_protocol',
            field=models.CharField(choices=[('CORE', 'CORE'), ('COREPLUS', 'COREPLUS'), ('LANMAN1', 'LANMAN1'), ('LANMAN2', 'LANMAN2'), ('NT1', 'NT1'), ('SMB2', 'SMB2'), ('SMB2_02', 'SMB2_02'), ('SMB2_10', 'SMB2_10'), ('SMB3', 'SMB3'), ('SMB3_00', 'SMB3_00'), ('SMB3_02', 'SMB3_02'), ('SMB3_11', 'SMB3_11')], default='LANMAN1', help_text='The minimum protocol version that will be supported by the server', max_length=120, verbose_name='Server minimum protocol'),
        ),
    ]
