# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-17 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_add_s3_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cifs',
            name='cifs_srv_max_protocol',
        ),
        migrations.RemoveField(
            model_name='cifs',
            name='cifs_srv_min_protocol',
        ),
    ]
