# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-09 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_add_asigra_model'),
        ('services', '0020_make_lunid_non_null'),
    ]

    operations = [
    ]
