# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-21 08:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_merge_20181109_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bsdusers',
            name='bsdusr_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
    ]
