from typing import Literal, Optional

from pydantic import Field

from middlewared.api.base import NQN, BaseModel, Excluded, ForUpdateMetaclass, NonEmptyString, excluded_field

__all__ = [
    "NVMetSubsysEntry",
    "NVMetSubsysCreateArgs",
    "NVMetSubsysCreateResult",
    "NVMetSubsysUpdateArgs",
    "NVMetSubsysUpdateResult",
    "NVMetSubsysDeleteArgs",
    "NVMetSubsysDeleteResult",
]


class NVMetSubsysEntry(BaseModel):
    id: int = Field(description="Unique identifier for the NVMe-oF subsystem.")
    name: NonEmptyString = Field(
        description=(
            "Human readable name for the subsystem.\n"
            "\n"
            "If `subnqn` is not provided on creation, then this name will be appended to the `basenqn` from "
            "`nvmet.global.config` to generate a subnqn."
        ),
    )
    subnqn: NonEmptyString | None = Field(
        default=None,
        description=(
            "NVMe Qualified Name (NQN) for the subsystem.\n"
            "\n"
            "If not provided during creation, will be auto-generated by appending the `name` to the `basenqn` from "
            "`nvmet.global.config`."
        ),
    )
    serial: str = Field(description="Serial number assigned to the subsystem.")
    allow_any_host: bool = Field(
        default=False,
        description="Any host can access the storage associated with this subsystem (i.e. no access control).",
    )
    pi_enable: bool | None = Field(
        default=None,
        description="Enable Protection Information (PI) for data integrity checking.",
    )
    qid_max: int | None = Field(default=None, description="Maximum number of queue IDs allowed for this subsystem.")
    ieee_oui: str | None = Field(default=None, description="IEEE Organizationally Unique Identifier for the subsystem.")
    ana: bool | None = Field(
        default=None,
        description=(
            "If set to either `True` or `False`, then *override* the global `ana` setting from `nvmet.global.config` "
            "for this subsystem only.\n"
            "\n"
            "If `null`, then the global `ana` setting will take effect."
        ),
    )
    hosts: Optional[list[int]] = Field(
        default=[],
        description=(
            "List of host ids which have access to this subsystem.\n"
            "\n"
            "Only populated on query if `extra.options.verbose` is set."
        ),
    )
    namespaces: Optional[list[int]] = Field(
        default=[],
        description=(
            "List of namespaces ids in this subsystem.\n"
            "\n"
            "Only populated on query if `extra.options.verbose` is set."
        ),
    )
    ports: Optional[list[int]] = Field(
        default=[],
        description=(
            "List of ports ids on which this subsystem is available.\n"
            "\n"
            "Only populated on query if `extra.options.verbose` is set."
        ),
    )


class NVMetSubsysCreate(NVMetSubsysEntry):
    id: Excluded = excluded_field()
    serial: Excluded = excluded_field()
    hosts: Excluded = excluded_field()
    namespaces: Excluded = excluded_field()
    ports: Excluded = excluded_field()
    subnqn: NQN | None = Field(
        default=None,
        description=(
            "NVMe Qualified Name (NQN) for the subsystem.\n"
            "\n"
            "Must be a valid NQN format if provided."
        ),
    )


class NVMetSubsysCreateArgs(BaseModel):
    nvmet_subsys_create: NVMetSubsysCreate = Field(
        description="Configuration data for creating a new NVMe-oF subsystem.",
    )


class NVMetSubsysCreateResult(BaseModel):
    result: NVMetSubsysEntry = Field(description="The newly created NVMe-oF subsystem configuration.")


class NVMetSubsysUpdate(NVMetSubsysCreate, metaclass=ForUpdateMetaclass):
    pass


class NVMetSubsysUpdateArgs(BaseModel):
    id: int = Field(description="ID of the subsystem to update.")
    nvmet_subsys_update: NVMetSubsysUpdate = Field(description="Updated configuration data for the NVMe-oF subsystem.")


class NVMetSubsysUpdateResult(BaseModel):
    result: NVMetSubsysEntry = Field(description="The updated NVMe-oF subsystem configuration.")


class NVMetSubsysDeleteOptions(BaseModel):
    force: bool = Field(
        default=False,
        description="Force subsystem deletion, even if currently associated with one or more namespaces or ports.",
    )


class NVMetSubsysDeleteArgs(BaseModel):
    id: int = Field(description="ID of the subsystem to delete.")
    options: NVMetSubsysDeleteOptions = Field(
        default_factory=NVMetSubsysDeleteOptions,
        description="Options for subsystem deletion behavior.",
    )


class NVMetSubsysDeleteResult(BaseModel):
    result: Literal[True] = Field(description="Indicates successful deletion of the subsystem.")
