# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 15:25
from __future__ import unicode_literals

from django.db import migrations


def remove_non_zfs(apps, schema_editor):
    Volume = apps.get_model('storage', 'Volume')
    Volume.objects.exclude(vol_fstype='ZFS').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_auto_20170525_1857'),
    ]

    operations = [
        migrations.RunPython(remove_non_zfs),
        migrations.RemoveField(
            model_name='volume',
            name='vol_fstype',
        ),
    ]
