# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_quotaexcess'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotaexcess',
            name='quota_type',
            field=models.CharField(default='quota', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotaexcess',
            name='dataset_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='quotaexcess',
            unique_together=set([('dataset_name', 'quota_type')]),
        ),
    ]
