# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_quota_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotaexcess',
            old_name='available',
            new_name='quota_value',
        ),
    ]
