# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-24 18:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0013_new_replication_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replication',
            old_name='repl_minute',
            new_name='repl_schedule_minute',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_hour',
            new_name='repl_schedule_hour',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_daymonth',
            new_name='repl_schedule_daymonth',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_month',
            new_name='repl_schedule_month',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_dayweek',
            new_name='repl_schedule_dayweek',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_begin',
            new_name='repl_schedule_begin',
        ),
        migrations.RenameField(
            model_name='replication',
            old_name='repl_end',
            new_name='repl_schedule_end',
        ),

        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_minute',
            field=models.CharField(default='00', help_text='Values allowed:<br>Slider: 0-30 (as it is every Nth minute).<br>Specific Minute: 0-59.', max_length=100, null=True, verbose_name='Minute'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_hour',
            field=models.CharField(default='*', help_text='Values allowed:<br>Slider: 0-12 (as it is every Nth hour).<br>Specific Hour: 0-23.', max_length=100, null=True, verbose_name='Hour'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_daymonth',
            field=models.CharField(default='*', help_text='Values allowed:<br>Slider: 0-15 (as its is every Nth day).<br>Specific Day: 1-31.', max_length=100, null=True, verbose_name='Day of month'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_month',
            field=models.CharField(default='*', max_length=100, null=True, verbose_name='Month'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_dayweek',
            field=models.CharField(default='*', max_length=100, null=True, verbose_name='Day of week'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_begin',
            field=models.TimeField(default=datetime.time(0, 0), help_text='Do not start replication before', null=True, verbose_name='Begin'),
        ),
        migrations.AlterField(
            model_name='replication',
            name='repl_schedule_end',
            field=models.TimeField(default=datetime.time(23, 59), help_text='Do not start replication after', null=True, verbose_name='End'),
        ),
    ]
