# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-04-02 09:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0019_auto_20190320_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_allow_empty',
            field=models.BooleanField(default=True, verbose_name='Allow taking empty snapshots'),
        ),
    ]
