#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin::/usr/local/sbin:/usr/local/bin

pre-install()
{
}

post-install()
{
        set -x -e 
        local dstCR
        dstCR=/usr/local/www/freenasUI
	echo "Adding freenas web gui"
	echo "Making freenas initial database"
        if [ ! -d /data ]; then
		rm -fr /data
		mkdir -p /data
	fi
        cd ${dstCR}
	python manage.py syncdb --noinput --migrate --traceback
        python manage.py collectstatic --noinput
        python tools/compilemsgs.py
        cd /data
	cp freenas-v1.db factory-v1.db
	chown -R www:www /data
}

backupwarning()
{
}




case $2 in
PRE-INSTALL)
	pre-install
	exit 0
        ;;
POST-INSTALL)
	post-install
	exit 0
	;;
BACKUPWARNING)
	backupwarning
	exit 0
	;;
*)
	exit 1
	;;
esac
