#!/usr/bin/python3

user = "root"
password = "Xenon*Jnk5"
netmask = "172.31.200.128"
gateway = "172.31.200.129"
vip = ""
vm_name = None
hostname = "testAUTOGENERATED"
domain = "testAUTOGENERATED.nb.ixsystems.net"
api_url = 'http://172.31.200.1/api/v2.0'
interface = "eth0"
badNtpServer = "10.20.20.122"
localHome = "/root"
keyPath = "/root/.ssh/test_id_rsa"
pool_name = "tank"
ha_pool_name = "ha"
ha = False
ha_license = ''
update = False
artifacts = "/root/freenas/freenas/tests/artifacts/"
isns_ip = "10.234.24.50"
extended_tests = False
sshKey = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC test@reference"
