#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: etcfs
# REQUIRE: datastore

name="etcfs"
start_cmd="etcfs_start"
stop_cmd="etcfs_stop"
status_cmd=":"

. /etc/rc.subr

etcfs_start()
{
    mkdir -p /var/run/etcfs
    /usr/local/sbin/mount_etcfs ${etcfs_flags} -o /var/empty /var/run/tmpfs
    mount_unionfs -o below /var/run/etcfs /etc
}

etcfs_stop()
{
    umount -f /etc
    umount -f /var/run/etcfs
    rmdir /var/run/etcfs
}

load_rc_config $name
run_rc_command $*