#!/bin/sh

. /etc/rc.freenas

service=/usr/sbin/service
pwdstr='+:::::::::'
grpstr='+:*::'
hostsstr='+::'


nisctl_cmd()
{
	local args="$*"

	if [ -n "${args}" ]
	then
		logger -t NIS "${args}"
		${args}
		return $?	
	fi		

	return 0
}

nisctl_start()
{
	echo "${pwdstr}" >> /etc/master.passwd
	pwd_mkdb -p /etc/master.passwd

	echo "${grpstr}" >> /etc/group

	echo nis >> /etc/host.conf
	echo "${hostsstr}" >> /etc/hosts

	if ! nisctl_cmd /etc/rc.d/ix-nsswitch start
	then
		nisctl_cmd /etc/rc.d/ix-passwd start
		return 1
	fi

	if ! nisctl_cmd /etc/rc.d/nisdomain start
	then
		nisctl_cmd /etc/rc.d/ix-passwd start
		return 1
	fi

	if ! nisctl_cmd /etc/rc.d/ypbind start
	then
		nisctl_cmd /etc/rc.d/ix-passwd start
		return 1
	fi

	srv_set directoryservice 1
	return 0
}

nisctl_stop()
{
	tmphostconf="$(mktemp /tmp/.XXXXXX)"

	nisctl_cmd /etc/rc.d/ypbind stop
	nisctl_cmd /etc/rc.d/nisdomain stop
	nisctl_cmd  /etc/rc.d/ix-nsswitch stop

	grep -v '^nis' /etc/host.conf > "${tmphostconf}"
	mv "${tmphostconf}" /etc/host.conf
	chmod 644 /etc/host.conf

	nisctl_cmd /etc/rc.d/ix-hostname start
	nisctl_cmd /etc/rc.d/ix-passwd start

	srv_set directoryservice 0
	. /etc/rc.conf.local
}

nisctl_status()
{
	nisctl_cmd ${service} ix-nis status
}

name="nisctl"
start_cmd='nisctl_start'
status_cmd='nisctl_status'
stop_cmd='nisctl_stop'

load_rc_config $name
run_rc_command "$1"
