#!/bin/sh -ex

mkdir -p /var/trash
for file in \
    /etc/cron.d/certbot \
    /etc/cron.d/e2scrub_all \
    /etc/cron.d/mdadm \
    /etc/cron.d/sysstat \
    /etc/cron.daily/apt-compat \
    /etc/cron.daily/calendar \
    /etc/cron.daily/exim4-base \
    /etc/cron.daily/dpkg \
    /etc/cron.daily/mdadm \
    /etc/cron.daily/man-db \
    /etc/cron.daily/sysstat \
    /etc/cron.weekly/man-db \
    /etc/grub.d/10_linux \
    /etc/grub.d/30_os-prober \
    /etc/logrotate.d/syslog-ng
do
    dpkg-divert --add --package truenas --rename --divert "/var/trash/$(echo "$file" | sed "s/\//_/g")" "$file"
done

# openssh-server explicitly sets itself to enabled on post install, so preset is not respected
# we need to manually disable it

systemctl disable ssh.service

# Services whose unit files are created with systemd-sysv-generator do not respect preset file so for now
# we disable them explicitly

systemctl disable scst
systemctl disable proftpd
systemctl disable nmbd
systemctl disable smbd
systemctl disable winbind
systemctl disable wsdd
systemctl disable walinuxagent
systemctl disable openipmi
systemctl disable nfs-server
systemctl disable rpcbind

# These services will be started from middleware as needed
systemctl disable ix-nvmf
systemctl disable truenas-webshare-auth
systemctl disable truesearch

# NAS-123024: disable proftpd.socket, if it starts it will block proftpd.service
# proftpd.socket is used in conjunction with xinetd
# NOTE: This should be reviewed on next update where the startup issue is fixed via a new systemd unit file.
systemctl disable proftpd.socket

# Update alternatives
update-alternatives --install "/usr/bin/vim" vim.tiny "/usr/bin/vim.tiny" "10"

# Add nut to dialout group - NAS-110578
usermod -a -G dialout nut
# Usbhid-ups driver does not start and needs nut as the group for it's executable to correctly execute NAS-113642
chown root:nut /lib/nut/usbhid-ups

# Copy to /conf/base
for bit in /etc/aliases /etc/group /etc/passwd /etc/syslog-ng/syslog-ng.conf /etc/ssl/openssl.cnf; do
    mkdir -p "$(dirname "/conf/base/$bit")"
    cp -aR "$bit" "/conf/base/$bit"
done

#DEBHELPER#

# Following service(s) are not respecting vendor preset file so we enable them explicitly
systemctl daemon-reload
systemctl enable zfs-zed
systemctl enable syslog-ng

# We need to mask certain services so that they don't start automatically
systemctl mask libvirtd.socket libvirtd-ro.socket libvirtd-admin.socket libvirtd-tls.socket libvirtd-tcp.socket
systemctl mask exim4-base.service exim4.service exim4-base.timer
systemctl mask uuidd.service uuidd.socket
systemctl mask ndctl-monitor.service
# Prevent `apt.systemd.daily[3756924]: /usr/lib/apt/apt.systemd.daily: 325: apt-config: Permission denied`
systemctl mask apt-daily.timer apt-daily-upgrade.timer

# mdmonitor.service in particular causes mdadm to send emails to the MAILADDR line
# in /etc/mdadm/mdadm.conf. By default, that's the root account, so end-users are
# getting unnecessary emails about these devices. Since middlewared service is
# solely responsible for managing md devices there is no reason to run this monitor
# service. This prevents unnecessary emails from being sent out.
systemctl mask mdadm.service mdmonitor.service

# We don't use LVM and this service can add significant boot delays
# on large disk systems
systemctl mask lvm2-monitor.service

# ipa-epn.service is in conflict with our implementation of support for IPA
systemctl mask ipa-epn.service

# Prevent systemd management of users and accounts: NAS-137910
systemctl mask systemd-sysusers.servics

systemctl set-default truenas.target

sed -i.bak 's/CHARMAP="ISO-8859-15"/CHARMAP="UTF-8"/' /etc/default/console-setup
