#!/bin/sh

# It unconfigures interfaces we've just configured even if it is instructed to do not touch anything
systemctl disable systemd-networkd
# We want middlewared to import pools
systemctl disable zfs-mount
systemctl disable zfs-volume-wait
systemctl disable zfs-import-cache
systemctl disable zfs-import-scan
#DEBHELPER#
