"""Remove alerts with incompatible args format

Revision ID: aa197df8684c
Revises: 3fc58b28ce77
Create Date: 2026-03-15 02:40:00.000000+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa197df8684c'
down_revision = '3fc58b28ce77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The "Full alerts mypy" refactor (3e2fd05b36) moved fields that were previously
    # stored in the `key` column into required dataclass fields in `args`.
    # Pre-existing alerts have the old args format and crash on deserialization.
    # These alerts are ephemeral and will be regenerated by their alert sources.
    op.execute(
        "DELETE FROM system_alert WHERE klass IN "
        "('ReplicationSuccess', 'ReplicationFailed', 'SnapshotFailed', "
        "'IPMISEL', 'QuotaWarning', 'QuotaCritical')"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
