# $FreeBSD$

PORTNAME=	tqdm
PORTVERSION=	4.11.2
DISTVERSIONPREFIX=	v
CATEGORIES=	misc
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	neel@neelc.org
COMMENT=	Fast, extensible progress bar for Python

LICENSE=	MIT

USE_GITHUB=	yes

USES=		python
USE_PYTHON=	autoplist distutils
NO_ARCH=	yes

.include <bsd.port.mk>
