# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-23 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('network', '0003_lagg_no_mtu')
    ]

    operations = [
        migrations.AddField(
            model_name='GlobalConfiguration',
            name='gc_domains',
            field=models.TextField(
                max_length=256,
                verbose_name="Additional domains",
                default='',
                blank=True,
                help_text="Delimit domains by spaces."
            )
        ),
]