# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_lagg_no_mtu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lagginterfacemembers',
            name='lagg_deviceoptions',
            field=models.CharField(default='up', max_length=120, verbose_name='Options'),
        ),
    ]
