# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-13 13:00
from __future__ import unicode_literals

from django.db import migrations, models

from freenasUI import choices


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20170703_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='vlan',
            name='vlan_pcp',
            field=models.PositiveIntegerField(blank=True, choices=choices.VLAN_PCP_CHOICES, help_text='3-bit field which refers to IEEE 802.1p class of service andmaps to the frame priority level.', null=True, verbose_name='Priority Code Point'),
        ),
    ]
