# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 16:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_globalconfiguration_gc_domains'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='gc_hostname_virtual',
            field=models.CharField(blank=True, max_length=120, null=True, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z\\.\\-\\_0-9]+$')], verbose_name='Hostname (Virtual)'),
        ),
    ]
