# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 10:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_globalconfiguration_gc_hostname_virtual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interfaces',
            name='int_vhid',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(255)], verbose_name='Virtual Host ID'),
        ),
    ]
