# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-09-03 13:29
from __future__ import unicode_literals

import re
from django.db import migrations, models


RE_MTU = re.compile(r'(?P<before>.*)\bmtu (?P<mtu>\d+)\b(?P<after>.*)')


def move_mtu_from_options(apps, schema_editor):
    Interfaces = apps.get_model('network', 'interfaces')

    for i in Interfaces.objects.all():
        if not i.int_options:
            continue
        reg = RE_MTU.search(i.int_options)
        if not reg:
            continue
        i.int_mtu = int(reg.group('mtu'))
        i.int_options = re.sub(r'\s{2,}', r' ', f'{reg.group("before")}{reg.group("after")}')
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20171121_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaces',
            name='int_mtu',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='MTU'),
        ),
        migrations.RunPython(move_mtu_from_options, reverse_code=migrations.RunPython.noop),
    ]
