# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 11:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_move_options_and_mtu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('members', freenasUI.freeadmin.models.fields.ListField(default=[], verbose_name='Members')),
                ('interface', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='network.Interfaces', verbose_name='Interface')),
            ],
            options={
                'verbose_name': 'Bridge',
                'verbose_name_plural': 'Bridges',
                'ordering': ['interface'],
            },
        ),
    ]
