# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-18 16:31
from __future__ import unicode_literals

import django.core.validators
import freenasUI
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20181114_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='gc_service_advertisement',
            field=freenasUI.freeadmin.models.fields.MultiSelectField(
                blank=True,
                max_length=255,
                null=True,
                default="MDNS,NETBIOS",
                verbose_name='Service Advertisement Methods'
            ),
        ),
    ]
