"""NVIDIA

Revision ID: 5654da8713d1
Revises: 4b0b7ba46e63
Create Date: 2024-08-12 08:09:19.248327+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5654da8713d1'
down_revision = '4b0b7ba46e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_docker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nvidia', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_docker', schema=None) as batch_op:
        batch_op.drop_column('nvidia')

    # ### end Alembic commands ###
