#!/bin/sh -ex

mkdir -p /var/trash
for file in \
    /etc/apparmor.d/libvirt/TEMPLATE.qemu \
    /etc/nsswitch.conf \
    /etc/zsh/zshenv \
    /usr/lib/netdata/conf.d/python.d.conf \
    /usr/lib/netdata/conf.d/charts.d.conf \
    /usr/share/spice-html5/spice_auto.html \
    /usr/share/spice-html5/spice.css \
    /etc/logrotate.d/netdata \
    /etc/logrotate.d/nginx \
    /usr/lib/tmpfiles.d/nut-server.conf \
    /usr/lib/tmpfiles.d/nut-client.conf \
    /usr/lib/tmpfiles.d/nut-common.tmpfiles
do
    dpkg-divert --add --package truenas-files --rename --divert "/var/trash/$(echo "$file" | sed "s/\//_/g")" "$file"
done
