.Dd May 12, 2010
.Dt PBI_UPDATE 1
.Os
.Sh NAME
.Nm pbi_update
.Nd Check for and perform updates of PBIs
.Sh SYNOPSIS
.Nm
.Op Fl c
.Op Fl -check-all
.Op Fl -disable-auto
.Op Fl -enable-auto
.Op Fl u
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
allows the user to check for updates from PBI update servers, and perform upgrades
of PBI packaged applications. 
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl c
Check-only of the specified PBI for available updates.
.It Fl -check-all
Run a full check of all installed PBIs, and display list of available updates.
.It Fl -disable-auto
Disable auto-updating of the target PBI
.It Fl -enable-auto
Enable auto-updating of the target PBI. Will only auto-update if the PBI is associated with a valid repository. 
.It Fl -update-all
Update all installed PBIs to the latest versions available.
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_delete 1
