.Dd SEPT 17, 2010
.Dt PBI_ICON 1
.Os
.Sh NAME
.Nm pbi_icon
.Nd Interacts with a PBIs icon / mime settings
.Sh SYNOPSIS
.Nm
.Op add-desktop 
.Op add-menu
.Op add-mime
.Op add-pathlnk
.Op del-desktop
.Op del-menu
.Op del-mime
.Op del-pathlnk
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
is used to manually add/remove desktop icons, menu entries, and mime registration for
PBIs installed on the system. Note: Not all applications will have desktop/menu/mime data.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It add-desktop
Installs any XDG compliant desktop icons, should be run as user.
.It add-mime
Installs any XDG compliant mime information, should be run as root.
.It add-menu
Installs any XDG compliant menu icons, should be run as root.
.It add-pathlnk
Installs any PATH links to ~/bin as user, or to LOCALBASE as root.
.It del-desktop
Removes any XDG compliant desktop icons, should be run as user.
.It del-menu
Removes any XDG compliant menu icons, should be run as root.
.It del-mime
Removes any XDG compliant mime information, should be run as root.
.It del-pathlnk
Removes any PATH links from ~/bin as user, or LOCALBASE as root.
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_info 1 ,
.Xr pbi_delete 1
