.Dd Apr 27, 2010
.Dt PBI_INFO 1
.Os
.Sh NAME
.Nm pbi_info
.Nd Lists information about PBIs
.Sh SYNOPSIS
.Nm
.Op Fl a
.Op Fl i
.Op Fl v
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
is used provide a listing of PBIs installed on the system, along with
details about these applications.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl a
List all PBIs installed on the system, same as running pbi_info without an argument. 
.It Fl i
List all available PBIs from any repo index files
.It Fl v
Enable verbose output
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_delete 1
