.Dd Apr 15, 2010
.Dt PBI_DELETE 1
.Os
.Sh NAME
.Nm pbi_delete
.Nd Removes an installed PBI
.Sh SYNOPSIS
.Nm
.Op Fl v
.Op Fl -clean-hdir
.Op Ar pbi
.Sh DESCRIPTION
The utility,
.Nm ,
is used to remove an installed PBI file from the system.
.Pp
.Sh OPTIONS
.Bl -tag -width indent
.It Fl v
Enable verbose output
.It Fl -clean-hdir
Perform a full cleaning of the shared-hash dir, removing any unused files. This
is normally handled by the pbid daemon, and only needs to be run if pbid is disabled.
.El
.Sh SEE ALSO
.Xr pbi_add 1 ,
.Xr pbi_create 1 ,
.Xr pbi_makeport 1
