#!/bin/sh
#
# $FreeBSD$
#
#

# PROVIDE: ix-autotune
# REQUIRE: middlewared
# BEFORE: NETWORKING

. /etc/rc.freenas

do_autotune()
{
	local rv
	/usr/local/bin/midclt call system.advanced.autotune sysctl > /dev/null
	rv=$(/usr/local/bin/midclt call system.advanced.autotune loader)
	return ${rv}
}

autotune()
{
	do_autotune
	local res=$?

	if [ ${res} -eq 2 ]
	then
		debug "Rebooting server after applying loader.conf changes."
		echo "Rebooting server after applying loader.conf changes."
		shutdown -r now
	fi
}

name="ix-autotune"
start_cmd='autotune'
run_rc_command "$1"
