#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ataidle
# REQUIRE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

ataidle_start()
{
	/usr/local/bin/midclt call disk.configure_power_management > /dev/null
}

name="ix-ataidle"
rcvar="ataidle_enable"
start_cmd="ataidle_start"
stop_cmd=':'

load_rc_config $name
run_rc_command "${cmd}"
