#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ctld
# REQUIRE: FILESYSTEMS
# BEFORE: ctld

. /etc/rc.subr

generate_ctl()
{
	/usr/local/libexec/nas/generate_ctl_conf.py
}

name="ix-ctld"
rcvar="ctld_enable"
start_precmd='check_service'
start_cmd='generate_ctl'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
