#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-chelsio
# BEFORE: NETWORKING

. /etc/rc.subr

set_sysctl()
{
if sysctl dev.cxl > /dev/null 2>&1 ; then
	for i in `jot 8 0 7 1`
	do	
		sysctl dev.cxl.$i.holdoff_tmr_idx=3 > /dev/null 2>&1
	done
fi
}

name="ix-chelsio"
start_cmd='set_sysctl'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
