#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-inadyn
# BEFORE: inadynmt

. /etc/rc.subr

generate_inadyn_real()
{
	local IFS="|"

	local f="id ddns_provider ddns_ipserver ddns_domain ddns_username ddns_password ddns_updateperiod ddns_fupdateperiod"
	eval local $f
	local sf=$(var_to_sf $f)
	${FREENAS_SQLITE_CMD} ${RO_FREENAS_CONFIG} \
		"SELECT $sf FROM services_dynamicdns ORDER BY -id LIMIT 1" | \
	while eval read -r $f; do
		if [ -n "${ddns_provider}" ]; then
			echo -n "--dyndns_system ${ddns_provider} "
		fi
		if [ -n "${ddns_ipserver}" ]; then
			echo -n "--ip_server_name ${ddns_ipserver} "
		fi
		if [ -n "${ddns_updateperiod}" ]; then
			echo -n "--update_period_sec ${ddns_updateperiod} "
		fi
		if [ -n "${ddns_fupdateperiod}" ]; then
			echo -n "--forced_update_period ${ddns_fupdateperiod} "
		fi
		ddns_options=`${FREENAS_SQLITE_CMD} ${RO_FREENAS_CONFIG} "SELECT ddns_options FROM services_dynamicdns WHERE id=${id}"`
		if [ -n "${ddns_options}" ]; then
			echo -n "${ddns_options} "
		fi
		# hash and backslash must be escaped
		ddns_password=$(/usr/local/bin/midclt call notifier.pwenc_decrypt "${ddns_password}"|sed -e 's/\\/\\\\/g' -e 's/#/\\#/g')
		ddns_username=$(echo ${ddns_username}|sed -e 's/\\/\\\\/g' -e 's/#/\\#/g')
		ddns_domain=`echo $ddns_domain | awk 'BEGIN { FS=",?[ \t]*"; OFS=" --alias "; } { $1=$1; print $0; }'`
                ddns_domain=`echo $ddns_domain | awk 'BEGIN { FS="#"; OFS=","; } { $1=$1; print $0; }'`
		echo "--background --syslog --username ${ddns_username} --password ${ddns_password} --alias ${ddns_domain}"
	done
}

generate_inadyn()
{
	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT
	generate_inadyn_real > /usr/local/etc/inadyn-mt.conf
}

name="ix-inadyn"
start_cmd='generate_inadyn'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
