#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kerberos
# BEFORE: kerberos

. /etc/rc.freenas

generate_krb5_conf()
{
	/usr/local/libexec/nas/generate_krb5_conf.py
}

name="ix-kerberos"
start_cmd='generate_krb5_conf'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
