#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kerberos
# BEFORE: kdc

. /etc/rc.freenas

generate_kerberos_files()
{
         LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call etc.generate kerberos > /dev/null
}

name="ix-kerberos"
start_cmd='generate_kerberos_files'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
