#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-loader
# BEFORE: FILESYSTEMS
# REQUIRE: ix-update

. /etc/rc.freenas

generate_loader_confs()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call etc.generate loader
}

name="ix-loader"
start_cmd='generate_loader_confs'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
