#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-multipath
# REQUIRE: FILESYSTEMS ix-syncdisks

. /etc/rc.subr

multipath_sync()
{
	SENTINEL="/var/tmp/.multipath"
	if ! [ -f ${SENTINEL} ]; then
		touch ${SENTINEL}
		echo "Starting ${name}."
		LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python \
			/usr/local/www/freenasUI/middleware/notifier.py \
			multipath_sync \
			>/dev/null
	else
		ret=$(find /var/tmp -name .multipath -maxdepth 1 -mtime 600s | wc -l | tr -d '[[:space:]]')
		if [ ${ret} == "0"; then
			touch ${SENTINEL}
			echo "Starting ${name}."
			LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/python \
				/usr/local/www/freenasUI/middleware/notifier.py \
				multipath_sync \
				>/dev/null
		else
			exit 1
		fi
	fi

}

name="ix-multipath"
start_cmd='multipath_sync'
stop_cmd=''

load_rc_config $name
run_rc_command "$1"
