#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nsswitch
# REQUIRE: nsswitch

. /etc/rc.freenas


generate_nsswitch_start()
{
	/usr/local/libexec/nas/generate_nsswitch_conf.py start
}

generate_nsswitch_stop()
{
	/usr/local/libexec/nas/generate_nsswitch_conf.py stop
}

name="ix-nsswitch"
start_cmd='generate_nsswitch_start'
stop_cmd='generate_nsswitch_stop'

load_rc_config $name
run_rc_command "$1"
