#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nsswitch
# BEFORE: nsswitch
# REQUIRE: resolv

. /etc/rc.freenas


generate_nsswitch_start()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/libexec/nas/generate_nsswitch_conf.py start
}

generate_nsswitch_stop()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/libexec/nas/generate_nsswitch_conf.py stop
}

name="ix-nsswitch"
start_cmd='generate_nsswitch_start'
stop_cmd='generate_nsswitch_stop'

load_rc_config $name
run_rc_command "$1"
