#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nfsbind
# BEFORE: mountd gssd nfsuserd nfsd


nfs_bindip() {
	# We need to make sure the NFS bind IP exists
	# and that can't happen until network starts.
	# Since nfs flags goes in rc.conf.local we need to regenerate it.
	/usr/local/bin/midclt call etc.generate rc > /dev/null
}

name="ix-nfsbind"
start_cmd='nfs_bindip'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
