#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-preinit
# REQUIRE: FILESYSTEMS
# BEFORE: SERVERS

. /etc/rc.subr

execute_task()
{
	local stype=$1
	local f="ini_$stype"
	eval local $f
	local sf=$(var_to_sf $f)

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM tasks_initshutdown WHERE ini_when = 'preinit' AND ini_enabled = 1 AND ini_type = '$stype' ORDER BY id" | \
	while eval read -r $f; do
		if [ "${stype}" = "command" ]; then
			sh -c "${ini_command}" < /dev/null
		else
			if [ -e "${ini_script}" ]; then
				sh -c "exec ${ini_script}" < /dev/null
			fi
		fi
	done
}

do_preinit()
{
	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT

	execute_task "command"
	execute_task "script"
}

name="ix-preinit"
start_cmd='do_preinit'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
