#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-preinit
# REQUIRE: FILESYSTEMS
# BEFORE: SERVERS

. /etc/rc.subr

do_preinit()
{
	/usr/local/bin/midclt call initshutdownscript.execute_init_tasks PREINIT > /dev/null
}

name="ix-preinit"
start_cmd='do_preinit'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
