#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-pam
# REQUIRE: root resolv
# BEFORE: NETWORK

. /etc/rc.freenas

pam_start()
{
	/usr/local/bin/midclt call etc.generate_all > /dev/null
}

pam_stop()
{
	/usr/local/bin/midclt call etc.generate_all > /dev/null
}

name="ix-pam"
start_cmd='pam_start'
stop_cmd='pam_stop'
        
load_rc_config $name
run_rc_command "$1"
