#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-resolv
# BEFORE: resolv
# KEYWORD: nojail
# REQUIRE: nsswitch

. /etc/rc.freenas

ix_resolv_start()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt -q call dns.sync > /dev/null
}

name="ix-resolv"
start_cmd='ix_resolv_start'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
