#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-syncdisks
# REQUIRE: devd earlykld
# BEFORE: fsck

. /etc/rc.subr

syncdisks()
{
	echo "Syncing disks..."
	/usr/local/bin/midclt call --job true --job-print description disk.sync_all > /dev/null
}

name="ix-syncdisks"
start_cmd='syncdisks'
stop_cmd=''

load_rc_config $name
run_rc_command "$1"
