#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-system
# BEFORE: samba_server ix-syslogd ix-collectd

. /etc/rc.freenas

notifier()
{
	/usr/local/bin/python \
	/usr/local/www/freenasUI/middleware/notifier.py $*
}

system_start()
{
	notifier system_dataset_create > /dev/null
	notifier nfsv4link > /dev/null
}

name="ix-system"
start_cmd='system_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
