#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-system
# BEFORE: samba_server ix-syslogd ix-collectd

. /etc/rc.freenas

notifier()
{
	/usr/local/bin/python \
	/usr/local/www/freenasUI/middleware/notifier.py $*
}

system_start()
{
	notifier system_dataset_create > /dev/null
	if [ "$(notifier pwenc_check)" = "False" ]; then
		notifier pwenc_generate_secret
	fi
	# start zilstatd daemon (needed by snmp for stats from zilstat)
	/usr/local/bin/python \
	/usr/local/www/freenasUI/tools/freenas-snmpd.py >/dev/null 2>&1
}

name="ix-system"
start_cmd='system_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
