#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-syslogd
# REQUIRE: zfs
# BEFORE: syslogd

. /etc/rc.freenas

ix_syslogd_start()
{
	# FIXME: THIS SHOULD BE REMOVED ONCE ix-zfs HAS BEEN PORTED OVER TO MIDDLEWARED
	/usr/local/bin/midclt call etc.generate 'syslogd' > /dev/null
}

name="ix-syslogd"
start_cmd='ix_syslogd_start'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
