#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-samba
# REQUIRE: FILESYSTEMS mountlate
# REQUIRE: ix-pam
# BEFORE: samba_server

. /etc/rc.freenas

generate_smb_config()
{
	/usr/local/libexec/nas/generate_smb4_conf.py
}

name="ix-samba"
start_cmd='generate_smb_config'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
