#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-sed
# BEFORE: ix-fstab

. /etc/rc.subr

unlock_drives()
{
	local IFS="|"
	local f="disk_passwd"
	local g="disk_name"
	eval local $f
	eval local $g
	local sf=$(var_to_sf $f)
	local sg=$(var_to_sf $g)
	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT

	${FREENAS_SQLITE_CMD} ${RO_FREENAS_CONFIG} "
	SELECT
		$sg,$sf

	FROM
		storage_disk

	WHERE (
		$sf != ''
	)

	 " | \
	while eval read $g $f
	do
		/sbin/camcontrol security /dev/${disk_name} "$(/usr/local/bin/midclt call notifier.pwenc_decrypt ${disk_passwd})"
	done
}

name="ix-sed"
start_cmd='unlock_drives'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
