#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-shutdown
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

do_shutdown()
{
	/usr/local/bin/midclt call initshutdownscript.execute_init_tasks SHUTDOWN > /dev/null
}

name="ix-shutdown"
start_cmd=':'
stop_cmd='do_shutdown'

load_rc_config $name
run_rc_command "$1"
