#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-syslogd
# REQUIRE: zfs
# BEFORE: syslogd

. /etc/rc.freenas

generate_syslog_conf()
{
	/usr/local/sbin/dispatcherctl call etcd.generation.generate_group '"syslog"'
}

ix_syslogd_start()
{
	generate_syslog_conf
}

name="ix-syslogd"
start_cmd='ix_syslogd_start'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
