#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-system
# BEFORE: samba_server

. /etc/rc.freenas

notifier()
{
	/usr/local/bin/python \
	/usr/local/www/freenasUI/middleware/notifier.py $*
}

system_start()
{
	if [ "$(notifier pwenc_check)" = "False" ]; then
		notifier pwenc_generate_secret
	fi
}

name="ix-system"
start_cmd='system_start'
stop_cmd=':'
status_cmd=':'

load_rc_config $name
run_rc_command $*
