#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-swap
# REQUIRE: zfs
# BEFORE: savecore

. /etc/rc.subr

generate_fstab_swap()
{
    /usr/local/bin/midctl call notifier.get_allswapdev | \
    while read devname; do
    if [ -c "/dev/${devname}" ]; then
        echo "/dev/${devname}.eli	none			swap		sw		0	0"
        if [ ! -L /dev/dumpdev ]; then
            /sbin/dumpon /dev/${devname} && ln -sf /dev/${devname} /dev/dumpdev
        fi
    fi
    done
}

generate_fstab()
{
    generate_fstab_swap >> /etc/fstab
    service swap start
}

name="ix-swap"
start_cmd='generate_fstab'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
