#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ssl
# REQUIRE: FILESYSTEMS
# BEFORE: ix-nginx

. /etc/rc.freenas


generate_ssl_certificates()
{
	sed -i '' '1,/^RANDFILE/ s,^RANDFILE.*,RANDFILE = /tmp/.rnd,' /etc/ssl/openssl.cnf
	/usr/local/libexec/nas/generate_ssl_certificates.py
}

name="ix-ssl"
start_cmd='generate_ssl_certificates'
stop_cmd=':'

load_rc_config $name
run_rc_command "${1}"
