#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-shutdown
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

execute_task()
{
	local stype=$1
	local f="ini_$stype"
	eval local $f
	local sf=$(var_to_sf $f)

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM tasks_initshutdown WHERE ini_when = 'shutdown' AND ini_enabled = 1 AND ini_type = '$stype' ORDER BY id" | \
	while eval read -r $f; do
		if [ "${stype}" = "command" ]; then
			sh -c "${ini_command}" < /dev/null
		else
			if [ -e "${ini_script}" ]; then
				sh -c "exec ${ini_script}" < /dev/null
			fi
		fi
	done
}

do_shutdown()
{
	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT

	execute_task "command"
	execute_task "script"

	/usr/local/bin/midclt call core.event_send system ADDED '{"id": "shutting-down"}' > /dev/null
}

name="ix-shutdown"
start_cmd=':'
stop_cmd='do_shutdown'

load_rc_config $name
run_rc_command "$1"
