#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ttys
# REQUIRE: root devfs
# BEFORE: LOGIN

. /etc/rc.subr

update_ttys()
{
	local IFS="|"
	local f="adv_consolemenu adv_serialconsole adv_serialspeed"
	eval local $f
	local sf=$(var_to_sf $f)
	local serspeed

	RO_FREENAS_CONFIG=$(ro_sqlite ${name} 2> /tmp/${name}.fail && rm /tmp/${name}.fail)
	trap 'rm -f ${RO_FREENAS_CONFIG}' EXIT

	${FREENAS_SQLITE_CMD} ${RO_FREENAS_CONFIG} "
	SELECT
		$sf

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1
	" | \
	while eval read $f
	do
		# If serial console is disabled, keep speed set by loader.
		if [ "$adv_serialconsole" -eq "1" ]; then
			serspeed=".${adv_serialspeed}"
		else
			serspeed=""
		fi

		tmp=$(mktemp /tmp/tmp.XXXXXX)
		if [ "${adv_consolemenu}" -eq "1" ]; then
			sed -E -e "s,^(ttyv0.*)Pc(.*)\$,\1freenas\2," /etc/ttys | \
			    sed -E -e "s,^(ttyu.*)(freenas|3wire)(\.[0-9]+)?(.*)\$,\1freenas${serspeed}\4," > "${tmp}"
		else
			sed -E -e "s,^(ttyv0.*)freenas(.*)\$,\1Pc\2," /etc/ttys | \
			    sed -E -e "s,^(ttyu.*)(freenas|3wire)(\.[0-9]+)?(.*)\$,\13wire${serspeed}\4," > "${tmp}"
		fi

		if [ -s "${tmp}" ]; then
			mv "${tmp}" /etc/ttys
		else
			rm -f "$tmp"
		fi

		kill -HUP 1
		break
	done
}

name="ix-ttys"
start_cmd='update_ttys'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
