#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-update
# BEFORE: ix-fstab

. /etc/rc.freenas

readonly UPDATE_FAILED_LOG="/data/update.failed"

# The function below takes two arguments
# 1. The path you want it to write its output to (the .crt and .key files)
# 2. The old pre-certui database (do not give it the post certmanager migrated db as it will fail)
# It writes the cert file as "precertman.crt" and key file as "precertman.key"
upgrade_cert_migration()
{
    local write_path="${1}"
    local freenas_old_db="${2}"
    local tmpcertfile=$(mktemp /tmp/tmp.XXXXXX)

    ${FREENAS_SQLITE_CMD} ${freenas_old_db} "
    SELECT
           ssl_certfile

    FROM
           system_ssl

    ORDER BY
           -id

    LIMIT 1
           " > "${tmpcertfile}"
    # Now seperate the certs and keys into seperate files
    sed -nE '/-----BEGIN CERTIFICATE-----/,/-----END CERTIFICATE-----|end/p ' "${tmpcertfile}" > "${write_path}/precertman.crt"
    sed -nE '/-----BEGIN RSA PRIVATE KEY-----/,/-----END RSA PRIVATE KEY-----|end/p' "${tmpcertfile}" > "${write_path}/precertman.key"
}

db_update_real()
{
	echo "Applying database schema changes"

	yes | /usr/local/bin/python \
	    /usr/local/www/freenasUI/manage.py migrate --merge --delete-ghost-migrations > \
		$UPDATE_FAILED_LOG 2>&1
	if [ $? -ne 0 ]; then
		echo "manage.py migrate failed"
		return 1
	fi
	rm -f $UPDATE_FAILED_LOG
	return 0
}

handle_error()
{
	local LABELNAME OTHER_PARTNUM PARTNUM TARGET_DRIVE

	echo "Reverting to previous state"

	rm -f $NEED_UPDATE_SENTINEL
	mv ${FREENAS_CONFIG}.bak ${FREENAS_CONFIG}
	if [ -f $CD_UPGRADE_SENTINEL ]; then
		rm $CD_UPGRADE_SENTINEL
		cat <<EOF
Database upgrade FAILED; check $UPDATE_FAILED_LOG for more details.
Reverting a failed CD upgrade is not totally possible
Rebooting in 15 seconds..
EOF
		sleep 15
		reboot
	fi

	. /etc/nanobsd.conf

	# Need to be fixed for #4689
	LABELNAME=`echo ${NANO_DRIVE} | cut -f2 -d/`
	if mount | grep ${NANO_DRIVE}s1 > /dev/null ; then
		PARTNUM=1
		OTHER_PARTNUM=2
	else
		PARTNUM=2
		OTHER_PARTNUM=1
	fi
	TARGET_DRIVE=`glabel status | awk '/ufs\/'${LABELNAME}s${PARTNUM}'a/ { print $3; }' | sed -e 's/s.a//'`
	gpart set -a active -i $OTHER_PARTNUM ${TARGET_DRIVE}

	cat <<EOF
Database upgrade FAILED; check $UPDATE_FAILED_LOG for more details.
Rebooting in 15 seconds..
EOF
	sleep 15
	reboot
}

db_update()
{
	local precertman
	if [ ! -f $NEED_UPDATE_SENTINEL ]; then
	    # exit this script and continue with normal boot.
	    exit 0
	fi

	# We are running very early, make / read-write.
	mount -uw /
	echo "Saving current ${FREENAS_CONFIG} to ${FREENAS_CONFIG}.bak"
	cp ${FREENAS_CONFIG} ${FREENAS_CONFIG}.bak

	if [ -f /data/uploaded.db ]; then
		echo "Moving uploaded config to ${FREENAS_CONFIG}"
		mv /data/uploaded.db ${FREENAS_CONFIG}
	fi

	# The call below checks if the version of freenas we are updating form is
	# a pre-cert-UI version or not and stores its result in a local var.
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "select * from system_ssl;" > /dev/null 2>&1
	precertman=$?
	if [ "${precertman}" == 0 ]; then
		# The step below will parse and write the old cert and key to /root/precertman.crt/.key
		upgrade_cert_migration "/root" ${FREENAS_CONFIG}
	fi

	set +e
	db_update_real || handle_error
	set -e

	rm -f $NEED_UPDATE_SENTINEL
	rm -f $CD_UPGRADE_SENTINEL

	# remove ${FIRST_INSTALL_SENTINEL} from this loader call
	rm -f ${FIRST_INSTALL_SENTINEL}
	# NOTE: this must be run via the rc.d script, not service(8).
	env AUTOTUNE_REBOOT=false /etc/ix.rc.d/ix-loader start
	# we need it for the ix-loader service call later on
	touch ${FIRST_INSTALL_SENTINEL}

	echo "Database upgrade complete.  Rebooting."
	cd /
	if [ "${precertman}" == 0 ]; then
		# Now that the migration is done we just take the earlier saved cert and key
		# and add it to the current scheme of things (the call to the python code below
		# does that) after it is done delete the precertman.crt and .key files
		/usr/local/bin/python /usr/local/www/freenasUI/tools/updatessl.py /root/precertman.crt /root/precertman.key
	fi
	rm -f /root/precertman.*
	sleep 2
	reboot
}

name="ix-update"
start_cmd='db_update'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
