#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-zfs
# REQUIRE: hostid mountcritlocal
# BEFORE: FILESYSTEMS var

. /etc/rc.subr

import_zpools()
{
	/usr/local/bin/midclt call -job --job-print description pool.import_on_boot > /dev/null
}

name="ix-zfs"
start_cmd='import_zpools'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
