#!/bin/sh
#
# $FreeBSD$
#
# Copyright (c) 2015 iXsystems, Inc.
# All rights reserved.
# This file is a part of TrueNAS
# and may not be copied and/or distributed
# without the express permission of iXsystems.

# PROVIDE: ix_pf_early
# BEFORE: routing
# REQUIRE: FILESYSTEMS netif
# KEYWORD: nojail

. /etc/rc.subr

name="ix_pf_early"
start_cmd="ix_pf_early_start"
stop_cmd=":"


ix_pf_early_start()
{
	checkyesno failover_enable || /sbin/pfctl -ef /etc/pf.conf.block
}

run_rc_command "$1"
