#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix_pf_early
# BEFORE: routing
# REQUIRE: FILESYSTEMS netif
# KEYWORD: nojail

. /etc/rc.subr

name="ix_pf_early"
start_cmd="ix_pf_early_start"
stop_cmd=":"


ix_pf_early_start()
{
	/bin/sh /etc/ipfw.conf.block
}

run_rc_command "$1"
