#!/bin/sh
#
# $FreeBSD$
#
# Copyright (c) 2015 iXsystems, Inc.
# All rights reserved.
# This file is a part of TrueNAS
# and may not be copied and/or distributed
# without the express permission of iXsystems.

# PROVIDE: ix_pf_late
# AFTER: bgfsck
# KEYWORD: nojail shutdown

. /etc/rc.subr

name="ix_pf_late"
start_cmd="ix_pf_late_start"
stop_cmd="ix_pf_late_stop"


ix_pf_late_start()
{
	checkyesno failover_enable || /sbin/pfctl -d
}

ix_pf_late_stop()
{
	checkyesno failover_enable || /sbin/pfctl -e /etc/pf.conf.block
}

run_rc_command "$1"
