#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix_register
# REQUIRE: mdnsd
# KEYWORD: nojail

. /etc/rc.subr

name="ix_register"
start_cmd="ix_register_start"
stop_cmd=":"


ix_register_start()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call mdnsadvertise.start > /dev/null
}

run_rc_command "$1"
