#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix_register
# REQUIRE: mdnsd
# KEYWORD: nojail

. /etc/rc.subr

name="ix_register"
start_cmd="ix_register_start"
reload_cmd="ix_register_reload"
extra_commands="reload"
pid="/var/run/register.pid"
stop_cmd=":"


ix_register_start()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call mdns.start > /dev/null
}

ix_register_reload()
{
	LD_LIBRARY_PATH=/usr/local/lib /usr/local/bin/midclt call mdns.restart > /dev/null
}

run_rc_command "$1"
