#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix_register
# REQUIRE: mdnsd
# KEYWORD: nojail

. /etc/rc.subr

name="ix_register"
start_cmd="ix_register_start"
reload_cmd="ix_register_reload"
extra_commands="reload"
pid="/var/run/register.pid"
stop_cmd=":"


ix_register_start()
{
	daemon -c -f -p ${pid} -r /usr/local/libexec/nas/register_mdns.py
}

ix_register_reload()
{
	kill -TERM `cat ${pid}`
}

run_rc_command "$1"
