#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-afpd
# REQUIRE: FILESYSTEMS
# BEFORE: afpd

. /etc/rc.subr

generate_afpd()
{
	/usr/local/libexec/nas/generate_afpd_conf.py
}

name="ix-afpd"
start_cmd='generate_afpd'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
