#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ataidle
# REQUIRE: DAEMON
# BEFORE: LOGIN
# KEYWORD: nojail shutdown

. /etc/rc.subr

ataidle_start()
{
	local IFS=\|

	local f="disk_identifier disk_hddstandby disk_advpowermgmt disk_acousticlevel"
	eval local $f
	local cmd sf
	sf=$(echo $f | sed -e 's/ /, /g')

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
		"SELECT $sf FROM storage_disk" | \
	while eval read $f; do
        disk=$(/usr/local/bin/python /usr/local/www/freenasUI/middleware/notifier.py identifier_to_device "${disk_identifier}")
        if [ -z `echo "${disk}"|egrep "^ada|^da"` ]; then
            continue
        fi
		ataidle_args=""
		if [ "${disk_advpowermgmt}" != "Disabled" ]; then
			ataidle_args="-P ${disk_advpowermgmt}"
		else
			ataidle_args="-P 0"
		fi
		if [ "${disk_acousticlevel}" != "Disabled" ]; then
			if [ "${disk_acousticlevel}" = "Minimum" ]; then
				disk_acousticlevel=1
			elif [ "${disk_acousticlevel}" = "Medium" ]; then
				disk_acousticlevel=64
			elif [ "${disk_acousticlevel}" = "Maximum" ]; then
				disk_acousticlevel=127
			fi
		else
			disk_acousticlevel=0
		fi
		ataidle_args="${ataidle_args} -A ${disk_acousticlevel}"
		if [ -n "${ataidle_args}" ]; then
			/usr/local/sbin/ataidle ${ataidle_args} ${disk}
		fi
		if [ "${disk_hddstandby}" != "Always On" ]; then
			(sleep 60; /usr/local/sbin/ataidle -I ${disk_hddstandby} ${disk}) > /dev/null 2>&1 &
		fi
	done
}

name="ix-ataidle"
start_cmd="ataidle_start"
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
