#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-bsnmpd
# REQUIRE: FILESYSTEMS NETWORKING
# BEFORE: bsnmpd

. /etc/rc.subr

bsnmp_config=/etc/snmpd.config

generate_snmpconf()
{
	local IFS="|"
	local f="
		snmp_location
		snmp_contact
		snmp_community
		snmp_traps
		snmp_options
	"
	eval local $f
	local sf=$(var_to_sf $f)

        hw_machine=`/sbin/sysctl -n hw.machine`
        hw_model=`/sbin/sysctl -n hw.model`
        hw_clockrate=`/sbin/sysctl -n hw.clockrate`
        kern_ostype=`/sbin/sysctl -n kern.ostype`
        kern_osrelease=`/sbin/sysctl -n kern.osrelease`
        kern_osrevision=`/sbin/sysctl -n kern.osrevision`

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT $sf FROM services_snmp ORDER BY -id LIMIT 1" | \
	while read $f; do
		cat > "${bsnmp_config}" << EOF
# Set some common variables
host := ${hostname}
contact := "${snmp_contact}"
location := "${snmp_location}"
system := 1 # FreeBSD
description := "Hardware: ${hw_machine} ${hw_model} running at ${hw_clockrate} Software: ${kern_ostype} ${kern_osrelease} (revision ${kern_osrevision})"
read := "${snmp_community}"

# Configuration
%snmpd
begemotSnmpdDebugDumpPdus = 2
begemotSnmpdDebugSyslogPri = 7

# Set the read and write communities.
begemotSnmpdCommunityString.0.1 = "${snmp_community}"
begemotSnmpdCommunityDisable = 1

# open standard SNMP ports
begemotSnmpdPortStatus.0.0.0.0.161 = 1

# open a unix domain socket
begemotSnmpdLocalPortStatus."/var/run/snmpd.sock" = 1
begemotSnmpdLocalPortType."/var/run/snmpd.sock" = 4

sysContact = \$(contact)
sysLocation = \$(location)
sysObjectId = 1.3.6.1.4.1.12325.1.1.2.1.\$(system)
sysDescr = \$(description)

begemotSnmpdModulePath."mibII" = "/usr/lib/snmp_mibII.so"
EOF
	done
	echo "$snmp_options" >> ${bsnmp_config}
}

name="ix-snmpd"
start_cmd='generate_snmpconf'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
