#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-cache
# REQUIRE: LOGIN

. /etc/rc.freenas

populate_cache()
{
	if srv_enabled ldap
	then
		/usr/local/www/freenasUI/tools/cachetool.py fill

	elif srv_enabled activedirectory
	then
		/usr/local/www/freenasUI/tools/cachetool.py fill
	fi
}

expire_cache()
{
        /usr/local/www/freenasUI/tools/cachetool.py expire
}

name="ix-cache"
start_cmd='populate_cache'
stop_cmd='expire_cache'
            
load_rc_config $name
run_rc_command "$1"
