#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-fusionio
# BEFORE: ix-zfs

. /etc/rc.subr

load_fusionio()
{
	if ! kldstat -v | grep -q iomemory-vsl; then
		kldload iomemory-vsl
	fi
}

unload_fusionio()
{
	# TODO: Insert fun fio_detach stuff here.

	kldunload iomemory-vsl
}

name="ix-fusionio"
start_cmd='load_fusionio'
stop_cmd='unload_fusionio'

load_rc_config $name
run_rc_command "$1"
