#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-inadyn
# BEFORE: inadyn

. /etc/rc.subr

generate_inadyn_real()
{
	local IFS=\|

	local f="ddns_provider ddns_domain ddns_username ddns_password ddns_updateperiod ddns_fupdateperiod ddns_options"
	eval local $f
	local cmd sf
	sf=$(echo $f | sed -e 's/ /, /g')
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
		"SELECT $sf FROM services_dynamicdns ORDER BY -id LIMIT 1" | \
	while eval read $f; do
		cat << E*O*F
dyndns_system ${ddns_provider}	
background
syslog
username ${ddns_username}
password ${ddns_password}
alias ${ddns_domain}
E*O*F
		if [ -n "${ddns_updateperiod}" ]; then
			echo "update_period_sec ${ddns_updateperiod}"
		fi
		if [ -n "${ddns_fupdateperiod}" ]; then
			echo "forced_update_period ${ddns_fupdateperiod}"
		fi
		if [ -n "${ddns_options}" ]; then
			echo "${ddns_options}"
		fi
	done
}

generate_inadyn()
{
	generate_inadyn_real > /usr/local/etc/inadyn.conf
}

name="ix-inadyn"
start_cmd='generate_inadyn'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
