#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-inetd
# REQUIRE: FILESYSTEMS
# BEFORE: inetd

. /etc/rc.subr

# XXX need to refactor this
_svc_enabled()
{
    local IFS=\|
    local boolvalue
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable FROM services_services WHERE srv_service='$1' ORDER BY id DESC LIMIT 1" | \
	while read boolvalue; do
	    echo ${boolvalue}
	done
}

generate_tftp()
{
    local IFS=\|
    local f="tftp_directory tftp_newfiles tftp_port tftp_username tftp_umask tftp_options"
    eval local $f
    local cmd sf
    local enabled
    sf=$(echo $f | sed -e 's/ /, /g')
    enabled=$(_svc_enabled tftp)
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM services_tftp ORDER BY -id LIMIT 1" | \
    while eval read $f; do
	if [ $enabled = 1 ]; then
	    if [ $tftp_port = "69" ]; then
		service="tftp"
	    else
		service="freenas-tftp"
		echo "freenas-tftp $tftp_port/udp" >> /tmp/services.extra
	    fi
	    cmd="tftpd -l -s $tftp_directory -u $tftp_username -U $tftp_umask $tftp_options"
	    if [ $tftp_newfiles = 1 ]; then
		cmd="$cmd -w"
	    fi
	    echo "$service dgram udp wait root /usr/libexec/tftpd $cmd" \
		>> /tmp/inetd.conf.extra
	fi
    done
}

generate_inetd_files()
{
    rm -f /tmp/inetd.conf.extra /tmp/services.extra
    generate_tftp
    if [ -f /tmp/services.extra ]; then
	cat /conf/base/etc/services /tmp/services.extra > /etc/services
    fi
    if [ -f /tmp/inetd.conf.extra ]; then
	cat /conf/base/etc/inetd.conf /tmp/inetd.conf.extra > /etc/inetd.conf
    fi
    rm -f /tmp/inetd.conf.extra /tmp/services.extra
    # we assume that someone else kicks inetd if necessary
}

name="ix-inetd"
start_cmd='generate_inetd_files'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
