#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-inetd
# REQUIRE: FILESYSTEMS
# BEFORE: inetd

. /etc/rc.subr

generate_tftp()
{
	local IFS=\|
	local f="toggleTFTP directory newfiles tftp_port username umask options"
	local toggleTFTP directory newfiles tftp_port username umask options
	local cmd sf
	sf=$(echo $f | sed -e 's/ /, /g')
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	    "SELECT $sf FROM freenas_servicestftp ORDER BY -id LIMIT 1" | \
    while read toggleTFTP directory newfiles tftp_port username umask options; do
	if [ $toggleTFTP = 1 ]; then
	    if [ $tftp_port = "69" ]; then
		service="tftp"
	    else
		service="freenas-tftp"
		echo "freenas-tftp $tftp_port/udp" >> /tmp/services.extra
	    fi
	    cmd="tftpd -l -s $directory -u $username -U $umask $options"
	    if [ $newfiles = 1 ]; then
		cmd="$cmd -w"
	    fi
	    echo "$service dgram udp wait root /usr/libexec/tftpd $cmd" \
		>> /tmp/inetd.conf.extra
	fi
    done
}

generate_inetd_files()
{
    rm -f /tmp/inetd.conf.extra /tmp/services.extra
    generate_tftp
    if [ -f /tmp/services.extra ]; then
	cat /conf/base/etc/services /tmp/services.extra > /etc/services
    fi
    if [ -f /tmp/inetd.conf.extra ]; then
	cat /conf/base/etc/inetd.conf /tmp/inetd.conf.extra > /etc/inetd.conf
    fi
    rm -f /tmp/inetd.conf.extra /tmp/services.extra
    # we assume that someone else kicks inetd if necessary
}

name="ix-inetd"
start_cmd='generate_inetd_files'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
