#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-jail
# BEFORE: jail

. /etc/rc.freenas

get_plugins_jail_name()
{
	jail_name=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		jail_name

	FROM
		services_plugins

	ORDER BY	
		-id

	LIMIT 1;
	")

	echo "${jail_name}"
}
    
generate_plugins_jail_config()
{
	local IFS="|"
	local tmpfile="$(mktemp -q /var/tmp/.rcfooXXXXXX)"

	grep -v "jail_" /etc/rc.conf > "${tmpfile}"

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		jail_path,
		jail_name,
		jail_ip,
		jail_netmask,
		jail_interface,
		plugins_path

	FROM
		services_plugins

	ORDER BY	
		-id

	LIMIT 1
	" | \
	while read path name ip netmask iface plugins
	do
		echo "${plugins} ${path}/${name}/mnt nullfs ro 0 0" > "/etc/fstab.${name}"
		cp /etc/resolv.conf ${path}/${name}/etc/resolv.conf
		sysctl security.jail.allow_raw_sockets=1

		# No VIM colors needed here
		cat<<-__EOF__>>"${tmpfile}"

		jail_${name}_rootdir="${path}/${name}"
		jail_${name}_hostname="${name}"
		jail_${name}_ip="${ip}"
		jail_${name}_devfs_enable="YES"
		jail_${name}_devfs_ruleset="devfsrules_jail"
		jail_${name}_procfs_enable="YES"
		jail_${name}_mount_enable="YES"
		jail_sysvipc_allow="YES"
		jail_list="${name}"
		jail_enable="YES"
__EOF__
	done	

	mv "${tmpfile}" /etc/rc.conf
	return $?
}


plugins_jail_start()
{
	if srv_enabled plugins
	then
		local jail_name="$(get_plugins_jail_name)"

		generate_plugins_jail_config
		/etc/rc.d/jail start "${jail_name}"
	fi
}

plugins_jail_stop()
{
	if srv_enabled plugins
	then
		local jail_name="$(get_plugins_jail_name)"
		if [ -n "${jail_name}" ]
		then
			local tmpfile="$(mktemp -q /var/tmp/.rcfooXXXXXX)"

			grep -v "jail_" /etc/rc.conf > "${tmpfile}"
			mv "${tmpfile}" /etc/rc.conf

			rm -f "/etc/fstab.${jail_name}"
			/etc/rc.d/jail stop "${jail_name}"
		fi
	fi
}



name="ix-jail"
start_cmd='plugins_jail_start'
stop_cmd='plugins_jail_stop'
            
load_rc_config $name
run_rc_command "$1"
