#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kinit
# REQUIRE: kerberos

. /etc/rc.subr

kerberos_init()
{
	local IFS="|"

    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		ad_dcname,
		ad_domainname,
		ad_netbiosname,
		ad_adminname,
		ad_adminpw

	FROM
		services_services,
		services_activedirectory

	WHERE (
		srv_service = 'activedirectory' and
		srv_enable = '1'
	)

	ORDER BY
		-services_activedirectory.id

	LIMIT 1
	" | \
	while read dc domain netbios admin pw
	do
		if [ -n "${admin}" -a -n "${domain}" -a -n "${pw}" ]
		then
			local pwfile="/tmp/."$(date '+%H%M%S')
			touch "${pwfile}"
			chmod 600 "${pwfile}"
			echo "${pw}" > ${pwfile}

			domain=$(echo "${domain}"|tr a-z A-Z)
			kinit --password-file="${pwfile}" "${admin}@${domain}"

			rm "${pwfile}"
		fi
	done
}

name="ix-kinit"
start_cmd='kerberos_init'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
