#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kinit
# REQUIRE: kerberos

. /etc/rc.subr

: ${PATH_AD_KEYTAB:="/etc/AD.keytab"}

kerberos_init()
{
	local IFS="|"

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		ad_dcname,
		ad_domainname,
		ad_netbiosname,
		ad_adminname,
		ad_adminpw,
		ad_windows_version,
		ad_spn,
		ad_spnpw

	FROM
		services_services,
		services_activedirectory

	WHERE (
		srv_service = 'activedirectory' and
		srv_enable = '1'
	)

	ORDER BY
		-services_activedirectory.id

	LIMIT 1
	" | \
	while read dc domain netbios admin pw version spn spnpw
	do
		if [ "${version}" != "windows2008" -a -n "${admin}" -a -n "${domain}" -a -n "${pw}" ]
		then
			local pwfile="/tmp/."$(date '+%H%M%S')
			touch "${pwfile}"
			chmod 600 "${pwfile}"
			echo "${pw}" > ${pwfile}

			domain=$(echo "${domain}"|tr a-z A-Z)
			kinit --password-file="${pwfile}" "${admin}@${domain}"

			rm "${pwfile}"

		elif [ "${version}" = "windows2008" -a -n "${domain}" -a -n "${pw}" ]
		then
			local pwfile="/tmp/."$(date '+%H%M%S')
			touch "${pwfile}"
			chmod 600 "${pwfile}"
			echo "${spnpw}" > ${pwfile}

			domain=$(echo "${domain}"|tr a-z A-Z)
			kinit -k -t /etc/AD.keytab --password-file="${pwfile}" "${spn}@${domain}"

			rm "${pwfile}"
		fi
	done
}

name="ix-kinit"
start_cmd='kerberos_init'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
