#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kinit
# REQUIRE: kerberos
# REQUIRE: ix-samba
# REQUIRE: ntpd

. /etc/rc.freenas


kerberos_start()
{
	local ec pwfile

	ec=1

	if srv_enabled activedirectory
	then
		AD_init

		domainname=$(AD_get domainname)
		adminname=$(AD_get adminname)
		adminpw=$(AD_get adminpw)

		if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
		then
			local pwfile="/tmp/."$(date '+%H%M%S')
			touch "${pwfile}"
			chmod 600 "${pwfile}"
			echo "${adminpw}" > ${pwfile}
			domainname=$(echo "${domainname}" | tr a-z A-Z)
			kinit --password-file="${pwfile}" \
			    "${adminname}@${domainname}"
			ec=$?

			sleep 10
			rm -f "${pwfile}"
		fi
	fi
	return $ec
}

kerberos_status()
{
	local ec

	ec=1

	if srv_enabled activedirectory
	then
		AD_init

		domainname=$(AD_get domainname)
		adminname=$(AD_get adminname)
		adminpw=$(AD_get adminpw)

		if [ -n "${adminname}" -a -n "${domainname}" -a -n "${adminpw}" ]
		then
			domainname=$(echo "${domainname}"|tr a-z A-Z)
			klist -l | grep -q "^${adminname}@${domainname}"
			ec=$?
		fi
	fi
	return $ec
}

kerberos_stop()
{
	kdestroy
}

name="ix-kinit"
start_cmd='kerberos_start'
status_cmd='kerberos_status'
stop_cmd='kerberos_stop'

load_rc_config $name
run_rc_command "$1"
