#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-kerberos
# BEFORE: kerberos

. /etc/rc.freenas

: ${PATH_KRB5_TEMPLATE:="/etc/ix/templates/kerberos/krb5.conf"}
: ${PATH_KRB5_CONFIG:="/etc/krb5.conf"}

generate_krb5_conf()
{
	AD_init

	local krbhost=$(AD_get krbhost)
	local kpwdhost=$(AD_get kpwdhost)
	local domainname=$(AD_get domainname)
	local template="${PATH_KRB5_TEMPLATE}"

	AD_log "generate_krb5_conf: krbhost=${krbhost}, kpwdhost=${kpwdhost}, " \
		"domainname=${domainname}"

	if [ ! -f "${template}" ]
	then
		return 1
	fi

	awk -v realm="${domainname}" \
		-v kdc="${krbhost}" \
		-v kpwd="${kpwdhost}" \
	'
	BEGIN {
		kdc = sprintf("%s", tolower(kdc));
		vars["@@UPPER_REALM@@"]  = toupper(realm);	
		vars["@@LOWER_REALM@@"]  = tolower(realm);	
		vars["@@ADMIN_SERVER@@"]  = kdc;	
		vars["@@KPASSWD_SERVER@@"] = kpwd;
		vars["@@DOMAIN@@"]  = tolower(realm);
		vars["@@KDC@@"]  = kdc;	
	}
	{
		if (/@@.+@@/) {
			for (var in vars) {
				gsub(var, vars[var]);
			}
		}

		print $0;
	}
	' < "${template}" > "${PATH_KRB5_CONFIG}"

	local IFS="
"
	for line in $(verify_krb5_conf 2>&1) 
	do
		AD_log "generate_krb5_conf: ${line}"
	done

	return 0
}

generate_kerberos_files()
{
	if srv_enabled activedirectory
	then
		generate_krb5_conf
	fi
}

name="ix-kerberos"
start_cmd='generate_kerberos_files'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
