#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-loader
# REQUIRE: ix-update

. /etc/rc.subr

loader_serial()
{
	local serial_enable=0

	serial_enable=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_serialconsole

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1")

	if [ "${serial_enable}" != "0" ]; then
		echo 'boot_multicons="YES"'
		echo 'console="vidconsole,comconsole"'
	fi
}

loader_saver()
{
	local saver_enable=0

	saver_enable=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_consolescreensaver

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1")

	if [ "${saver_enable}" != "0" ]; then
		echo 'screensave_load="YES"'
		echo 'screensave_name="daemon_saver"'
	fi

}

loader_user() {

	local IFS="|"
	local f="ldr_var ldr_value ldr_comment"
	eval local $f
	local sf=$(var_to_sf $f)
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM system_loader ORDER BY id" | \
	while eval read $f; do
		(echo -n "${ldr_var}=\"${ldr_value}\""
		 if [ -n "$ldr_comment" ]; then
			echo -e " # $ldr_comment"
		 else
			echo
		 fi)
	done

}

update_loader_conf()
{
	local tmp

	tmp=$(mktemp /tmp/tmp.XXXXXX)

	settings="serial saver user"
	for s in ${settings}
	do
		eval "loader_${s}" >> $tmp
	done

	# NOTE: newline required!
	sha256orig=$(sha256 -q -s "$(sed -E -n '/# User customizations/{n;p;}' /boot/loader.conf)
")
	sha256new=$(sha256 -q "${tmp}" 2>/dev/null)
	if [ "${sha256orig}" != "${sha256new}" ]; then
		tmp2=$(mktemp /tmp/tmp.XXXXXXX)
		cat > $tmp2 <<EOF
$(sed -E -n '/# User customizations/q;p' /boot/loader.conf)

# User customizations (DO NOT DELETE THIS LINE)
$(cat "${tmp}" 2>/dev/null)
EOF
		rc=1
		if mount -uw /; then
			if mv "$tmp2" /boot/loader.conf; then
				rc=0
			fi
			mount -ur /
		else
			rm -f "$tmp2"
		fi
		return $rc
	fi
	rm -f $tmp
}

name="ix-loader"
start_cmd='update_loader_conf'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
