#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-loader
# REQUIRE: ix-update

. /etc/rc.subr

: ${AUTOTUNE_REBOOT=true}

# Update an file that persists across reboots with a new file if something's
# changed, or nuke it if the file was unchanged.
#
# TODO: move to rc.freenas.
#
# Parameters:
#   1 - Old file
#   2 - New file
#
# Returns...
#   0 - updated something.
#   1 - no change.
#   2 - an error occurred.
update_persistent_file()
{
	local new old rc

	old=$1
	new=$2

	rc=1
	if [ ! -f "$new" ]; then
		:
	elif cmp -s "$old" "$new"; then
		rm -f "$new"
	else
		rc=2
		if mount -uw -onoatime /; then
			if mv "$new" "$old"; then
				rc=0
			fi
			mount -ur /
		fi
	fi
	return $rc
}

loader_serial()
{
	local serial_enable=0

	serial_enable=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_serialconsole

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1")

	if [ "${serial_enable}" != "0" ]; then
		echo 'boot_multicons="YES"'
		echo 'console="vidconsole,comconsole"'
	fi
}

loader_user() {

	local IFS="|"
	local f="tun_var tun_value tun_comment"
	eval local $f
	local sf=$(var_to_sf $f)
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM system_tunable WHERE tun_enabled = 1 ORDER BY id" | \
	while eval read -r $f; do
		(echo -n "${tun_var}=\"${tun_value}\""
		 if [ -n "${tun_comment}" ]; then
			echo -e " # ${tun_comment}"
		 else
			echo
		 fi)
	done

}

loader_debugkernel()
{
	local debugkernel_enable=0

	debugkernel_enable=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_debugkernel

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1")

	if [ "${debugkernel_enable}" != "0" ]; then
		echo 'kernel="kernel-debug"'
		echo 'module_path="/boot/kernel-debug;/boot/modules"'
	fi
}

do_autotune()
{
	local autotune

	export PATH=$PATH:/usr/local/bin:/usr/local/sbin

	autotune=/usr/local/bin/autotune
	ec=0
	if [ -x $autotune ]
	then

		$autotune \
				--kernel-reserved=1073741824 \
				--userland-reserved=2417483648

		ec=$?
		# Values changed based on recommendations. Reboot [eventually].
		if [ $ec -eq 2 ]
		then
			ec=0
			reboot_now=true
		fi
	fi
	return $ec
}

generate_boot_loader_conf_local()
{
	local settings
	local tmp

	settings="serial user debugkernel"

	tmp=$(mktemp /tmp/tmp.XXXXXX)

	for setting in $settings; do
		eval "loader_${setting}" >> $tmp
	done

	update_persistent_file /boot/loader.conf.local $tmp
}

generate_loader_confs()
{
	reboot_now=false

	do_autotune
	generate_boot_loader_conf_local

	if $AUTOTUNE_REBOOT && $reboot_now; then
		shutdown -r now
	fi
}

generate_loader_confs_noreboot()
{
	do_autotune
	generate_boot_loader_conf_local
}

name="ix-loader"
start_cmd='generate_loader_confs'
reload_cmd='generate_loader_confs_noreboot'
stop_cmd=':'
extra_commands='reload'

load_rc_config $name
run_rc_command "$1"
