#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-msmtp
# REQUIRE: FILESYSTEMS
# BEFORE: mountlate

. /etc/rc.subr

msmtp_config=${msmtp_config:-"/usr/local/etc/msmtprc"}

generate_msmtp_cfg()
{
	local IFS=\|
	local f="em_fromemail em_outgoingserver em_port em_security em_smtp em_user em_pass"
	eval local $f
	local cmd sf
	sf=$(echo $f | sed -e 's/ /, /g')
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	    "SELECT $sf FROM system_email ORDER BY -id LIMIT 1" | \
	    while eval read $f; do
	        cat <<__EOF__
account default
host ${em_outgoingserver}
port ${em_port}
protocol smtp
from ${em_fromemail}
syslog LOG_MAIL
__EOF__
		if [ ${em_security} != "plain" ]; then
		    echo tls on
		    echo tls_certcheck off
		    if [ ${em_port} -eq 25 ]; then
		        echo tls_starttls off
		    else
		        echo tls_starttls on
		    fi
		    if [ ${em_security} = "ssl" ]; then
		        echo tls_force_sslv3 on
		    fi
		fi
                if [ "${em_smtp}" = "1" ]; then
		    echo auth login
                    echo user ${em_user}
                    echo password ${em_pass}
		else
		    echo auth off
                fi
	    done
}

generate_msmtp()
{
	generate_msmtp_cfg > ${msmtp_config}
	chmod 600 ${msmtp_config}
}

name="ix-msmtp"
start_cmd='generate_msmtp'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
