#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-multipath
# REQUIRE: FILESYSTEMS ix-syncdisks

. /etc/rc.subr

multipath_sync()
{
	/usr/local/bin/python /usr/local/www/freenasUI/middleware/notifier.py multipath_sync
}

name="ix-multipath"
start_cmd='multipath_sync'
stop_cmd=''

load_rc_config $name
run_rc_command "$1"
