#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-proftpd
# REQUIRE: FILESYSTEMS
# BEFORE: proftpd

. /etc/rc.subr

msmtp_config=${msmtp_config:-"/var/etc/msmtp.conf"}

generate_msmtp_cfg()
{
	local IFS=\|
	local f="fromemail outgoingserver port security smtp"
	local fromemail outgoingserver port security smtp
	local cmd sf
	sf=$(echo $f | sed -e 's/ /, /g')
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	    "SELECT $sf FROM freenas_systemadvancedemail ORDER BY -id LIMIT 1" | \
	    while read fromemail outgoingserver port security smtp
	        cat <<__EOF__
account default
host ${outgoingserver}
port ${port}
protocol smtp
from ${fromemail}
syslog LOG_MAIL
auth none
__EOF__
		# xxx need support for auth method
		# xxx need user/pass in database
		# eg: -i "count(//system/email/auth) > 0"
  		# -v "concat('auth ',//system/email/authmethod)" -n
		# -v "concat('user ',//system/email/username)" -n
		# -v "concat('password ',//system/email/password)" -n
		if [ ${security} != "None" ]; then
		    echo tls on
		    echo tls_certcheck off
		    if [ ${port} -eq 25 ]; then
		        echo tls_starttls off
		    else
		        echo tls_starttls on
		    fi
		fi
	    done
}

generate_msmtp()
{
	generate_msmtp_cfg > ${msmtp_config}
	chmod 600 ${msmtp_config}
}

name="ix-msmtp"
start_cmd='generate_msmtp'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
