#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nis
# BEFORE: ypbind

. /etc/rc.freenas

nis_start()
{
	return 0
}

nis_status()
{
	return 0
}

nis_stop()
{
	return 0
}


name="ix-nis"
start_cmd='nis_start'
status_cmd='nis_status'
stop_cmd='nis_stop'
            
load_rc_config $name
run_rc_command "$1"
