#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ntpd
# REQUIRE: FILESYSTEMS
# BEFORE: ntpd

. /etc/rc.subr

FREENAS_SQLITE_CMD=/usr/local/bin/sqlite3

generate_ntp_conf()
{
	local IFS="|"
	local f="
		stg_ntpserver1
		stg_ntpserver2
		stg_ntpserver3
		"
	eval local $f
	local sf=$(var_to_sf $f)

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT $sf FROM system_settings ORDER BY -id LIMIT 1" | \
	while read $f; do
		if [ -n "${ntpserver1}" ]; then
			echo "server ${ntpserver1}"
		fi
		if [ -n "${ntpserver2}" ]; then
			echo "server ${ntpserver2}"
		fi
		if [ -n "${ntpserver3}" ]; then
			echo "server ${ntpserver3}"
		fi
	done > /etc/ntp.conf
}



name="ix-ntpd"
start_cmd='generate_ntp_conf'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
