#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nsswitch
# REQUIRE: root
# BEFORE: nsswitch

. /etc/rc.freenas

: ${PATH_NS_CONF:="/etc/nsswitch.conf"}


generate_nsswitch_conf()
{
	local ldap=0
	local ad=0
	local nis=0
	local ad_unix=0
	local hosts="files dns"
	local conf="${PATH_NS_CONF}"

	local p="compat"
	local g="compat"

	if dirsrv_enabled activedirectory || dirsrv_enabled nt4
	then
		ad="1"
		ad_unix=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
			SELECT
				ad_unix_extensions
			FROM
				services_activedirectory
			ORDER BY
				-id
			LIMIT 1
		")

	elif dirsrv_enabled ldap
	then
		ldap="1"

	elif dirsrv_enabled nis
	then
		nis="1"
	fi

	if [ "${ldap}" = "1" -o "${ad}" = "1" -o "${nis}" = "1" ]
	then
		p="files"
		g="files"

		if [ "${ad}" = "1" ]
		then
			if [ "${ad_unix}" = "1" ]
			then
				p="${p} ldap"
				g="${g} ldap"
			else
				p="${p} winbind"
				g="${g} winbind"
			fi
			hosts="${hosts} wins"

		elif [ "${ldap}" = "1" ]
		then
			p="${p} ldap"
			g="${g} ldap"

		elif [ "${nis}" = "1" ]
		then
			p="${p} nis"
			g="${g} nis"
			hosts="${hosts} nis"
		fi
	fi
	
	cat >"${conf}" <<-EOF
	group: ${g}
	hosts: ${hosts}
	networks: files
	passwd: ${p}
	shells: files
	services: files
	protocols: files
	rpc: files
EOF
	
	return 0
}

name="ix-nsswitch"
start_cmd='generate_nsswitch_conf'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
