#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nsswitch
# REQUIRE: root
# BEFORE: nsswitch

. /etc/rc.freenas

: ${PATH_NS_CONF:="/etc/nsswitch.conf"}

is_win2k8()
{
	local res=0

	while read version
	do
		if [ "${version}" = "windows2008" ]
		then
			res=1
			break
		fi

	done <<EOF
	$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		ad_windows_version
	FROM
		services_activedirectory
	")
EOF

	return ${res}
}

generate_nsswitch_conf()
{
	local ldap=0
	local ad=0
	local conf="${PATH_NS_CONF}"

	while read line
	do
		local var=$(echo "${line}"|cut -s -f1 -d'|')
		local val=$(echo "${line}"|cut -s -f2 -d'|')

		case "${var}" in
			activedirectory) ad="${val}" ;;
			ldap) ldap="${val}" ;;
		esac

	done <<EOF
	$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		srv_service,
		srv_enable

	FROM
		services_services

	WHERE
		srv_service IN (
			'ldap',
			'activedirectory'
	)")
EOF

	local p="compat"
	local g="compat"

	is_win2k8;
	local win2k8=$?

	if [ "${ldap}" = "1" -o "${ad}" = "1" ]
	then
		p="files"
		g="files"

		if [ "${ad}" = "1" -a "${win2k8}" = "0" ]
		then
			p="${p} winbind"
			g="${g} winbind"
		fi

		if [ "${ldap}" = "1" -o "${win2k8}" = "1" ]
		then
			p="${p} ldap"
			g="${g} ldap"
		fi
	fi
	
	cat<<-EOF>"${conf}"
	group: ${g}
	group_compat: nis
	hosts: files dns
	networks: files
	passwd: ${p}
	passwd_compat: nis
	shells: files
	services: compat
	services_compat: nis
	protocols: files
	rpc: files
EOF
	
	/etc/rc.d/nsswitch start
	return 0
}

name="ix-nsswitch"
start_cmd='generate_nsswitch_conf'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
