#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-nfsd
# REQUIRE: FILESYSTEMS
# BEFORE: nfsd mountd

. /etc/rc.subr

#
# TODO: For now we overwrite /etc/exports, it's desirable to teach mountd about another
# place so user can write their own entry.
#
generate_exports()
{
	local IFS=\|

	local mountpoint network alldirs nfsro quiet
        local maproot_user maproot_group mapall_user mapall_group
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT mp_path, nfs_network, nfs_alldirs, nfs_ro, nfs_quiet, nfs_maproot_user, nfs_maproot_group, nfs_mapall_user, nfs_mapall_group FROM sharing_nfs_share AS us LEFT OUTER JOIN storage_mountpoint AS mp ON us.nfs_path_id = mp.id ORDER BY us.id DESC" | \
	while read mountpoint network alldirs nfsro quiet maproot_user maproot_group mapall_user mapall_group ; do
		if [ -d "${mountpoint}" ]; then
			echo -n ${mountpoint}
			if [ "${alldirs}" = "1" ]; then
				echo -n " -alldirs"
			fi
			if [ "${nfsro}" = "1" ]; then
				echo -n " -ro"
			fi
			if [ "${quiet}" = "1" ]; then
				echo -n " -quiet"
			fi
                        if [ -n "${mapall_user}" -o -n "${mapall_group}" ]; then
				echo -n " -mapall=${mapall_user}:${mapall_group}"
                        else
                                if [ -n "${maproot_user}" -o -n "${maproot_group}" ]; then
				        echo -n " -maproot=${maproot_user}:${maproot_group}"
                                fi
			fi
			if [ -n "${network}" ]; then
                echo -n " "
				echo -n "${network}" | awk -F" " '{ if ($0 !~ /\//) print $0; else printf "-network %s",$0 }'
			fi
			echo
		fi
	done > /etc/exports
}

name="ix-nfsd"
start_cmd='generate_exports'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
