#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-pam
# REQUIRE: root
# REQUIRE: ix-nsswitch
# BEFORE: NETWORK

. /etc/rc.subr

: ${PAM_TEMPLATE_DIR:="/etc/ix/templates/pam.d"}
: ${PAM_DIR:="/etc/pam.d"}

generate_pam_service_file()
{
	local service="${1}"
	local winbind="${2}"
	local ldap="${3}"
	local krb5="${4}"
	local template
	local temp
	local file

	template="${PAM_TEMPLATE_DIR}/${service}"
	temp="/tmp/.tmp.${service}"
	file="${PAM_DIR}/${service}"

	if [ ! -f "${template}" ]
	then
		return 1
	fi

	awk -v ldap="${ldap}" -v winbind="${winbind}" -v krb5="${krb5}" '{
		if (/^#.*@@LDAP@@/ && ldap) {
			gsub("^#.*@@LDAP@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@WINBIND@@/ && winbind) {
			gsub("^#.*@@WINBIND@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@KRB5@@/ && krb5) {
			gsub("^#.*@@KRB5@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@MKHOMEDIR@@/ && (ldap || winbind || krb5)) {
			gsub("^#.*@@MKHOMEDIR@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@.*@@/) {
		} else {
			print $0;
		}
	}' < "${template}" > "${temp}"

	if [ -f "${temp}" ]
	then
		mv "${temp}" "${file}" >/dev/null 2>&1
		if [ "$?" != "0" ]
		then
			rm -f "${temp}"
			return 1
		fi
	fi

	return 0
}


generate_pam_files()
{
	local ldap=0
	local ad=0
	local ad_unix=0

	if [ ! -d "${PAM_TEMPLATE_DIR}" -o ! -d "${PAM_DIR}" ]
	then
		return 1
	fi

	if srv_enabled activedirectory
	then
		ad=1
                ad_unix=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
                        SELECT
                                ad_unix_extensions
                        FROM
                                services_activedirectory
                        ORDER BY
                                -id
                        LIMIT 1
                ")
		if [ "${ad_unix}" = "1" ]
		then
			ad=0
		fi

	elif srv_enabled ldap
	then
		ldap=1
	fi


	for service in $(ls "${PAM_TEMPLATE_DIR}")
	do
		generate_pam_service_file "${service}" "${ad}" "${ldap}" "${ad_unix}"
	done

	return 0
}

name="ix-pam"
start_cmd='generate_pam_files'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
