#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-pam
# REQUIRE: root
# BEFORE: NETWORK

. /etc/rc.subr

: ${PAM_TEMPLATE_DIR:="/etc/ix/templates/pam.d"}
: ${PAM_DIR:="/etc/pam.d"}

is_win2k8()
{
	local res=0

	while read version
	do
		if [ "${version}" = "windows2008" ]
		then
			res=1
			break
		fi

	done <<EOF
	$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		ad_windows_version
	FROM
		services_activedirectory
	")
EOF

	return ${res}
}

generate_pam_service_file()
{
	local service="${1}"
	local winbind="${2}"
	local ldap="${3}"
	local krb5="${4}"
	local template
	local temp
	local file

	template="${PAM_TEMPLATE_DIR}/${service}"
	temp="/tmp/.tmp.${service}"
	file="${PAM_DIR}/${service}"

	if [ ! -f "${template}" ]
	then
		return 1
	fi

	awk -v ldap="${ldap}" -v winbind="${winbind}" -v krb5="${krb5}" '{
		if (/^#.*@@LDAP@@/ && ldap) {
			gsub("^#.*@@LDAP@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@WINBIND@@/ && winbind) {
			gsub("^#.*@@WINBIND@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@KRB5@@/ && krb5) {
			gsub("^#.*@@KRB5@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@MKHOMEDIR@@/ && (winbind || ldap || krb5)) {
			gsub("^#.*@@MKHOMEDIR@@[^a-zA-Z0-9]+", "");
			print $0;
		} else if (/^#.*@@.*@@/) {
		} else {
			print $0;
		}
	}' < "${template}" > "${temp}"

	if [ -f "${temp}" ]
	then
		mv "${temp}" "${file}" >/dev/null 2>&1
		if [ "$?" != "0" ]
		then
			rm -f "${temp}"
			return 1
		fi
	fi

	return 0
}


generate_pam_files()
{
	local ldap=0
	local krb5=0
	local winbind=0

	if [ ! -d "${PAM_TEMPLATE_DIR}" -o ! -d "${PAM_DIR}" ]
	then
		return 1
	fi

	while read line
	do
		local var=$(echo "${line}"|cut -s -f1 -d'|')
		local val=$(echo "${line}"|cut -s -f2 -d'|')

		case "${var}" in
			activedirectory) winbind="${val}" ;;
			ldap) ldap="${val}" ;;
		esac

	done <<EOF
	$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		srv_service,
		srv_enable

	FROM
		services_services

	WHERE
		srv_service IN (
			'ldap',
			'activedirectory'
	)")
EOF
	is_win2k8;
	if [ "$?" = "1" ]
	then
		winbind=0
		krb5=1
	fi

	for service in $(ls "${PAM_TEMPLATE_DIR}")
	do
		generate_pam_service_file "${service}" \
			"${winbind}" "${ldap}" "${krb5}"
	done

	return 0
}

name="ix-pam"
start_cmd='generate_pam_files'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
