#!/bin/sh
#
# $FreeBSD$
#

# REQUIRE: ix-warden jail
# PROVIDE: ix-plugins

. /etc/rc.freenas


plugins_start()
{
	local args="$*"

	sql="
	SELECT
		plugin_name,
		plugin_jail,
		plugin_path,
		plugin_enabled,
		plugin_port
	FROM
		plugins_plugins
	"

	if [ -n "${args}" ]
	then
		names=""
		for p in ${args}
		do
			if [ -z "${names}" ]
			then
				names="'${p}'"
			else
				names="${names},'${p}'"
			fi
		done
		sql="${sql}
		WHERE	
			plugin_name
		IN
			($names)
		"
	fi


	local _ifs="${IFS}"
	IFS="|"

	local tmpfile="/var/tmp/...borked"
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "${sql}" | \
	while read name jail path enabled port
	do
		if [ "${enabled}" != "1" -a "${rc_force}" != "yes" ]
		then
			continue
		fi

		local jip=
		local ipv4=$(jail_get_ipv4 "${jail}")
		local ipv6=$(jail_get_ipv6 "${jail}")
		if [ -n "${ipv4}" ]
		then
			jail_get_ip_and_netmask "${ipv4}"
			jip="${JIP}"
		
		elif [ -n "${ipv6}" ]
		then
			jail_get_ip_and_netmask "${ipv6}"
			jip="${JIP}"
		fi

		local jid=$(jail_get_jid "${jail}")
		if [ -z "${jid}" ]
		then
			continue
		fi

		echo jexec ${jid} "${path}/control" start "${jip}" "${port}"
		jexec ${jid} "${path}/control" start "${jip}" "${port}" 2>/dev/null
		if [ "$?" != "0" ]
		then
			touch "${tmpfile}"
		fi
	done
	IFS="${_ifs}"

	local res=0
	if [ -f "${tmpfile}" ]
	then
		rm -f "${tmpfile}"
		res=1
	fi

	return ${res}
}

plugins_stop()
{
	local args="$*"

	sql="
	SELECT
		plugin_name,
		plugin_jail,
		plugin_path,
		plugin_enabled
	FROM
		plugins_plugins
	"

	if [ -n "${args}" ]
	then
		names=""
		for p in ${args}
		do
			if [ -z "${names}" ]
			then
				names="'${p}'"
			else
				names="${names},'${p}'"
			fi
		done
		sql="${sql}
		WHERE	
			plugin_name
		IN
			($names)
		"
	fi

	local _ifs="${IFS}"
	IFS="|"
	
	local tmpfile="/var/tmp/...borked"
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "${sql}" | \
	while read name jail path enabled 
	do
		if [ "${enabled}" != "0" -a "${rc_force}" != "yes" ]
		then
			continue
		fi

		local jid=$(jail_get_jid "${jail}")
		if [ -z "${jid}" ]
		then
			continue
		fi

		jexec ${jid} "${path}/control" stop 2>/dev/null
		if [ "$?" != "0" ]
		then
			touch "${tmpfile}"
		fi
	done
	IFS="${_ifs}"

	local res=0
	if [ -f "${tmpfile}" ]
	then
		rm -f "${tmpfile}"
		res=1
	fi

	return ${res}
}

plugins_status()
{
	local args="$*"

	sql="
	SELECT
		plugin_name,
		plugin_jail,
		plugin_path,
		plugin_enabled
	FROM
		plugins_plugins
	"

	if [ -n "${args}" ]
	then
		names=""
		for p in ${args}
		do
			if [ -z "${names}" ]
			then
				names="'${p}'"
			else
				names="${names},'${p}'"
			fi
		done
		sql="${sql}
		WHERE	
			plugin_name
		IN
			($names)
		"
	fi

	local _ifs="${IFS}"
	IFS="|"
	
	local tmpfile="/var/tmp/...sporked"
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "${sql}" | \
	while read name jail path enabled 
	do
		local jid=$(jail_get_jid "${jail}")
		if [ -z "${jid}" ]
		then
			continue
		fi

		jexec ${jid} "${path}/control" status 2>/dev/null
		if [ "$?" != "0" ]
		then
			touch "${tmpfile}"
		fi
	done
	IFS="${_ifs}"

	local res=0
	if [ -f "${tmpfile}" ]
	then
		rm -f "${tmpfile}"
		res=1
	fi

	return ${res}
}

name="ix-plugins"
start_cmd='plugins_start'
stop_cmd='plugins_stop'
status_cmd='plugins_status'
            
load_rc_config $name
run_rc_command $*
