#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-powerd
# REQUIRE: DAEMON
# BEFORE: powerd

. /etc/rc.subr

powerd_enable()
{
	/etc/rc.d/powerd onestart >/dev/null 2>&1
	return $?
}

powerd_disable()
{
	/etc/rc.d/powerd onestop >/dev/null 2>&1
	return $?
}

powerd_check()
{
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		adv_powerdaemon

	FROM
		system_advanced
	
	ORDER BY
		-id
	LIMIT 1
	" | \
	while read onoff
	do
		case "${onoff}" in
			0) res=$(powerd_disable) ;;
			1) res=$(powerd_enable) ;;
		esac
		break
	done

	return ${res}
}

name="ix-powerd"
start_cmd='powerd_check'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
