#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-syslogd
# REQUIRE: root
# BEFORE: syslogd

. /etc/rc.subr

generate_syslog_conf()
{
	local IFS="|"
	local f="
		stg_syslogserver
		"
	eval local $f
	local sf=$(var_to_sf $f)

	cp /conf/base/etc/syslog.conf /etc/syslog.conf

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		$sf

	FROM
		system_settings

	ORDER BY
		-id

	LIMIT 1
	" | \
	while eval read $f; do
		if [ -n "${stg_syslogserver}" ]; then
			echo -e "*.err;kern.warning;auth.notice;mail.crit\t/dev/console" > /etc/syslog.conf
			echo -e "*.err;kern.warning;auth.notice;mail.crit\t/var/log/messages" > /etc/syslog.conf
			echo -e "*.*\t@${stg_syslogserver}" >> /etc/syslog.conf
		fi
	done
}

name="ix-syslogd"
start_cmd='generate_syslog_conf'
stop_cmd=':'
        
load_rc_config $name
run_rc_command "$1"
