#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-samba
# REQUIRE: FILESYSTEMS mountlate
# REQUIRE: ix-pam
# BEFORE: smbd

. /etc/rc.freenas

: ${SMB_CONF:="/usr/local/etc/smb.conf"}
AVAHI_SERVICES_DIR=/usr/local/etc/avahi/services
: ${AVAHI_CIFS_SERVICE:=$AVAHI_SERVICES_DIR/cifs.service}

is_within_zfs() {

	local mp share_dev
	share_dev=$(stat -f "%d" "$1")
	zfs list -H -o mountpoint | grep -v '^-' | while read mp; do
		if [ "${share_dev}" -eq "`stat -f "%d" "${mp}"`" ]; then
			echo "zfsacl"
			return 0
		fi
	done
	return 1

}

generate_smbconf()
{
	local IFS=\|

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		cifs_srv_authmodel,
		cifs_srv_workgroup,
		cifs_srv_description,
		cifs_srv_doscharset,
		cifs_srv_unixcharset,
		cifs_srv_loglevel,
		cifs_srv_localmaster,
		cifs_srv_timeserver,
		cifs_srv_guest,
		cifs_srv_guestok,
		cifs_srv_guestonly,
		cifs_srv_filemask,
		cifs_srv_dirmask,
		cifs_srv_largerw,
		cifs_srv_sendfile,
		cifs_srv_easupport,
		cifs_srv_dosattr,
		cifs_srv_nullpw,
		cifs_srv_unixext,
		cifs_srv_aio_enable,
		cifs_srv_aio_rs,
		cifs_srv_aio_ws,
		cifs_srv_homedir_enable,
		cifs_srv_homedir_browseable_enable,
		cifs_srv_homedir,
		(
			SELECT
				srv_enable
			FROM
				services_services
			WHERE
				srv_service = 'activedirectory'
			ORDER BY
				-id
			LIMIT 1
		) as cifs_srv_ad_enable,
		(
			SELECT
				srv_enable
			FROM
				services_services
			WHERE
				srv_service = 'ldap'
			ORDER BY
				-id
			LIMIT 1
		) as cifs_srv_ldap_enable,
		ad_domainname,
		ad_workgroup,
		ad_allow_trusted_doms,
		ad_adminname,
		ad_adminpw,
		ldap_hostname,
		ldap_basedn,
		ldap_anonbind,
		ldap_rootbasedn,
		ldap_rootbindpw,
		ldap_pwencryption,
		ldap_ssl,
		ldap_usersuffix,
		ldap_groupsuffix,
		ldap_passwordsuffix,
		ldap_machinesuffix

	FROM
		services_cifs

	JOIN services_ldap ON (1 = 1)
	JOIN services_activedirectory ON (1 = 1 )

	ORDER BY
		-services_cifs.id,
		-services_ldap.id,
		-services_activedirectory.id

	LIMIT 1
	" | \
	while read -r authmodel workgroup cifs_description doscharset \
		unixcharset loglevel localmaster timeserver guest guestok guestonly \
		cifs_filemask cifs_dirmask \
		largerw sendfile easupport dosattr nullpw unixext \
		cifs_aio_enable cifs_aio_rs cifs_aio_ws cifs_homedir \
		cifs_homedir_browseable cifs_homedir_mp ad_enable ldap_enable \
		ad_domainname ad_workgroup ad_allow_trusted_doms \
		ad_adminname ad_adminpw ldap_hostname ldap_basedn ldap_anonbind \
		ldap_rootbasedn ldap_rootbindpw ldap_pwencryption ldap_ssl \
		ldap_usersuffix ldap_groupsuffix ldap_passwordsuffix ldap_machinesuffix;
	do
		# Default user and group is ftp:ftp
		if [ -z "${guest}" ]; then
			guest=ftp
		fi

		cat<<-EOF
		[global]
		    encrypt passwords = yes
		    dns proxy = no
		    strict locking = no
		    read raw = yes
		    write raw = yes
		    oplocks = yes
		    max xmit = 65535
		    deadtime = 15
		    display charset = LOCALE
		    max log size = 10
		    syslog only = yes
		    syslog = yes
		    load printers = no
		    printing = bsd
		    printcap name = /dev/null
		    disable spoolss = yes
		    smb passwd file = /var/etc/private/smbpasswd
		    private dir = /var/etc/private
		    getwd cache = yes
		    guest account = ${guest}
		    map to guest = Bad Password
EOF
		if [ "${guestok}" = "1" ]; then
			echo "    guest ok = yes"
		else
			echo "    guest ok = no"
		fi
		if [ "${guestonly}" = "1" ]; then
			echo "    guest only = yes"
		fi

		if [ "${ad_enable}" = "0" ]; then
			echo "    workgroup = ${workgroup}"
		fi

		if [ -n "${cifs_description}" ]; then
			echo "    server string = ${cifs_description}"
		fi

		if [ "${sendfile}" = "1" ]; then
			echo "    use sendfile = yes"
		fi

		if [ "${largerw}" = "0" ]; then
			echo "    large readwrite = no"
		fi

		if [ "${easupport}" = "1" ]; then
			echo "    ea support = yes"
		fi

		if [ "${dosattr}" = "1" ]; then
			echo "    store dos attributes = yes"
		fi

		#Default is yes
		if [ "${unixext}" = "0" ]; then
			echo "    unix extensions = no"
		fi

		if [ "${localmaster}" = "1" -a "${ad_enable}" !=  "1" ]; then
			echo "    local master = yes"
		fi

		if [ "${timeserver}" = "1" ]; then
			echo "    time server = yes"
		fi

		if [ "${nullpw}" = "1" ]; then
			echo "    null passwords = yes"
		fi

		if [ "${ldap_enable}" = "1" ]; then
			echo "    security = user"

			if [ -n "${ldap_hostname}" ]; then
				echo "    passdb backend = ldapsam:ldap://${ldap_hostname}"
			fi

			if [ -n "${ldap_rootbasedn}" ]; then
			    echo "    ldap admin dn = ${ldap_rootbasedn}"
			fi

			if [ -n "${ldap_rootbindpw}" ]; then
				mount -u /
				/usr/local/bin/smbpasswd -w "${ldap_rootbindpw}" >/dev/null 2>&1
				mount -ur /
			fi

			if [ -n "${ldap_basedn}" ]; then
			    echo "    ldap suffix = ${ldap_basedn}"
			fi

			if [ -n "${ldap_usersuffix}" ]; then
			    echo "    ldap user suffix = ${ldap_usersuffix}"
			fi

			if [ -n "${ldap_groupsuffix}" ]; then
			    echo "    ldap group suffix = ${ldap_groupsuffix}"
			fi

			if [ -n "${ldap_machinesuffix}" ]; then
			    echo "    ldap machine suffix = ${ldap_machinesuffix}"
			fi

			if [ "${ldap_ssl}" = "start_tls" ]; then
				echo "    ldap ssl = start tls"
			else
				echo "    ldap ssl = off"
			fi

			cat<<-EOF
			    ldap replication sleep = 1000
			    ldap passwd sync = yes
			    #ldap debug level = 1
			    #ldap debug threshold = 1
			    ldapsam:trusted = yes
			    idmap uid = 10000-39999
			    idmap gid = 10000-39999
EOF

		elif [ "${ad_enable}" = "1" ]; then
			local domain=$(echo "${ad_domainname}"|tr a-z A-Z)
			local ad_workgroup="${ad_workgroup}"

			AD_init
			mkdir -p ${FREENAS_CACHEDIR}/.samba

			# wins server ?
			# template??
			# admin users??
			# valid users??
			# acls?

			cat<<-EOF
			    #security = ADS
			    realm = ${domain}
			    workgroup = ${ad_workgroup}	
			    client use spnego = yes
			    cache directory = ${FREENAS_CACHEDIR}/.samba

			    wins server = $(AD_get dcname)
			    password server = $(AD_get dcname)

			    local master = no
			    domain master = no
			    preferred master = no

			    inherit acls = yes
			    acl compatibility = auto
			    acl check permissions = true
			    acl map full control = true
			    dos filemode = yes

			    idmap uid = 10000-19999
			    idmap gid = 10000-19999
			    idmap config ${ad_workgroup}: backend = rid
			    idmap config ${ad_workgroup}: range = 20000-20000000

			    winbind cache time = 10
			    winbind offline logon = yes
			    winbind enum users = yes
			    winbind enum groups = yes
			    winbind nested groups = yes
			    winbind use default domain = no
			    winbind refresh tickets = yes
			    # Enable in the global settings if you want to manage
			    # files in multitiered AD deployments. This doesn't work
			    # in all configurations. Caveat emptor.
EOF
			if [ "${ad_allow_trusted_doms}" = "1" ]; then
				echo -e "\t\t\t    allow trusted domains = yes"
			else
				echo -e "\t\t\t    allow trusted domains = no"
			fi

			cat<<-EOF
			    template shell = /bin/sh
			    template homedir = /home/%D/%U

EOF
		else
			echo "    security = ${authmodel}"
			if [ "${authmodel}" = "share" ]; then
				cat<<-EOF
			    force user = ${guest}
			    force group = ${guest}
			    passdb backend = tdbsam:/var/etc/private/passdb.tdb
EOF
			fi
		fi

		if [ -z "${cifs_filemask}" ]; then
			cifs_filemask=0666
		fi

		echo "    create mask = ${cifs_filemask}"

		if [ -z "${cifs_dirmask}" ]; then
			cifs_dirmask=0777
		fi

		echo "    create mask = ${cifs_filemask}"
		echo "    directory mask = ${cifs_dirmask}"
		echo "    client ntlmv2 auth = yes"

		if [ -n "${doscharset}" ]; then
			echo "    dos charset = ${doscharset}"
		fi

		if [ -n "${unixcharset}" ]; then
			echo "    unix charset = ${unixcharset}"
		fi

		if [ -n "${loglevel}" -a "${loglevel}" != "True" ]; then
			echo "    log level = ${loglevel}"
		fi

		if [ "${cifs_aio_enable}" = "1" ]; then
			echo "    aio read size = ${cifs_aio_rs}"
			echo "    aio write size = ${cifs_aio_ws}"
		fi

	    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	    SELECT
	    	cifs_srv_smb_options
	    FROM
	    	services_cifs
	    ORDER BY
	    	-id
	    LIMIT 1
	    "

		if [ "${cifs_homedir}" = "1" ]; then

			if [ "${ad_enable}" = "1" ]; then
				valid_users="%D/%U"
			else
				valid_users="%U"
			fi
			cifs_homedir_path="$cifs_homedir_mp/$valid_users"

			cat<<-EOF
			[homes]
			    comment = Home Directories
			    valid users = ${valid_users}
			    writable = yes
EOF
                        if [ "${cifs_homedir_browseable}" = "1" ]; then
                                echo "    browseable = yes"
                        else
                                echo "    browseable = no"
                        fi
                        if [ "${cifs_homedir_mp}" != "" ]; then
                                echo "    path = ${cifs_homedir_path}"
                        fi
		fi


	done

	echo
}

generate_exports()
{
	local IFS="|"

	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "
	SELECT
		cifs_name,
		cifs_comment,
		cifs_path,
		cifs_ro,
		cifs_browsable,
		cifs_inheritowner,
		cifs_inheritperms,
		cifs_recyclebin,
		cifs_showhiddenfiles,
		cifs_guest,
		cifs_guestok,
		cifs_guestonly,
		cifs_hostsallow,
		cifs_hostsdeny
	FROM
		sharing_cifs_share AS cs

	ORDER BY
		cs.id ASC
	" | \
	while read -r name comment mountpoint cifsro browsable inheritowner inheritperms \
		recyclebin showhiddenfiles guest guestok guestonly hostsallow hostsdeny;
	do
		if [ -d "${mountpoint}" ]; then

			fs=$(zfs list -H -o mountpoint,name|grep -E "${mountpoint}	"|awk '{print $2}')
			if [ -n "${fs}" ]; then
				task_rint=`${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT task_ret_count FROM storage_task WHERE task_filesystem='${fs}' LIMIT 1;"`
				task_runit=`${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT task_ret_unit FROM storage_task WHERE task_filesystem=\"${fs}\" LIMIT 1;" | /usr/bin/cut -c1`
				if [ -n "${task_rint}" ]; then
					vfsobj_shadow=" shadow_copy2"
				fi
			fi

			echo "[${name}]"
			echo "    path = ${mountpoint}"
			echo "    printable = no"
			echo "    veto files = /.snap/.windows/"
			if [ -n "${comment}" ]; then
				echo "    comment = ${comment}"
			fi
			if [ "${cifsro}" = "0" ]; then
				echo "    writeable = yes"
			else
				echo "    writeable = no"
			fi
			if [ "${browsable}" = "0" ]; then
				echo "    browseable = no"
			else
				echo "    browseable = yes"
			fi

			if [ "${inheritowner}" = "1" ]; then
				echo "    inherit owner = yes"
			else
				echo "    inherit owner = no"
			fi

			#
			#    This should always be set to "yes" if permission changes
			#    on windows are desired.
			#
			if [ "${inheritperms}" = "1" ]; then
				echo "    inherit permissions = yes"
			else
				echo "    inherit permissions = no"
			fi

			zfsacl=$(is_within_zfs "${mountpoint}")
			if [ "${recyclebin}" = "1" ]; then
			cat<<-EOF
			    vfs objects = ${zfsacl} recycle${vfsobj_shadow}
			    recycle:repository = .recycle/%U
			    recycle:keeptree = yes
			    recycle:versions = yes
			    recycle:touch = yes
			    recycle:directory_mode = 0777
			    recycle:subdir_mode = 0700
EOF
			else
				echo "    vfs objects = ${zfsacl} ${vfsobj_shadow}"
			fi
			if [ -n "${task_rint}" ]; then
			cat <<-EOF
			    shadow: snapdir = .zfs/snapshot
			    shadow: sort = desc
			    shadow: localtime = yes
			    shadow: format = auto-%Y%m%d.%H%M-${task_rint}${task_runit}
EOF
			fi
			if [ "${showhiddenfiles}" = "1" ]; then
				echo "    hide dot files = no"
			fi
			if [ -n "${hostsallow}" ]; then
				echo "    hosts allow = ${hostsallow}"
			fi
			if [ -n "${hostsdeny}" ]; then
				echo "    hosts deny = ${hostsdeny}"
			fi
			if [ "${guestok}" = "1" -o "${guestonly}" = "1" ]; then
				echo "    guest account = ${guest}"
			fi
			if [ "${guestok}" = "1" ]; then
				echo "    guest ok = yes"
			else
				echo "    guest ok = no"
			fi
			if [ "${guestonly}" = "1" ]; then
				echo "    guest only = yes"
			fi
			cat<<-EOF
			    inherit acls = Yes
			    map archive = No
			    map readonly = no
			    nfs4:mode = special
			    nfs4:acedup = merge
			    nfs4:chown = yes
EOF

			${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT cifs_auxsmbconf FROM sharing_cifs_share WHERE cifs_name=\"${name}\" ORDER BY -id LIMIT 1"
			echo
		fi
	done
}

generate_smb_tdb()
{
	local tmp
	tmp=$(mktemp /tmp/tmp.XXXXXX)
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT bsdusr_smbhash FROM account_bsdusers WHERE bsdusr_smbhash LIKE '%:%:XXXX%' AND NOT bsdusr_unixhash LIKE '*LOCKED*%'" > $tmp
	rm -f /var/etc/private/passdb.tdb
	/usr/local/bin/pdbedit -d 0 -i smbpasswd:$tmp \
	    -e tdbsam:/var/etc/private/passdb.tdb >/dev/null
	rm -f $tmp
}

generate_avahi_cifs_service()
{
	local samba_enabled

	srv_enabled cifs && \
	    [ "x$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT cifs_srv_zeroconf FROM services_cifs")" = x1 ]
	if [ $? -eq 0 ]; then
		cat > ${AVAHI_CIFS_SERVICE} <<EOF
<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">CIFS Shares on %h</name>
  <service>
      <type>_smb._tcp</type>
      <port>445</port>
  </service>
  <service>
      <type>_device-info._tcp</type>
      <port>0</port>
    <txt-record>model=Xserve</txt-record>
  </service>
</service-group>
EOF
	else
		rm -f ${AVAHI_CIFS_SERVICE}
	fi
}

generate_smb_config()
{
	mkdir -p /var/etc/private
	chmod 700 /var/etc/private
	generate_smb_tdb
	generate_smbconf > ${SMB_CONF}
	generate_exports >> ${SMB_CONF}
	generate_avahi_cifs_service
}

name="ix-samba"
start_cmd='generate_smb_config'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
