#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-sercons
# REQUIRE: FILESYSTEMS

. /etc/rc.subr

update_sercons()
{
	tmp=$(mktemp /tmp/tmp.XXXXXX)
	local sercons=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialconsole FROM system_advanced ORDER BY id DESC LIMIT 1")
	local serspeed=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT adv_serialspeed FROM system_advanced ORDER BY id DESC LIMIT 1")
	local bc=/boot.config

	case $sercons in
	0)
		if [ -f ${bc} ]; then
			mount -uw -onoatime /
			rm -f ${bc}
			mount -ur /
		fi
		;;
	1)
		echo "-Dh -S${serspeed}" > ${tmp}
		if [ -f ${bc} ] ; then
			if ! [ $(sha256 -q ${tmp}) == $(sha256 -q ${bc}) ] ; then
				mount -uw -onoatime /
				mv ${tmp} ${bc}
				mount -ur /
			fi
		else
			mount -uw -onoatime /
			mv ${tmp} ${bc}
			mount -ur /
		fi
		;;
        esac
}

name="ix-sercons"
start_cmd='update_sercons'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
