#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-samba
# REQUIRE: FILESYSTEMS
# BEFORE: samba

. /etc/rc.subr

generate_smbconf()
{
	local IFS=\|

	local netbiosname workgroup cifs_description doscharset unixcharset loglevel localmaster timeserver guest cifs_filemask cifs_dirmask sendbuffer recvbuffer largerw sendfile easupport dosattr nullpw cifs_aio_enable cifs_aio_rs cifs_aio_ws cifs_homedir smb_options
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT cifs_srv_netbiosname, cifs_srv_workgroup, cifs_srv_description, cifs_srv_doscharset, cifs_srv_unixcharset, cifs_srv_loglevel, cifs_srv_localmaster, cifs_srv_timeserver, cifs_srv_guest, cifs_srv_filemask, cifs_srv_dirmask, cifs_srv_sendbuffer, cifs_srv_recvbuffer, cifs_srv_largerw, cifs_srv_sendfile, cifs_srv_easupport, cifs_srv_dosattr, cifs_srv_nullpw, cifs_srv_aio_enable, cifs_srv_aio_rs, cifs_srv_aio_ws, cifs_srv_homedir_enable FROM services_cifs ORDER BY id DESC LIMIT 1" | \
	while read netbiosname workgroup cifs_description doscharset unixcharset loglevel localmaster timeserver guest cifs_filemask cifs_dirmask sendbuffer recvbuffer largerw sendfile easupport dosattr nullpw cifs_aio_enable cifs_aio_rs cifs_aio_ws cifs_homedir; do
		echo '
[global]
encrypt passwords = yes
dns proxy = no
strict locking = no
read raw = yes
write raw = yes
oplocks = yes
max xmit = 65535
deadtime = 15
display charset = LOCALE
max log size = 10
syslog only = yes
syslog = yes
load printers = no
printing = bsd
printcap name = /dev/null
disable spoolss = yes
smb passwd file = /var/etc/private/smbpasswd
private dir = /var/etc/private
getwd cache = yes'
		echo ${guest} > /tmp/ix-samba
		echo "netbios name = ${netbiosname}"
		echo "workgroup = ${workgroup}"
		if [ -n "${cifs_description}" ]; then
			echo "server string = ${cifs_description}"
		fi
		if [ "${sendfile}" = "1" ]; then
			echo "use sendfile = yes"
		fi
		if [ "${largerw}" = "0" ]; then
			echo "large readwrite = no"
		fi
		if [ "${easupport}" = "1" ]; then
			echo "ea support = yes"
		fi
		if [ "${dosattr}" = "1" ]; then
			echo "store dos attributes = yes"
		fi
		if [ "${localmaster}" = "1" ]; then
			echo "local master = yes"
		fi
		if [ "${timeserver}" = "1" ]; then
			echo "time server = yes"
		fi
		if [ "${nullpw}" = "1" ]; then
			echo "null passwords = yes"
		fi
		# Default user and group is ftp:ftp
		if [ -z "${guest}" ]; then
			guest=ftp
		fi
		# For now, we only support "SHARE" model.
		# TODO: user group; other models;
		echo "security = share"
		echo "guest account = ${guest}"
		echo "force user = ${guest}"
		echo "force group = ${guest}"
		echo "passdb backend = smbpasswd"
		if [ -z "${cifs_filemask}" ]; then
			cifs_filemask=0666
		fi
		echo "create mask = ${cifs_filemask}"
		if [ -z "${cifs_dirmask}" ]; then
			cifs_dirmask=0777
		fi
		echo "create mask = ${cifs_filemask}"
		echo "directory mask = ${cifs_dirmask}"

		if [ -n "${doscharset}" ]; then
			echo "dos charset = ${doscharset}"
		fi
		if [ -n "${unixcharset}" ]; then
			echo "unix charset = ${unixcharset}"
		fi
		if [ -n "${loglevel}" ]; then
			echo "log level = ${loglevel}"
		fi
		if [ -n "${sendbuffer}" -o -n "${recvbuffer}" ]; then
			echo -n "socket options ="
			if [ -n "${sendbuffer}" ]; then
				echo -n " SO_SNDBUF=${sendbuffer}"
			fi
			if [ -n "${recvbuffer}" ]; then
				echo -n " SO_RCVBUF=${recvbuffer}"
			fi
			echo
		fi
		if [ "${cifs_aio_enable}" = "1" ]; then
			echo "aio read size = ${cifs_aio_rs}"
			echo "aio write size = ${cifs_aio_ws}"
		fi
		if [ "${cifs_homedir}" = "1" ]; then
			echo '
[homes]
comment = Home Directories
browseable = yes
valid users = %S
writable = yes'
		fi
	done
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT cifs_srv_smb_options FROM services_cifs ORDER BY id DESC LIMIT 1"
	echo
}

generate_exports()
{
	local IFS=\|

	local name comment mountpoint cifsro browsable inheritperms recyclebin showhiddenfiles hostsallow hostsdeny auxsmbconf
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT cifs_name, cifs_comment, mp_path, cifs_ro, cifs_browsable, cifs_inheritperms, cifs_recyclebin, cifs_showhiddenfiles, cifs_hostsallow, cifs_hostsdeny, cifs_auxsmbconf FROM sharing_cifs_share AS cs LEFT OUTER JOIN storage_mountpoint AS mp ON cs.cifs_path_id = mp.id ORDER BY cs.id ASC" | \
	while read name comment mountpoint cifsro browsable inheritperms recyclebin showhiddenfiles hostsallow hostsdeny auxsmbconf; do
		chmod 777 ${mountpoint}
		chown `cat /tmp/ix-samba` ${mountpoint}
		rm /tmp/ix-samba
		echo "[${name}]"
		echo "path = ${mountpoint}"
		echo "printable = no"
		echo "veto files = /.snap/"
		if [ -n "${comment}" ]; then
			echo "comment = ${comment}"
		fi
		if [ "${cifsro}" = "0" ]; then
			echo "writeable = yes"
		else
			echo "writeable = no"
		fi
		if [ "${browsable}" = "0" ]; then
			echo "browseable = no"
		else
			echo "browseable = yes"
		fi
		if [ "${inheritperms}" = "1" ]; then
			echo "inherit permissions = yes"
		else
			echo "inherit permissions = no"
		fi
		if [ "${recyclebin}" = "1" ]; then
			echo "vfs objects = recycle"
			echo "recycle:repository = .recycle/%U"
			echo "recycle:keeptree = yes"
			echo "recycle:versions = yes"
			echo "recycle:touch = yes"
			echo "recycle:directory_mode = 0777"
			echo "recycle:subdir_mode = 0700"
		fi
		if [ "${showhiddenfiles}" = "1" ]; then
			echo "hide dot files = no"
		fi
		if [ -n "${hostsallow}" ]; then
			echo "hosts allow = ${hostsallow}"
		fi
		if [ -n "${hostsdeny}" ]; then
			echo "hosts deny = ${hostsdeny}"
		fi
		# TODO: Other models
		echo "guest ok = yes"
		if [ -n "${auxsmbconf}" ]; then
			echo ${auxsmbconf}
		fi
	done
	echo
}

generate_smb_config()
{
	generate_smbconf > /usr/local/etc/smb.conf
	generate_exports >> /usr/local/etc/smb.conf
	mkdir -p /var/etc/private
}

name="ix-nfsd"
start_cmd='generate_smb_config'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
