#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-sshd
# REQUIRE: FILESYSTEMS
# BEFORE: sshd

. /etc/rc.subr

AVAHI_SERVICES_DIR=/usr/local/etc/avahi/services/
: ${AVAHI_SFTP_SERVICE=$AVAHI_SERVICES_DIR/sftp-ssh.service}
: ${AVAHI_SSH_SERVICE=$AVAHI_SERVICES_DIR/ssh.service}

#
# TODO: this is really just a place holder for the moment....
#
generate_sshd()
{
    local IFS=\|
    local f="ssh_tcpport ssh_rootlogin ssh_passwordauth ssh_tcpfwd ssh_compression"
    eval local $f
    local cmd sf cfg
    sf=$(echo $f | sed -e 's/ /, /g')
    cfg=/etc/ssh/sshd_config

    sshd_enabled=$(${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT srv_enable from services_services where srv_service = 'ssh'" 2>/dev/null || echo 0)
    for file in $AVAHI_SFTP_SERVICE $AVAHI_SSH_SERVICE; do
        if [ "x$sshd_enabled" = x1 ]; then
	    cat > $file <<EOF
<?xml version="1.0" standalone="no"?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">
<service-group>
  <name replace-wildcards="yes">%h</name>
  <service>
    <type>_sftp-ssh._tcp</type>
    <port>22</port>
  </service>
</service-group>
EOF
	else
	    rm -f $file
        fi
    done

    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM services_ssh ORDER BY -id LIMIT 1" | \
	while eval read $f; do
	    cat > $cfg <<EOF
Protocol 2
UseDNS no
Subsystem       sftp    /usr/libexec/sftp-server
ChallengeResponseAuthentication no
ClientAliveCountMax 3
ClientAliveInterval 15
EOF
	    if [ "$ssh_tcpport" -gt 0 ]; then
		echo "Port $ssh_tcpport" >> $cfg
	    fi
	    if [ "$ssh_rootlogin" = 1 ]; then
		echo "PermitRootLogin yes" >> $cfg
	    else
		echo "PermitRootLogin without-password" >> $cfg
	    fi
	    if [ "$ssh_tcpfwd" = 1 ]; then
		echo "AllowTcpForwarding yes" >> $cfg
	    else
		echo "AllowTcpForwarding no" >> $cfg
	    fi
	    if [ "$ssh_compression" = 1 ]; then
		echo "Compression delayed" >> $cfg
	    else
		echo "Compression no" >> $cfg
	    fi
	    if [ "$ssh_passwordauth" = 1 ]; then
		echo "PasswordAuthentication yes" >> $cfg
	    fi
	    ssh_pubkeyauth=1		# Missing in schema
	    if [ "$ssh_pubkeyauth" = 1 ]; then
		echo "PubkeyAuthentication yes" >> $cfg
	    fi
    done
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT ssh_options FROM services_ssh ORDER BY -id LIMIT 1" >> $cfg
    # Generate a passwordless key-pair for automatic replication
    if [ ! -d /data/ssh ]; then
	mkdir -m 755 /data/ssh
    fi
    if [ ! -e /data/ssh/replication ]; then
	/usr/bin/ssh-keygen -qt rsa -N "" -C "Key for replication" -b 2048 -f /data/ssh/replication
    fi
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT ssh_remote_hostkey FROM storage_replremote" > /etc/ssh/ssh_known_hosts
}

name="ix-sshd"
start_cmd='generate_sshd'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
