#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-sysctl
# REQUIRE: ix-update sysctl
# BEFORE: ix-zfs

. /etc/rc.subr

set_autotune_sysctls()
{
	local IFS="
"
	local autotune

	export PATH=$PATH:/usr/local/bin:/usr/local/sbin

	autotune=/usr/local/bin/autotune
	if [ -x $autotune ]; then

		$autotune \
			--kernel-reserved=1073741824 \
			--userland-reserved=2417483648 \
			--conf sysctl

	fi
}

set_user_sysctls()
{
	local IFS="|"
	local f="sysctl_mib sysctl_value"
	eval local $f
	local sf=$(var_to_sf $f)

	# Generate sysctls
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
		"SELECT $sf FROM system_sysctl WHERE sysctl_enabled = 1 ORDER BY id" | \
	while eval read -r $f; do
		sysctl ${sysctl_mib}="${sysctl_value}"
	done
}

start_sysctl()
{
	set_autotune_sysctls
	set_user_sysctls
}

reload_sysctl()
{
	set_user_sysctls
}

name="ix-sysctl"
start_cmd='start_sysctl'
reload_cmd='reload_sysctl'
stop_cmd=':'
extra_commands='reload'

load_rc_config $name
run_rc_command "$1"
