#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-ups
# REQUIRE: FILESYSTEMS
# BEFORE: nut

. /etc/rc.subr

UPS_CONFPATH="/usr/local/etc/nut"
UPS_CONFIG="${UPS_CONFPATH}/ups.conf"
UPS_MONFILE="${UPS_CONFPATH}/upsmon.conf"
UPS_USERSFILE="${UPS_CONFPATH}/upsd.users"
UPS_DAEMONFILE="${UPS_CONFPATH}/upsd.conf"
UPS_VARPATH="/var/db/nut"

generate_ups()
{
    local IFS=\|
    local f="ups_identifier ups_driver ups_port ups_options ups_description ups_shutdown ups_shutdowntimer ups_rmonitor ups_emailnotify ups_toemail ups_subject"
    eval local $f
    local cmd sf cfg
    sf=$(echo $f | sed -e 's/ /, /g')
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM services_ups ORDER BY -id LIMIT 1" | \
	while eval read $f; do
	    cat <<EOF
[${ups_identifier}]
    driver = $(echo "${ups_driver}"|tr -s " " "\n")
    port = ${ups_port}
    desc = "${ups_description}"
    ${ups_options}
EOF
    done
}

generate_upsmon()
{
    local IFS=\|
    local f="ups_identifier ups_driver ups_port ups_options ups_description ups_shutdown ups_shutdowntimer ups_rmonitor ups_emailnotify ups_toemail ups_subject"
    eval local $f
    local cmd sf cfg
    sf=$(echo $f | sed -e 's/ /, /g')
    ${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} \
	"SELECT $sf FROM services_ups ORDER BY -id LIMIT 1" | \
	while eval read $f; do
        cat > /var/tmp/nut_notify.sh << EOF
#!/bin/bash
echo \$1 | mail -s "\$(echo "${ups_subject}"|sed "s/%d/\$(date)/"|sed "s/%h/\$(hostname)/")" "${ups_toemail}"
EOF
        chmod +x /var/tmp/nut_notify.sh
	    cat <<EOF
MONITOR ${ups_identifier} 1 upsmon fixmepass master
NOTIFYCMD "/var/tmp/nut_notify.sh"
EOF
    echo -n "NOTIFYFLAG ONBATT SYSLOG+WALL"
    if [ "${ups_emailnotify}" -eq 1 ]; then
        echo "+EXEC"
    fi
    echo "SHUTDOWNCMD \"/sbin/shutdown -p now\""
    done
}

generate_upsdusers()
{

	    cat <<EOF
[upsmon]
    password = fixmepass
    upsmon master
EOF

}

generate_upsd()
{

	    cat <<EOF
LISTEN 127.0.0.1
EOF

}

generate_ups_conf()
{
    mkdir -p ${UPS_CONFPATH}
    mkdir -p ${UPS_VARPATH}
    generate_ups > ${UPS_CONFIG}
    generate_upsmon > ${UPS_MONFILE}
    generate_upsdusers > ${UPS_USERSFILE}
    generate_upsd > ${UPS_DAEMONFILE}
    chown root:uucp ${UPS_VARPATH} ${UPS_CONFIG} ${UPS_MONFILE} ${UPS_USERSFILE} ${UPS_DAEMONFILE}
    chmod 440 ${UPS_CONFIG} ${UPS_MONFILE} ${UPS_USERSFILE} ${UPS_DAEMONFILE}
    chmod g=rwx,o= ${UPS_VARPATH}
}

name="ix-ups"
start_cmd='generate_ups_conf'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
