#!/bin/sh
#
# $FreeBSD$
#

# PROVIDE: ix-zfs
# REQUIRE: hostid mountcritlocal
# BEFORE: zfs

. /etc/rc.subr

#
# Generate fstab right before mountlate.
#
import_zpools()
{
	local IFS=\|
	local volumename guid
	if [ ! -d "/data/zfs" ]; then
		mkdir /data/zfs || true
	fi
	${FREENAS_SQLITE_CMD} ${FREENAS_CONFIG} "SELECT vol_name, vol_guid FROM storage_volume WHERE vol_fstype = 'ZFS'" | \
	while read -r volumename guid; do
		if [ -n "${guid}" ]; then
			/sbin/zpool import -o cachefile=none -R /mnt -f ${guid}
		else
			/sbin/zpool import -o cachefile=none -R /mnt -f ${volumename}
		fi
		/sbin/zpool set cachefile=/data/zfs/zpool.cache ${volumename}
		# Fixup mountpoints
		[ -d /mnt/mnt ] && /sbin/zfs inherit -r mountpoint ${volumename}
	done
}

name="ix-zfs"
start_cmd='import_zpools'
stop_cmd=':'

load_rc_config $name
run_rc_command "$1"
