# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-02 09:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Peer name')),
                ('description', models.CharField(max_length=250, verbose_name='Peer description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSH_Peer',
            fields=[
                ('peer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='peers.Peer')),
                ('ssh_port', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65536)], verbose_name='SSH remote peer port number')),
                ('ssh_remote_hostname', models.CharField(max_length=120, verbose_name='Remote hostname')),
                ('ssh_remote_user', models.CharField(max_length=120, verbose_name='Remote Dedicated User')),
                ('ssh_remote_hostkey', models.CharField(max_length=2048, verbose_name='Remote hostkey')),
            ],
            options={
                'abstract': False,
            },
            bases=('peers.peer',),
        ),
    ]
