# Created by: John Hixson <john@ixsystems.com>
# $FreeBSD: head/www/py-django-json-rpc/Makefile 412351 2016-04-01 14:33:55Z mat $

PORTNAME=	django-json-rpc
PORTVERSION=	0.7.2
CATEGORIES=	www python
MASTER_SITES=	CHEESESHOP
PKGNAMEPREFIX=	${PYTHON_PKGNAMEPREFIX}

MAINTAINER=	john@ixsystems.com
COMMENT=	Simple JSON-RPC implementation for Django

RUN_DEPENDS=	${PYTHON_PKGNAMEPREFIX}django110>0:www/py-django110

LICENSE=	MIT

USES=		python
USE_PYTHON=	distutils autoplist

.include <bsd.port.mk>
