"""Add stig field

Revision ID: b44c092bfa30
Revises: cc7a413cd73c
Create Date: 2024-12-10 11:06:50.402558+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b44c092bfa30'
down_revision = 'cc7a413cd73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_stig', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_security', schema=None) as batch_op:
        batch_op.drop_column('enable_stig')

    # ### end Alembic commands ###
