"""add enclosure_label table

Revision ID: 0a7978b37780
Revises: 4e6f1334f0f0
Create Date: 2024-12-06 16:45:09.138671+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7978b37780'
down_revision = '4e6f1334f0f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosure_label',
        sa.Column('id', sa.String(length=200), nullable=False),
        sa.Column('label', sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint(
            'id',
            name=op.f('pk_enclosure_label')
        ),
        sqlite_autoincrement=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('enclosure_label')
    # ### end Alembic commands ###
