"""Remove MEGA cloud provider

Revision ID: 7c663f5ec8a1
Revises: 249b95f63f76
Create Date: 2025-05-13 11:29:12.009530+00:00

"""
import json
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

from middlewared.plugins.cloud_sync import CloudProviderRemovedAlertClass
from middlewared.utils.time_utils import utc_now


# revision identifiers, used by Alembic.
revision = '7c663f5ec8a1'
down_revision = '249b95f63f76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    if conn.execute(text("""
        DELETE FROM tasks_cloudsync WHERE credential_id IN (
            SELECT id FROM system_cloudcredentials WHERE provider = 'MEGA'
        )
    """)).rowcount > 0:
        args = {"provider": "MEGA"}
        now = utc_now()
        conn.execute(
            'INSERT INTO system_alert (node, source, "key", datetime, text, args, dismissed, uuid, klass, '
            "last_occurrence) VALUES ('A', '', :key, :datetime, :text, :args, 0, :uuid, 'CloudProviderRemoved', "
            ":last_occurrence)",
            {
                "key": json.dumps(args),
                "datetime": now,
                "text": CloudProviderRemovedAlertClass.text % args,
                "args": json.dumps(args),
                "uuid": str(uuid.uuid4()),
                "last_occurrence": now,
            }
        )

    op.execute(text("DELETE FROM system_cloudcredentials WHERE provider = 'MEGA'"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###
