"""Set retention_policy to "Same as Source" for full filesystem replications

Revision ID: 682c6dc4d00b
Revises: af75faf3a0e2
Create Date: 2025-01-17 11:55:48.862206+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text


# revision identifiers, used by Alembic.
revision = '682c6dc4d00b'
down_revision = 'af75faf3a0e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("UPDATE storage_replication SET repl_retention_policy = 'SOURCE' WHERE repl_replicate = 1"))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
