# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 15:34


from django.db import migrations, models


def disk_enclosure_slot(apps, schema_editor):
    field = models.IntegerField(null=True, blank=True)
    field.set_attributes_from_name('disk_enclosure_slot'),
    schema_editor.add_field(
        apps.get_model('storage.Disk'),
        field,
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnclosureLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encid', models.CharField(max_length=200, unique=True)),
                ('label', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(disk_enclosure_slot),
    ]
