"""Certificates revocation

Revision ID: d20ab6a17489
Revises: f2e8d8e7fd57
Create Date: 2019-11-19 21:04:49.865264+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd20ab6a17489'
down_revision = 'f2e8d8e7fd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_revoked_date', sa.DateTime(), nullable=True))

    with op.batch_alter_table('system_certificateauthority', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cert_revoked_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_certificateauthority', schema=None) as batch_op:
        batch_op.drop_column('cert_revoked_date')

    with op.batch_alter_table('system_certificate', schema=None) as batch_op:
        batch_op.drop_column('cert_revoked_date')

    # ### end Alembic commands ###
