"""NFSv4 domain

Revision ID: 514ce6934952
Revises: 115caec86b91
Create Date: 2019-11-19 20:47:28.702007+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '514ce6934952'
down_revision = '115caec86b91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_nfs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nfs_srv_v4_domain', sa.String(length=120), nullable=True))

    op.execute("UPDATE services_nfs SET nfs_srv_v4_domain = ''")

    with op.batch_alter_table('services_nfs', schema=None) as batch_op:
        batch_op.alter_column('nfs_srv_v4_domain',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_nfs', schema=None) as batch_op:
        batch_op.drop_column('nfs_srv_v4_domain')

    # ### end Alembic commands ###
