"""Make sure builtin users are not smb users

Revision ID: 28ecea8be3fb
Revises: 6d3efdc7ba5b
Create Date: 2020-08-07 12:39:23.535263+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28ecea8be3fb'
down_revision = '6d3efdc7ba5b'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE account_bsdusers SET bsdusr_smb = 0 WHERE bsdusr_builtin = 1")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
