"""make netatalk logging configurable

Revision ID: e9e611d7c5a7
Revises: 730c995cbd37
Create Date: 2020-05-21 11:45:15.691643+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e611d7c5a7'
down_revision = '730c995cbd37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_afp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('afp_srv_loglevel', sa.String(length=120), nullable=True))

    op.execute('UPDATE services_afp SET afp_srv_loglevel="MINIMUM"')

    with op.batch_alter_table('services_afp', schema=None) as batch_op:
        batch_op.alter_column('afp_srv_loglevel', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_afp', schema=None) as batch_op:
        batch_op.drop_column('afp_srv_loglevel')

    # ### end Alembic commands ###
