"""remove nmbclusters sysctl

Revision ID: 730c995cbd37
Revises: 434ea5397cd3
Create Date: 2020-05-18 14:29:59.887895+00:00

"""


# revision identifiers, used by Alembic.
revision = '730c995cbd37'
down_revision = '434ea5397cd3'
branch_labels = None
depends_on = None

TABLE = 'system_tunable'


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
