"""Network interface link address

Revision ID: b410e4d0145f
Revises: a3298f120609
Create Date: 2020-10-02 13:41:27.024460+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b410e4d0145f'
down_revision = 'a3298f120609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('int_link_address', sa.String(length=17), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('network_interfaces', schema=None) as batch_op:
        batch_op.drop_column('int_link_address')

    # ### end Alembic commands ###
