"""Convert SMB bindip not null

Revision ID: 43779dce3a07
Revises: 2ab85192c49f
Create Date: 2020-05-01 10:55:52.386403+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43779dce3a07'
down_revision = '2ab85192c49f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE services_cifs SET cifs_srv_bindip = '' WHERE cifs_srv_bindip IS NULL")
    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.alter_column('cifs_srv_bindip',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_cifs', schema=None) as batch_op:
        batch_op.alter_column('cifs_srv_bindip',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###
