"""Remove alerts unique index

Revision ID: ffcd02f6af9f
Revises: 1432b666093e
Create Date: 2020-05-29 16:11:37.779011+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffcd02f6af9f'
down_revision = '1432b666093e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('system_alert', schema=None) as batch_op:
            batch_op.drop_index('system_alert_node_f77e0d77_uniq')
    except Exception:
        # Might be already done by migrate113
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_alert', schema=None) as batch_op:
        batch_op.create_index('system_alert_node_f77e0d77_uniq', ['node', 'klass', 'key'], unique=1)

    # ### end Alembic commands ###
