"""Remove asigra table

Revision ID: 83dae64197f3
Revises: 58339783792c
Create Date: 2020-04-29 18:07:43.037006+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83dae64197f3'
down_revision = '58339783792c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('services_asigra')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services_asigra',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filesystem', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
