"""SNMP iftop

Revision ID: c09a16ca3399
Revises: 56016e596321
Create Date: 2020-10-21 16:19:50.910413+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09a16ca3399'
down_revision = '56016e596321'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_snmp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('snmp_iftop', sa.Boolean(), nullable=True))

    op.execute("UPDATE services_snmp SET snmp_iftop = FALSE")

    with op.batch_alter_table('services_snmp', schema=None) as batch_op:
        batch_op.alter_column('snmp_iftop', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_snmp', schema=None) as batch_op:
        batch_op.drop_column('snmp_iftop')

    # ### end Alembic commands ###
