"""Adding unique constraint on iSCSITargetExtent(name)

Revision ID: d015631e2929
Revises: 90b815426c10
Create Date: 2021-03-21 09:49:26.747269+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd015631e2929'
down_revision = '90b815426c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_iscsitargetextent', schema=None) as batch_op:
        batch_op.create_unique_constraint('iscsi_target_extent_name_unique', ['iscsi_target_extent_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services_iscsitargetextent', schema=None) as batch_op:
        batch_op.drop_constraint('iscsi_target_extent_name_unique', type_='unique')

    # ### end Alembic commands ###
