name: mypy static type checks

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:26

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          cd src/middlewared
          mypy \
            middlewared/plugins/catalog/ \
            middlewared/plugins/cron/ \
            middlewared/plugins/init_shutdown_script/ \
            middlewared/plugins/keyvalue.py \
            middlewared/plugins/ntp/ \
            middlewared/plugins/truenas/ \
            middlewared/plugins/truesearch.py \
            middlewared/plugins/webshare/ \
            middlewared/plugins/update_/ \
            middlewared/plugins/ups/ \
            middlewared/plugins/zfs/ \
            --exclude middlewared/etc_files \
            --follow-imports silent \
            --strict
