name: pytest CI

on:
  pull_request:
    types:
      - 'synchronize'
      - 'opened'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/truenas/middleware:26

    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: |
          cd src/middlewared
          PYTHONPATH=. FAKE_ENV=1 pytest-3 -v --disable-pytest-warnings middlewared/pytest
