"""Fix lacking foreign keys

Revision ID: d38e9cc6174c
Revises: a3423860aea0
Create Date: 2019-09-27 08:20:13.391318+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd38e9cc6174c'
down_revision = 'a3423860aea0'
branch_labels = None
depends_on = None


def create_foreign_key(*args, **kwargs):
    op.execute(f"DELETE FROM {args[1]} WHERE {args[3][0]} NOT IN (SELECT {args[4][0]} FROM {args[2]})")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    create_foreign_key(None, 'account_bsdgroupmembership', 'account_bsdgroups', ['bsdgrpmember_group_id'], ['id'])
    create_foreign_key(None, 'account_bsdgroupmembership', 'account_bsdusers', ['bsdgrpmember_user_id'], ['id'])
    with op.batch_alter_table('account_bsdgroupmembership', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_account_bsdgroupmembership_bsdgrpmember_group_id_account_bsdgroups'), 'account_bsdgroups', ['bsdgrpmember_group_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_account_bsdgroupmembership_bsdgrpmember_user_id_account_bsdusers'), 'account_bsdusers', ['bsdgrpmember_user_id'], ['id'])

    create_foreign_key(None, 'network_lagginterface', 'network_interfaces', ['lagg_interface_id'], ['id'])
    with op.batch_alter_table('network_lagginterface', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_network_lagginterface_lagg_interface_id_network_interfaces'), 'network_interfaces', ['lagg_interface_id'], ['id'])

    create_foreign_key(None, 'storage_encrypteddisk', 'storage_volume', ['encrypted_volume_id'], ['id'])
    with op.batch_alter_table('storage_encrypteddisk', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_storage_encrypteddisk_encrypted_volume_id_storage_volume'), 'storage_volume', ['encrypted_volume_id'], ['id'])

    create_foreign_key(None, 'storage_scrub', 'storage_volume', ['scrub_volume_id'], ['id'])
    with op.batch_alter_table('storage_scrub', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_storage_scrub_scrub_volume_id_storage_volume'), 'storage_volume', ['scrub_volume_id'], ['id'])

    create_foreign_key(None, 'tasks_smarttest_smarttest_disks', 'storage_disk', ['disk_id'], ['disk_identifier'], ondelete='CASCADE')
    create_foreign_key(None, 'tasks_smarttest_smarttest_disks', 'tasks_smarttest', ['smarttest_id'], ['id'], ondelete='CASCADE')
    with op.batch_alter_table('tasks_smarttest_smarttest_disks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tasks_smarttest_smarttest_disks_disk_id_storage_disk'), 'storage_disk', ['disk_id'], ['disk_identifier'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('fk_tasks_smarttest_smarttest_disks_smarttest_id_tasks_smarttest'), 'tasks_smarttest', ['smarttest_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks_smarttest_smarttest_disks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tasks_smarttest_smarttest_disks_smarttest_id_tasks_smarttest'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_tasks_smarttest_smarttest_disks_disk_id_storage_disk'), type_='foreignkey')

    with op.batch_alter_table('storage_scrub', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_storage_scrub_scrub_volume_id_storage_volume'), type_='foreignkey')

    with op.batch_alter_table('storage_encrypteddisk', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_storage_encrypteddisk_encrypted_volume_id_storage_volume'), type_='foreignkey')

    with op.batch_alter_table('network_lagginterface', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_network_lagginterface_lagg_interface_id_network_interfaces'), type_='foreignkey')

    with op.batch_alter_table('account_bsdgroupmembership', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_account_bsdgroupmembership_bsdgrpmember_user_id_account_bsdusers'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_account_bsdgroupmembership_bsdgrpmember_group_id_account_bsdgroups'), type_='foreignkey')

    # ### end Alembic commands ###
