import dataclasses
import secrets
import string
import sys

from .args import RunArgs


@dataclasses.dataclass
class Context(RunArgs):
    # Derived from hostname after auto-generation
    domain: str

    # Network details resolved by get_ipinfo() — not known until runtime
    netmask: str
    gateway: str
    ns1: str | None
    ns2: str | None


def context_from_args(args: RunArgs) -> Context:
    d = dataclasses.asdict(args)

    if args.ha_license_path:
        with open(args.ha_license_path) as f:
            d['ha_license'] = f.read()

    # create random hostname and random fake domain
    # FIXME
    digit = ''.join(secrets.choice((string.ascii_uppercase + string.digits)) for i in range(10))
    # d['hostname'] = args.hostname or f'test{digit}'
    d['hostname'] = args.hostname or f'testAUTOGENERATED'
    domain = f"{d['hostname']}.nb.ixsystems.net"

    ip_to_use = args.ip
    interface, netmask, gateway, ns1, ns2 = get_ipinfo(ip_to_use)

    if not all((interface, netmask, gateway)):
        print(
            f'Unable to determine interface ({interface!r}), netmask ({netmask!r}) and gateway ({gateway!r}) '
            f'for {ip_to_use!r}'
        )
        sys.exit(1)

    # FIXME
    d['interface'] = interface

    return Context(**d, domain=domain, netmask=netmask, gateway=gateway, ns1=ns1, ns2=ns2)


def get_ipinfo(ip_to_use):
    return (
        'eth0',
        '.'.join(ip_to_use.split('.')[:3] + ['128']),
        '.'.join(ip_to_use.split('.')[:3] + ['129']),
        '.'.join(ip_to_use.split('.')[:3] + ['130']),
        '.'.join(ip_to_use.split('.')[:3] + ['131']),
    )

    iface = net = gate = ns1 = ns2 = None
    with client(host_ip=ip_to_use) as c:
        net_config = c.call('network.configuration.config')
        ns1 = net_config.get('nameserver1')
        ns2 = net_config.get('nameserver2')
        _ip_to_use = socket.gethostbyname(ip_to_use)
        for i in c.call('interface.query'):
            for j in i['state']['aliases']:
                if j.get('address') == _ip_to_use:
                    iface = i['id']
                    net = j['netmask']
                    for k in c.call('route.system_routes'):
                        if k.get('network') == '0.0.0.0' and k.get('gateway'):
                            return iface, net, k['gateway'], ns1, ns2

    return iface, net, gate, ns1, ns2
