import dataclasses
import secrets
import string

from .args import RunArgs


@dataclasses.dataclass
class Context(RunArgs):
    # Derived from hostname after auto-generation
    domain: str = ''

    # Network details resolved by get_ipinfo() — not known until runtime
    netmask: str = ''
    gateway: str = ''
    ns1: str | None = None
    ns2: str | None = None


def context_from_args(args: RunArgs) -> Context:
    d = dataclasses.asdict(args)

    if args.ha_license_path:
        with open(args.ha_license_path) as f:
            d['ha_license'] = f.read()

    # create random hostname and random fake domain
    # FIXME
    digit = ''.join(secrets.choice((string.ascii_uppercase + string.digits)) for i in range(10))
    # d['hostname'] = args.hostname or f'test{digit}'
    d['hostname'] = args.hostname or f'testAUTOGENERATED'
    domain = f"{d['hostname']}.nb.ixsystems.net"

    return Context(**d, domain=domain)
