# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-20 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initshutdown_ini_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsync',
            name='transfer_mode',
            field=models.CharField(choices=[('SYNC', 'Sync'), ('COPY', 'Copy'), ('MOVE', 'Move')], default='sync', max_length=20, verbose_name='Transfer Mode'),
        ),
    ]
