# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-30 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cloudsync_transfer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsync',
            name='encryption',
            field=models.BooleanField(default=False, help_text='This option will push encrypted files and decrypt pulled files.', verbose_name='Remote encryption'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudsync',
            name='filename_encryption',
            field=models.BooleanField(default=True, help_text='Also encrypt filenames.', verbose_name='Filename encryption'),
        ),
        migrations.AddField(
            model_name='cloudsync',
            name='encryption_password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cloudsync',
            name='encryption_salt',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
