# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-17 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_cloudsync_transfer_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsync',
            name='args',
            field=models.TextField(default='', blank=True, help_text='These args will be passed to rclone.<br>See <a href="https://rclone.org/docs/">https://rclone.org/docs/</a> for help', max_length=255, verbose_name='Auxiliary args'),
            preserve_default=False,
        ),
    ]
