# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-06-17 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_cloudsync_args'),
        ('tasks', '0004_cloudsync_encryption'),
    ]

    operations = [
    ]
