# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-26 08:35
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20180823_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudsync',
            name='exclude',
            field=freenasUI.freeadmin.models.fields.ListField(default=[], editable=False),
            preserve_default=False,
        ),
    ]
