# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-08 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20181229_0917'),
        ('tasks', '0006_fixinitshutdown'),
    ]

    operations = [
    ]
