# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-16 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_init_tasks_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='initshutdown',
            name='ini_multiline_command',
            field=models.TextField(blank=True, verbose_name='Multiline command'),
        ),
    ]
