# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-17 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import freenasUI.freeadmin.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_add_ini_multiline_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='initshutdown',
            name='ini_type',
            field=models.CharField(choices=[('command', 'Command'), ('multiline_command', 'Multiline command'), ('script', 'Script')], default='command', max_length=17, verbose_name='Type'),
        ),
    ]
